'use client';
import {useMemo,useState} from 'react';
import {ArrowUpRight,Heart,Eye,Share2,Compass,ArrowDownWideNarrow} from 'lucide-react';
import {projects,worldHref,type Project} from '../projects';
import {usePulse,track} from '../activity';
import {WorldDock} from '../components/world-dock';
import './leaderboard.css';
const garden:Project={id:'garden',title:'The in-between',subtitle:'The shared garden',category:'Play',url:'/',art:'reef',tag:'THE SHARED GARDEN'};
const metrics=[{id:'visits',label:'Views',icon:Eye},{id:'favorites',label:'Favorites',icon:Heart},{id:'shares',label:'Shares',icon:Share2},{id:'opens',label:'Portal opens',icon:Compass}] as const;
type Metric=typeof metrics[number]['id'];
export default function Leaderboard(){
 const {pulse,error,favorite}=usePulse('leaderboard'),[metric,setMetric]=useState<Metric>('visits'),[message,setMessage]=useState('');
 const rows=useMemo(()=>projects.filter(p=>p.featured!==false).map(project=>({...project,visits:pulse?.ranking.find(p=>p.project===project.id)?.visits||0,shares:pulse?.ranking.find(p=>p.project===project.id)?.shares||0,opens:pulse?.ranking.find(p=>p.project===project.id)?.opens||0,favorites:pulse?.favorites.find(p=>p.project===project.id)?.favorites||0})).sort((a,b)=>b[metric]-a[metric]||a.title.localeCompare(b.title)),[pulse,metric]);
 const max=rows[0]?.[metric]||1;const total=(m:Metric)=>rows.reduce((n,r)=>n+r[m],0);const first=rows[0];
 const onFavorite=async(id:string)=>{try{const active=await favorite(id);setMessage(active?'Saved to your journey.':'Favorite removed.');}catch(e){setMessage((e as Error).message);}};
 return <main className="constellation-board"><div className="board-sky" aria-hidden="true"><i/><i/><i/><i/><i/></div><div className="board-scroll"><section className="board-title"><span className="eyebrow">THE CURIOSITY INDEX</span><h1>See where<br/>wonder <em>wanders.</em></h1><p>A living record of the worlds people explore, share, and keep close.</p><div className="board-live"><i className={error?'disconnected':''}/>{error?'Reconnecting to the live counts':pulse?`${pulse.active} ${pulse.active===1?'explorer':'explorers'} online`:'Connecting to the live counts'}</div><div className="board-totals"><div><strong>{pulse?total('visits').toLocaleString():'—'}</strong><span>VIEWS · 30 DAYS</span></div><div><strong>{pulse?total('favorites').toLocaleString():'—'}</strong><span>ACTIVE FAVORITES</span></div><div><strong>{pulse?total('shares').toLocaleString():'—'}</strong><span>SHARES · 30 DAYS</span></div></div><details className="board-counting"><summary>What these numbers mean</summary><p>Views and shares count once per browser activity session, per world, per day, over the last 30 days. A favorite stays counted until it is removed. Portal opens measure an action here, not play time inside another site. Tied worlds share a rank. Your private trail is in the compass button.</p><a href="/privacy">Privacy & your data <ArrowUpRight size={12}/></a></details></section>
 <section className="board-ranking" aria-label="World rankings"><div className="board-sort"><span><ArrowDownWideNarrow size={15}/>FOLLOW THE</span><div role="group" aria-label="Rank worlds by">{metrics.map(m=><button key={m.id} aria-pressed={metric===m.id} onClick={()=>setMetric(m.id)}><m.icon size={14}/>{m.label}</button>)}</div></div>{pulse&&first[metric]===0&&<p className="board-empty">A new world starts quietly. Be one of its first explorers.</p>}
 <div className="world-rank-list" role="list">{rows.map((p,i)=>{const rank=rows.findIndex(r=>r[metric]===p[metric])+1,selected=pulse?.saved.includes(p.id);return <div className="world-rank" role="listitem" key={p.id} style={{'--rank-fill':`${p[metric]/max*100}%`,'--rank-delay':`${i*35}ms`} as React.CSSProperties}><span className="rank-number">{pulse?String(rank).padStart(2,'0'):'—'}</span><a href={worldHref(p)} onClick={()=>track('project_open',p.id)} className="rank-world"><small>{p.tag}</small><strong>{p.title}</strong><div className="rank-trace" aria-hidden="true"><i/></div><span className="rank-secondary">{pulse?`${p.visits} views · ${p.shares} shares · ${p.favorites} favorites`:'Waiting for the live record'}</span></a><div className="rank-value"><strong>{pulse?p[metric].toLocaleString():'—'}</strong><span>{metrics.find(m=>m.id===metric)?.label}</span></div><button className={`rank-save ${selected?'saved':''}`} aria-label={`${selected?'Unfavorite':'Favorite'} ${p.title}`} aria-pressed={!!selected} disabled={!pulse} onClick={()=>onFavorite(p.id)}><Heart size={17} fill={selected?'currentColor':'none'}/></button><a className="rank-enter" aria-label={`Enter ${p.title}`} href={worldHref(p)} onClick={()=>track('project_open',p.id)}><ArrowUpRight size={19}/></a></div>;})}</div><p className="board-footnote">A shared place to explore. Counts refresh every 30 seconds.</p></section></div><WorldDock current="leaderboard" pulse={pulse} onFavorite={onFavorite}/>{message&&<button className="toast" onClick={()=>setMessage('')} role="status">{message}</button>}</main>;
}
