import{cueCooldown,frequency,moodForWorld,motifs,musicAllowed,portalBlend,type SoundMood,type SoundSettings}from'./score';

let captureSource:(()=>MediaStreamTrack|null)|null=null;
/** A recording receives its own track. Stopping a clip cannot mute the garden. */
export function getSoundCaptureTrack():MediaStreamTrack|null{return captureSource?.()??null;}

/** A small owned graph: two note buses, a short stereo echo, and bounded voices. */
export class SoundDirector{
 private captureReader=()=>this.captureTrack();
 private capture:MediaStreamAudioDestinationNode|null=null;
 private context:AudioContext|null=null;private music:GainNode|null=null;private effects:GainNode|null=null;private dry:GainNode|null=null;private calm:GainNode|null=null;private color:GainNode|null=null;private echo:DelayNode|null=null;
 private timer:ReturnType<typeof setInterval>|null=null;private tick=0;private nextBeat=0;private path='/';private mood:SoundMood='garden';private blend=0;private settings:SoundSettings={enabled:false,music:.45,effects:.4};private voices=new Set<AudioScheduledSourceNode>();private cooldown=new Map<string,number>();private hidden=false;private ducked=false;private closed=false;
 get running(){return this.context?.state==='running';}
 async unlock(){if(this.closed)return false;try{if(!this.context)this.create();await this.context!.resume();this.nextBeat=this.context!.currentTime+.05;this.sync();this.startClock();return this.running;}catch{return false;}}
 private create(){const Audio=window.AudioContext||(window as unknown as{webkitAudioContext:typeof AudioContext}).webkitAudioContext;if(!Audio)throw new Error('Audio unavailable');const c=this.context=new Audio({latencyHint:'interactive'});this.music=c.createGain();this.effects=c.createGain();this.calm=c.createGain();this.color=c.createGain();this.dry=c.createGain();const compressor=c.createDynamicsCompressor();compressor.threshold.value=-16;compressor.knee.value=12;compressor.ratio.value=4;compressor.attack.value=.02;compressor.release.value=.25;this.dry.gain.value=.72;this.calm.connect(this.music);this.color.connect(this.music);this.music.connect(this.dry);this.effects.connect(this.dry);this.dry.connect(compressor);compressor.connect(c.destination);this.capture=c.createMediaStreamDestination();compressor.connect(this.capture);captureSource=this.captureReader;this.echo=c.createDelay(2);this.echo.delayTime.value=.39;const feedback=c.createGain(),wet=c.createGain(),filter=c.createBiquadFilter();feedback.gain.value=.22;wet.gain.value=.18;filter.type='lowpass';filter.frequency.value=2200;this.music.connect(this.echo);this.echo.connect(filter);filter.connect(feedback);feedback.connect(this.echo);filter.connect(wet);wet.connect(this.dry);this.music.gain.value=0;this.effects.gain.value=0;this.calm.gain.value=1;this.color.gain.value=0;}
 private ramp(node:GainNode|null,value:number,seconds=.45){if(!node||!this.context)return;const t=this.context.currentTime;node.gain.cancelScheduledValues(t);node.gain.setTargetAtTime(value,t,seconds);}
 setSettings(settings:SoundSettings){this.settings={...settings};this.sync();if(!settings.enabled){this.stopClock();this.clearVoices();void this.context?.suspend();}else if(this.running)this.startClock();}
 setRoute(path:string){this.path=path;this.mood=path==='/telescope'?'curiosity':'garden';this.blend=path==='/telescope'?1:0;this.sync();}
 proximity(worldId:string,distance:number){if(this.path!=='/')return;this.mood=moodForWorld(worldId);this.blend=portalBlend(distance);this.sync();}
 setDucked(ducked:boolean){this.ducked=ducked;this.sync();}
 async setHidden(hidden:boolean){this.hidden=hidden;if(hidden){this.stopClock();this.clearVoices();await this.context?.suspend();}else if(this.settings.enabled&&this.context){try{await this.context.resume();this.nextBeat=this.context.currentTime+.08;this.sync();this.startClock();}catch{/* The next explicit sound gesture can resume playback. */}}}
 private sync(){const enabled=this.settings.enabled&&!this.hidden;this.ramp(this.music,enabled&&musicAllowed(this.path)?this.settings.music*(this.ducked?.18:1):0,.35);this.ramp(this.effects,enabled?this.settings.effects:0,.03);this.ramp(this.calm,Math.cos(this.blend*Math.PI/2),.8);this.ramp(this.color,Math.sin(this.blend*Math.PI/2),.8);}
 private startClock(){if(this.timer||!this.running||!this.settings.enabled||this.hidden)return;this.timer=setInterval(()=>this.schedule(),180);this.schedule();}
 private stopClock(){if(this.timer)clearInterval(this.timer);this.timer=null;}
 private schedule(){const c=this.context;if(!c||!this.running||this.hidden||!this.settings.enabled)return;if(this.nextBeat<c.currentTime-.4)this.nextBeat=c.currentTime+.05;while(this.nextBeat<c.currentTime+.3){const beat=this.tick++;if(musicAllowed(this.path)&&this.settings.music>0){const calmNote=motifs.garden[beat%motifs.garden.length],colorNote=motifs[this.mood][beat%motifs[this.mood].length];if(calmNote>=0)this.note(calmNote,this.nextBeat,1.75,.043,this.calm!,false,Math.sin(beat*.4)*.35);if(colorNote>=0)this.note(colorNote,this.nextBeat,1.4,.034,this.color!,this.mood==='curiosity',Math.cos(beat*.57)*.3);if(beat%6===0){this.note(38,this.nextBeat,5.4,.026,this.calm!,false,-.25);this.note(this.mood==='mystery'?45:50,this.nextBeat,5.2,.02,this.color!,false,.25);}}this.nextBeat+=1.22;}}
 private own(source:AudioScheduledSourceNode){this.voices.add(source);source.onended=()=>{this.voices.delete(source);source.disconnect();};}
 private note(midi:number,when:number,duration:number,level:number,target:GainNode,glass=false,pan=0){const c=this.context;if(!c||this.voices.size>42)return;const envelope=c.createGain(),stereo=c.createStereoPanner();stereo.pan.value=pan;envelope.gain.setValueAtTime(.00001,when);envelope.gain.exponentialRampToValueAtTime(level,when+(glass?.025:.16));envelope.gain.exponentialRampToValueAtTime(level*.64,when+duration*.32);envelope.gain.exponentialRampToValueAtTime(.00001,when+duration);envelope.connect(stereo);stereo.connect(target);const ratios=glass?[1,2.002,3.003]:[1,2,3],levels=glass?[1,.18,.07]:[1,.13,.025];ratios.forEach((ratio,i)=>{const osc=c.createOscillator(),gain=c.createGain();osc.type='sine';osc.frequency.value=frequency(midi)*ratio;osc.detune.setValueAtTime(i?-.8:0,when);gain.gain.value=levels[i];osc.connect(gain);gain.connect(envelope);this.own(osc);osc.addEventListener('ended',()=>{gain.disconnect();if(i===2){envelope.disconnect();stereo.disconnect();}});osc.start(when);osc.stop(when+duration+.05);});}
 cue(kind:string){const c=this.context;if(!c||!this.running||!this.settings.enabled||!this.settings.effects||this.hidden||!Object.hasOwn(cueCooldown,kind))return;const now=c.currentTime,last=this.cooldown.get(kind)??-Infinity;if((now-last)*1000<cueCooldown[kind])return;this.cooldown.set(kind,now);const notes=kind==='favorite'?[74,81]:kind==='achievement'?[62,69,74,81]:kind==='portal'?[50,62,69]:[81,74];notes.forEach((n,i)=>this.note(n,now+i*.115,kind==='portal'?1.35:.45,.085,this.effects!,true));}
 private clearVoices(){for(const voice of this.voices){try{voice.stop();}catch{/* already stopped */}}this.voices.clear();}
 captureTrack():MediaStreamTrack|null{if(!this.settings.enabled||!this.running||this.hidden)return null;return this.capture?.stream.getAudioTracks()[0]?.clone()??null;}
 dispose(){if(captureSource===this.captureReader)captureSource=null;this.capture?.stream.getTracks().forEach(track=>track.stop());this.closed=true;this.stopClock();for(const voice of this.voices){try{voice.stop();}catch{/* already stopped */}}this.voices.clear();void this.context?.close();this.context=null;}
}
