'use client';
import {useMemo,useState,type CSSProperties} from 'react';
import {projects} from '../projects';
import './analytics-scene.css';
export type MeasuredEvent={project:string;name:string;total:number;sessions:number};
export type EntryChannel={channel:string;visits:number};
const measures={visit:{label:'Visits',events:['visit']},share:{label:'Shares',events:['share']},open:{label:'Portal opens',events:['project_open']},interact:{label:'Interactions',events:['first_interaction']},capture:{label:'Captures',events:['clip','screenshot']}};
type Measure=keyof typeof measures;
const palette:Record<string,string>={Understand:'#8fc8c1',Play:'#d9b277',Watch:'#a7a9d4',Lobby:'#a0bb93',Other:'#94a4b0'};
export default function AnalyticsScene({events,channels}:{events:MeasuredEvent[];channels?:EntryChannel[]}){
 const[measure,setMeasure]=useState<Measure>('visit'),[category,setCategory]=useState('All'),[selected,setSelected]=useState<string|null>(null);
 const rows=useMemo(()=>{const ids=[...new Set([...projects.filter(p=>p.featured!==false).map(p=>p.id),...events.map(e=>e.project)])];return ids.map(id=>{const project=projects.find(p=>p.id===id);const group=id==='garden'?'Lobby':project?.category||'Other';const count=events.filter(e=>e.project===id&&(measures[measure].events as string[]).includes(e.name)).reduce((sum,e)=>sum+Math.max(0,e.sessions),0);return{id,title:id==='garden'?'The in-between':project?.title||id,category:group,count,color:palette[group]||palette.Other};}).filter(row=>category==='All'||row.category===category).sort((a,b)=>b.count-a.count||a.title.localeCompare(b.title));},[events,measure,category]);
 const max=Math.max(1,...rows.map(r=>r.count)),sum=rows.reduce((n,r)=>n+r.count,0),focus=rows.find(r=>r.id===selected)||rows[0];
 const sourceNames:Record<string,string>={direct:'Direct / unknown',x:'X',github:'GitHub',search:'Search',shared:'Tagged shared links',other:'Other sites'};
 const sources=(channels||[]).filter(c=>Object.hasOwn(sourceNames,c.channel)&&Number.isFinite(c.visits)&&c.visits>=0).sort((a,b)=>b.visits-a.visits),sourceMax=Math.max(1,...sources.map(c=>c.visits));
 return <section className="analytics-scene" aria-labelledby="analytics-scene-heading"><div className="analytics-scene-heading"><div><span className="analytics-kicker">YOUR WORLDS, IN MOTION</span><h2 id="analytics-scene-heading">Watch curiosity take shape.</h2><p>Each tower is one world. Choose a signal to see where visitors spend their curiosity.</p></div><div className="analytics-total"><strong>{sum.toLocaleString()}</strong><span>{measures[measure].label.toLowerCase()} · {category==='All'?'all worlds':category.toLowerCase()}</span></div></div>
 <div className="analytics-controls"><div className="analytics-measures" role="group" aria-label="Activity to compare">{(Object.keys(measures) as Measure[]).map(id=><button key={id} aria-pressed={measure===id} onClick={()=>{setMeasure(id);setSelected(null);}}>{measures[id].label}</button>)}</div><label>Worlds <select value={category} onChange={e=>{setCategory(e.target.value);setSelected(null);}}>{['All','Understand','Play','Watch','Lobby'].map(c=><option key={c}>{c}</option>)}</select></label></div>
 <div className="analytics-skyline" role="group" aria-label={`${measures[measure].label} by world. Counts are browser sessions per action, not unique people.`}><div className="analytics-grid" aria-hidden="true"><span>{max}</span><span>{Math.round(max/2)}</span><span>0</span></div><div className="analytics-towers">{rows.map((row,i)=><button key={row.id} className={`analytics-tower ${focus?.id===row.id?'selected':''}`} style={{'--height':`${row.count/max*100}%`,'--tower-color':row.color,'--tower-order':i} as CSSProperties} aria-label={`${row.title}: ${row.count} ${measures[measure].label.toLowerCase()}, ${row.category}`} aria-pressed={focus?.id===row.id} onClick={()=>setSelected(row.id)}><span className="analytics-tower-value">{row.count}</span><span className="analytics-tower-body" aria-hidden="true"><i/></span><span className="analytics-tower-label">{row.title}</span></button>)}</div></div>
 {focus?<div className="analytics-world-detail" aria-live="polite"><i style={{background:focus.color}}/><strong>{focus.title}</strong><span>{focus.category}</span><b>{focus.count.toLocaleString()} {measures[measure].label.toLowerCase()}</b></div>:<p>No worlds in this category yet.</p>}
 {!sum&&<p className="analytics-empty">No {measures[measure].label.toLowerCase()} recorded for this selection yet. New activity will appear on the next refresh.</p>}
 <p className="analytics-explainer">Last 30 days. Counts are distinct browser sessions per action and world. Totals add these counts; one session can appear in several worlds or actions. They are not unique people, impressions or completed shares.</p>
 <div className="analytics-sources"><h3>How the journey begins.</h3><p>First site-entry source for each browser session. This measures arrivals here, not views on X or another platform.</p>{sources.length?<div className="analytics-source-list">{sources.map(source=><div className="analytics-source" key={source.channel}><span>{sourceNames[source.channel]}</span><div><i style={{width:`${source.visits/sourceMax*100}%`}}/></div><b>{source.visits.toLocaleString()}</b></div>)}</div>:<p className="analytics-empty">Source collection has just begun. No recorded arrivals yet.</p>}</div>
 </section>;
}
