'use client';
import {GithubIcon} from './github-icon';
import './membership.css';
import{useState}from'react';import{X,ArrowUpRight,Copy,Check,Heart}from'lucide-react';
export const sourceUrl='https://github.com/Arnie016/pure-exploration';
export function About({onClose,onRemix}:{onClose:()=>void;onRemix?:()=>void}){return <div className="modal-backdrop"><section className="studio-modal" role="dialog" aria-modal="true" aria-label="About Arnav"><button className="close-modal" aria-label="Close about" onClick={onClose}><X size={18}/></button><span className="eyebrow">HELLO. I’M ARNAV.</span><h2>I build things<br/>you can <em>get lost in.</em></h2><p>Little worlds. Useful experiments. Games that started with “what if?” Pure Exploration brings them together in one place.</p><p>Walk in, try something, follow a question somewhere unexpected. Everything here is free to explore.</p><div className="about-links"><a className="primary" href="https://x.com/itsArnz" target="_blank" rel="noreferrer">Follow @itsArnz on X <ArrowUpRight size={16}/></a><a className="outline-button" href={sourceUrl} target="_blank" rel="noreferrer"><GithubIcon size={16}/>Pure Exploration on GitHub <ArrowUpRight size={16}/></a>{onRemix&&<button className="text-button" onClick={onRemix}>Make this world your own <ArrowUpRight size={16}/></button>}</div><p className="small-copy">Made by Arnav with Codex. The garden, telescope, and airport are original procedural worlds. Interaction inspiration includes Ryan Sael’s wonderful <a href="https://sael.net/plane-of-focus/" target="_blank" rel="noreferrer">Plane of Focus</a>. Third-party projects keep their own credits and terms.</p></section></div>;}
export function Membership({onClose,world='Through the Glass'}:{onClose:()=>void;world?:string}){
 const[agent,setAgent]=useState('ChatGPT'),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false),[tier,setTier]=useState('supporter'),[promptIndex,setPromptIndex]=useState(0);
 const courseUrl='https://www.udemy.com/course/openai-codex-ai-agent-workflows/?referralCode=9394549FD2DB6B765A06';
 const tiers=[
  {id:'supporter',title:'Supporter',price:'1.99',caption:'Appreciate the worlds',intro:'Help more little worlds take shape.',benefits:['A monthly build note and newsletter about new worlds, AI and science.','A supporter thank-you in your explorer profile.'],availability:'Newsletter delivery and supporter recognition are being prepared.'},
  {id:'workshop',title:'Workshop',price:'4.99',caption:'Learn how they’re made',intro:'Follow an idea from first prompt to working world.',benefits:['Everything proposed for Supporter.','Curated prompt packs, annotated workflows and remix walkthroughs.','Course-related learning notes and offers, when confirmed.'],availability:'Paid prompt packs and course offers are being prepared. Udemy enrollment is a separate purchase.'},
  {id:'collaborator',title:'Collaborator',price:'8.99',caption:'Start a conversation',intro:'Bring a question, a prototype or a thoughtful contribution.',benefits:['Everything proposed for Workshop.','A member email channel for build questions and collaboration requests.','Small group office hours, subject to a published schedule.'],availability:'The email channel, office-hour schedule and response terms are still being defined.'}
 ];
 const selected=tiers.find(t=>t.id===tier)!;
 const optics=/glass|telescope|optics/i.test(world),airside=/airport|airside/i.test(world),garden=/garden|lobby|in-between/i.test(world),space=/space.time|solar|thirty steps|edge.*universe|observable/i.test(world),reef=/reef|coral/i.test(world);
 const focus=optics?'Read app/telescope/ray-bench.tsx, app/telescope/ray-optics.ts and app/optics.ts.':airside?'Read app/airport/workspace.tsx, app/airport/simulation.ts and app/airport/learning.ts.':garden?'Read app/garden.tsx, app/garden-scene.tsx and app/garden-landscape.ts.':space?'Find this world in app/projects.ts, then inspect its linked local files under public/games.':reef?'Find Reef / Memory in app/projects.ts and inspect public/games/coral-memory.':'Find this world in app/projects.ts and inspect the linked local game files before changing it.';
 const prompts=[
  {title:'Understand it',text:optics?'Trace one colored ray through a lens and a mirror. Explain which controls change focal length, where focus occurs, and which approximations the simulation uses.':airside?'Trace one robot task from sensor observation to route choice. Explain uncertainty, battery cost and what is simulated rather than learned from a real airport.':garden?'Trace how a real visitor joins the garden, moves a fox and enters a portal. Explain where presence updates arrive and which multiplayer features are still local.':space?'Trace one orbit or light-travel thought experiment in this world. Identify its units, timing assumptions and the controls that change the result.':reef?'Trace one coral colony through warming and recovery. Explain the illustrated history, local field notes and limits of the simulation.':`Trace the main interaction in ${world}. Explain its controls, state changes and current limitations using the code as evidence.`},
  {title:'Change one thing',text:optics?'Add one guided experiment comparing an achromatic lens with a single lens. Reuse the existing light bench, label the model’s limits and keep the rays readable.':airside?'Add one bounded scenario where a sensor fails. Show the route before and after, explain the changed decision and preserve the current simulator controls.':garden?'Improve one portal approach with an original visual landmark. Keep collision paths open and check keyboard movement and reduced motion.':space?'Add one saved comparison between two orbital or light-travel scenarios. Keep the assumptions visible and preserve the original scene.':reef?'Add one clear field-note filter for a selected coral colony. Keep notes in this browser and preserve the night-dive controls.':`Improve one specific interaction in ${world}. Propose a small change, preserve the existing game loop and implement the chosen improvement.`},
  {title:'Prove the change',text:'Run the checks appropriate to the changed files. Exercise the touched interaction with keyboard and pointer controls, at desktop and narrow widths. Report what passed, what remains unverified and which source files changed. Preserve original credits and add a concise attribution for your contribution.'}
 ];
 const brief=`Help me understand and customize ${world} from ${sourceUrl}.\nStart by reading README.md and the existing code. ${focus}\n\n${prompts[promptIndex].text}\n\nKeep secrets outside source, preserve honest simulation labels, and retain keyboard and reduced-motion support. Inherit an idea. Make it better. Credit the source.`;
 async function copyPrompt(){try{await navigator.clipboard.writeText(brief);setCopied(true);setCopyError(false);}catch{setCopied(false);setCopyError(true);}}
 return <div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="membership-title" className="studio-modal membership">
  <button className="close-modal" aria-label="Close membership" onClick={onClose}><X size={18}/></button>
  <span className="eyebrow">MAKE IT YOUR OWN</span><h2 id="membership-title">Make it<br/><em>your own.</em></h2><p className="member-ethos">Inherit an idea. Make it better. Credit the source.</p>
  <div className="member-free"><Heart size={14}/><span>All current games, favorites, sharing and public source remain free.</span><a href={sourceUrl} target="_blank" rel="noreferrer" aria-label="Open Pure Exploration source on GitHub"><GithubIcon size={17}/></a></div>
  <div className="member-tier-heading"><span>Proposed monthly tiers</span><small>US dollars · preview</small></div>
  <div className="member-tiers" role="group" aria-label="Preview a proposed membership tier">{tiers.map(t=><button key={t.id} aria-pressed={tier===t.id} onClick={()=>setTier(t.id)}><span>{t.title}</span><strong>US${t.price}<small>/mo</small></strong><em>{t.caption}</em></button>)}</div>
  <section className="member-benefit-reveal" key={selected.id} aria-labelledby="member-tier-title"><div className="member-benefit-heading"><h3 id="member-tier-title">{selected.title}</h3><span>Planned benefits</span></div><p>{selected.intro}</p><ul>{selected.benefits.map(b=><li key={b}>{b}</li>)}</ul><p className="member-availability">{selected.availability}</p></section>
  <p className="member-checkout-state" role="status"><span/>Payments are not open yet. Prices and benefits are proposed.</p>
  <details className="member-starter" open><summary>Free mini prompt pack <span>{world}</span></summary><div className="member-prompt-tabs" role="group" aria-label="Choose a free starter prompt">{prompts.map((p,i)=><button key={p.title} aria-pressed={promptIndex===i} onClick={()=>{setPromptIndex(i);setCopied(false);setCopyError(false);}}>{p.title}</button>)}</div><label className="member-agent">Your coding companion<select value={agent} onChange={e=>setAgent(e.target.value)}>{['ChatGPT','Claude','Cursor','Codex','OpenCode'].map(a=><option key={a}>{a}</option>)}</select></label><pre>{brief}</pre><div className="member-prompt-actions"><button className="outline-button" onClick={copyPrompt}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Copied':'Copy prompt'}</button>{['ChatGPT','Claude'].includes(agent)?<a className="text-button" target="_blank" rel="noreferrer" href={agent==='ChatGPT'?`https://chatgpt.com/?q=${encodeURIComponent(brief)}`:`https://claude.ai/new?q=${encodeURIComponent(brief)}`}>Open in {agent} <ArrowUpRight size={14}/></a>:<span>Open the repo in {agent} and paste the prompt.</span>}</div>{copyError&&<p role="status" className="member-availability">Copy was unavailable. Select the prompt text above to copy it.</p>}<p className="member-provider-note">Use your own coding-agent account. Provider usage charges follow your own plan.</p></details>
  <a className="member-course" href={courseUrl} target="_blank" rel="noreferrer"><span>View Codex course on Udemy<small>Referral link · course checkout is separate</small></span><ArrowUpRight size={16}/></a>
 </section></div>;
}
