export type MomentKind='image'|'video'|'audio'|'note'|'achievement';
export type Moment={id:string;kind:MomentKind;worldId:string;title:string;created:number;blob?:Blob;note:string};
export const LIBRARY_LIMIT_BYTES=200*1024*1024,LIBRARY_LIMIT_ITEMS=80;
let database:Promise<IDBDatabase>|null=null;
function db(){if(database)return database;database=new Promise<IDBDatabase>((resolve,reject)=>{if(typeof indexedDB==='undefined'){reject(new Error('This browser cannot keep a library. You can still download your captures.'));return;}const request=indexedDB.open('pure-exploration-library',1);request.onupgradeneeded=()=>request.result.createObjectStore('moments',{keyPath:'id'});request.onsuccess=()=>{request.result.onversionchange=()=>{request.result.close();database=null;};resolve(request.result);};request.onerror=()=>{database=null;reject(new Error('The library could not open. Check your browser’s storage settings.'));};request.onblocked=()=>{database=null;reject(new Error('Close other Pure Exploration tabs, then try again.'));};});return database;}
export function validateMoment(m:Pick<Moment,'kind'|'title'|'note'|'blob'>){if(!['image','video','audio','note','achievement'].includes(m.kind)||!m.title.trim()||m.title.length>120||m.note.length>2000)return 'This discovery has invalid details.';if(m.blob&&m.blob.size>40*1024*1024)return 'This file is larger than 40 MB. Keep a downloaded copy instead.';if(m.kind!=='note'&&!m.blob?.size)return 'There is no media to save.';const type=m.blob?.type.split(';')[0];const family=m.kind==='image'||m.kind==='achievement'?'image':m.kind;const formats:Record<string,RegExp>={image:/^image\/(png|jpeg|webp)$/,video:/^video\/(mp4|webm)$/,audio:/^audio\/(mpeg|mp3|wav|x-wav|ogg|webm|mp4)$/};if(m.kind!=='note'&&(!type||!formats[family]?.test(type)))return 'This media format does not match the kind of discovery.';return null;}
export async function listMoments(){const d=await db();return new Promise<Moment[]>((resolve,reject)=>{const req=d.transaction('moments').objectStore('moments').getAll();req.onsuccess=()=>resolve((req.result as Moment[]).sort((a,b)=>b.created-a.created));req.onerror=()=>reject(new Error('Your library could not be read. Try again.'));});}
export async function saveMoment(input:Omit<Moment,'id'|'created'> & {id?:string;created?:number}){const error=validateMoment(input);if(error)throw new Error(error);const d=await db(),moment:Moment={...input,id:input.id||crypto.randomUUID(),created:input.created||Date.now()};await new Promise<void>((resolve,reject)=>{const tx=d.transaction('moments','readwrite'),store=tx.objectStore('moments'),read=store.getAll();let reason='Your browser could not save this discovery. Download a copy or free some library space.';read.onsuccess=()=>{const previous=(read.result as Moment[]).filter(m=>m.id!==moment.id);const bytes=previous.reduce((n,m)=>n+(m.blob?.size||0),0)+(moment.blob?.size||0);if(previous.length>=LIBRARY_LIMIT_ITEMS||bytes>LIBRARY_LIMIT_BYTES){reason='Your library is full. Download and remove an older item, then try again.';tx.abort();return;}store.put(moment);};tx.oncomplete=()=>resolve();tx.onerror=tx.onabort=()=>reject(new Error(reason));});window.dispatchEvent(new CustomEvent('pe-library-change',{detail:{id:moment.id}}));return moment;}
export async function removeMoment(id:string){const d=await db();await new Promise<void>((resolve,reject)=>{const tx=d.transaction('moments','readwrite');tx.objectStore('moments').delete(id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(new Error('Could not remove this item. Try again.'));});window.dispatchEvent(new Event('pe-library-change'));}
export function momentFilename(m:Moment){const ext=m.kind==='note'?'txt':m.blob?.type.includes('png')?'png':m.blob?.type.includes('jpeg')?'jpg':m.blob?.type.includes('webp')?'webp':m.blob?.type.includes('mp4')?'mp4':m.blob?.type.includes('webm')?'webm':m.blob?.type.includes('ogg')?'ogg':m.blob?.type.includes('wav')?'wav':'mp3';return `${m.worldId}-${m.kind}-${new Date(m.created).toISOString().slice(0,10)}.${ext}`;}
export function downloadMoment(m:Moment){const url=URL.createObjectURL(m.blob||new Blob([m.note],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=momentFilename(m);a.click();setTimeout(()=>URL.revokeObjectURL(url),20000);}
