'use client';
import {useState} from 'react';
import {ArrowUpRight,Search,X,Footprints} from 'lucide-react';
import {projects,worldHref} from '../projects';
import {track} from '../activity';
import {ProjectArt} from './collection';
export function PortalDirectory({current,onClose}:{current:string;onClose:()=>void}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All');
 const available=projects.filter(p=>p.featured!==false),rows=available.filter(p=>(category==='All'||p.category===category)&&(p.title+' '+p.subtitle+' '+p.tag).toLowerCase().includes(query.toLowerCase()));
 return <div className="modal-backdrop portal-directory-backdrop" onClick={e=>{if(e.target===e.currentTarget)onClose();}}><section className="studio-modal portal-atlas" role="dialog" aria-modal="true" aria-label="World portals"><button className="close-modal" aria-label="Close portals" onClick={onClose}><X size={18}/></button><header><span className="eyebrow">FOLLOW YOUR CURIOSITY</span><h2>Choose your <em>next world.</em></h2><p>A little science. A little danger. A door worth opening.</p></header><div className="portal-browser-tools"><label className="portal-search"><Search size={17}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Stars, storms, pirates…" aria-label="Search portals"/></label><div role="group" aria-label="Portal categories">{[['All','All worlds'],['Understand','Science & systems'],['Play','Games & adventures'],['Watch','Stories & films']].map(([value,label])=><button key={value} aria-pressed={category===value} onClick={()=>setCategory(value)}>{label}</button>)}</div></div><div className="portal-entries">{rows.map(p=><a className={`portal-entry ${p.id===current?'is-here':''}`} key={p.id} href={worldHref(p)} onClick={e=>{if(p.id===current){e.preventDefault();onClose();}else track('project_open',p.id);}} onMouseEnter={e=>void e.currentTarget.querySelector('video')?.play().catch(()=>{})} onMouseLeave={e=>e.currentTarget.querySelector('video')?.pause()} onFocus={e=>void e.currentTarget.querySelector('video')?.play().catch(()=>{})} onBlur={e=>e.currentTarget.querySelector('video')?.pause()}><div className="portal-thumbnail"><ProjectArt project={p}/>{p.trailer&&<video src={p.trailer} muted playsInline loop preload="none"/>}<span>{p.id===current?'YOU ARE HERE':p.category==='Understand'?'EXPLORE':p.category==='Watch'?'WATCH':'PLAY'}</span></div><div className="portal-entry-copy"><small>{p.tag}</small><strong>{p.title}</strong><p>{p.subtitle}</p><span>{p.id===current?'Return to this world':p.category==='Watch'?'Enter the story':'Step through'}<ArrowUpRight size={15}/></span></div></a>)}</div>{!rows.length&&<div className="portal-empty"><p>No doors match that search.</p><button onClick={()=>{setQuery('');setCategory('All');}}>Show all worlds</button></div>}<footer><span>{available.length} connected worlds · open to everyone</span><a href="/?walk=1"><Footprints size={15}/>Go to lobby<ArrowUpRight size={14}/></a></footer></section></div>;
}
