'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,Footprints,Search,X} from 'lucide-react';
import {projects} from '../projects';
import {type Pulse} from '../activity';
import {WorldCinemaRail,worldCategories} from './world-cinema';
import './portal-directory.css';
import {ExplorationTree} from './exploration-tree';
export function PortalDirectory({current,onClose,pulse=null,onFavorite,initialView='constellation'}:{current:string;onClose:()=>void;pulse?:Pulse|null;onFavorite?:(id:string)=>void;initialView?:'shelves'|'constellation'}){
 const [view,setView]=useState(initialView),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),dialog=useRef<HTMLElement>(null),search=useRef<HTMLInputElement>(null),close=useRef(onClose);
 useEffect(()=>{close.current=onClose;},[onClose]);
 const available=projects.filter(p=>p.featured!==false&&p.category!=='Tools'),rows=available.filter(p=>(category==='All'||p.category===category)&&(p.title+' '+p.subtitle+' '+p.tag).toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;(view==='constellation'?dialog.current?.querySelector<HTMLElement>('.exploration-map-viewport'):search.current)?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();close.current();return;}if(e.key!=='Tab')return;const all=Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input,summary,[tabindex="0"]')||[]).filter(el=>el.getClientRects().length>0),first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[]);
 return <section className={`portal-cinema ${view==='constellation'?'is-map':''}`} ref={dialog} role="dialog" aria-modal="true" aria-label="World portals"><button className="portal-cinema-close" aria-label="Close portals" onClick={onClose}><X size={19}/><span>Back to world</span></button><div className="portal-cinema-scroll">{view==='shelves'&&<header className="portal-cinema-intro"><span>THE WORLD COLLECTION</span><h2>Find your <em>next world.</em></h2><p>Move along a shelf. Hover to preview a world.</p></header>}<div className="portal-cinema-view" role="group" aria-label="Portal view"><button aria-pressed={view==='shelves'} onClick={()=>setView('shelves')}>Shelves</button><button aria-pressed={view==='constellation'} onClick={()=>setView('constellation')}>Map</button></div><div className="portal-cinema-tools">{view==='shelves'&&<div role="group" aria-label="Portal categories"><button aria-pressed={category==='All'} onClick={()=>setCategory('All')}>All worlds</button>{worldCategories.map(c=><button key={c.id} aria-pressed={category===c.id} onClick={()=>setCategory(c.id)}>{c.label}</button>)}</div>}<label><Search size={16}/><input ref={search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Stars, storms, pirates…" aria-label="Search portals"/></label></div>{view==='constellation'?<ExplorationTree worlds={rows} pulse={pulse} current={current} onOpenAchievements={()=>{onClose();setTimeout(()=>window.dispatchEvent(new Event('pe-open-achievements')),0);}}/>:worldCategories.map(c=>{const group=rows.filter(p=>p.category===c.id);return group.length?<WorldCinemaRail key={c.id} title={c.label} description={c.description} worlds={group} pulse={pulse} current={current} onFavorite={onFavorite}/>:null;})}{!rows.length&&<div className="portal-cinema-empty"><h3>No worlds match that search.</h3><p>Try another name or show all worlds.</p><button onClick={()=>{setQuery('');setCategory('All');}}>Show all worlds</button></div>}{view==='shelves'&&<footer className="portal-cinema-footer"><span>{available.length} connected worlds · free to explore</span><Link href="/?walk=1" prefetch={false}><Footprints size={15}/>Go to lobby<ArrowUpRight size={14}/></Link></footer>}</div></section>;
}
