'use client';
import {useState} from 'react';
import {X,ChevronLeft,ChevronRight,RotateCcw,Expand,ArrowUpRight} from 'lucide-react';
import {type Project} from '../projects';
import {sourceUrl} from './about';
import './world-help.css';
export function WorldHelp({project,onClose}:{project:Project;onClose:()=>void}){
 const[step,setStep]=useState(0),[notice,setNotice]=useState('');
 const guides:Record<string,{start:string;keys:string;goal:string}>={
 'plate-engine':{start:'Drag to orbit the Earth cutaway, then follow the eight stops from mantle currents to an island volcano.',keys:'Drag: orbit · Scroll or pinch: zoom · Arrow keys: orbit the focused scene · + / −: zoom · Use the stop buttons and pause control to explore',goal:'Try Break the megathrust to see a quake and tsunami. Change mantle heat, then visit the Arc to compare the volcano forecast. Distances and time are compressed for this illustrative model.'},
 'coral-memory':{start:'You enter straight into the reef. Drag to look around; click a coral to open its dossier.',keys:'Drag: orbit · Scroll or pinch: zoom · Space: timeline · T: tour · N: night dive · P: photo mode · C: save photo',goal:'Move the timeline back to 2020 and watch a simulated heatwave. Select a colony, compare its history, then pin a note. Your notes stay on this device.'},
 'edge-universe':{start:'Press Play to descend from the observable universe toward the smallest scales.',keys:'Space: play / pause · ← / →: previous / next layer · Drag the timeline or choose a named layer',goal:'Pause at any scale and compare its size. Speed controls let you take the journey at your own pace.'},
 glorp:{start:'Enter the arena and move your alien hero into position.',keys:'A / D or ← / →: move · Space: fire',goal:'Watch the boss, dodge its attacks, and find your opening. An original alien action game.'},
 skyline:{start:'Choose Start a run. Open Controls first if you want to learn the moves.',keys:'← / → or A / D: lanes and corners · Space / ↑: hop · ↓ / S: dive · Aim and hold mouse: web swing · E: shockwave · P: pause',goal:'Follow the city route, collect pickups, and take on missions. Hero Studio, checkpoints and the journal keep your local journey.'},
 'hollow-bloom':{start:'Click to begin. Search the pharmacy for medical supplies; keep quiet around infected enemies.',keys:'WASD: move · Shift: run · C: crouch · Hold Q: listen · E: interact · F: knife · H: heal · Tab: backpack and crafting',goal:'Find supplies and escape. Noise attracts infected enemies; ammunition is limited. Mouse: aim and attack.'},
 tides:{start:'Choose a callsign and ship, then choose Guided for your first voyage.',keys:'W / S: sail speed · A / D: steer · Q / R: broadsides · Space: bow cannon · H: all controls',goal:'Reach the first marked port. Use the sea chart to set a course; the arrow points toward your selected destination.'},
 'fable-flight':{start:'Choose Clear Circuit and press Begin Flight. Press E for departure checks, then hold W to add throttle.',keys:'W / S: throttle · ↓: nose up · ↑: nose down · ← / →: roll · A / D: rudder · Space: brake · E: checks',goal:'For the first takeoff, add full throttle and gently pull ↓ at 55 kt. Follow the training gates. This is a simulation, not flight instruction.'},
 galevein:{start:'Press Start, then Explore for free flight or Story to follow the beacon trail.',keys:'W / S: speed · ↑ / ↓: climb / dive · A / D: turn · Space: flap · V: camera · X: plasma',goal:'Gain height and follow the glowing beacons. Explore turns off the keeper hunt while you learn to fly.'},
 lightning:{start:'Press BEGIN to follow the 60-second journey, or open LIGHTNING LAB to experiment.',keys:'Pause and drag the timeline to inspect any instant. PHYSICS reveals the quantities behind the scene.',goal:'Watch charge separate, follow the stepped leader, then meet the upward streamer.'},
 'universe-clash':{start:'Pick a fighter, then choose Local Pit or a Duel against AI.',keys:'The game shows the active fighter’s controls when a match starts. Click inside the arena to focus it.',goal:'Training is the easiest first stop. Online human matchmaking is not connected in this edition.'},
 poe:{start:'Choose a film, or open Read the stories for a short Poe retelling.',keys:'Space: play / pause · M: sound · ← / →: seek · Escape: close story',goal:'Explore the Masque, Usher and the Raven. Switch between moving scenes and readable retellings.'},
 aeolith:{start:'Choose an AI match style and launch your ship.',keys:'Use the match’s controls panel. Click inside the arena to focus the game.',goal:'This is Meridian Clash AI practice; cloud progression and matchmaking are not connected.'}
 };

 const guide=guides[project.id];
 const slides=[{title:'Step inside',text:guide?.start||project.subtitle},{title:'Find your controls',text:guide?.keys||'Use the controls shown inside the world.'},{title:'Try this first',text:guide?.goal||'Explore at your own pace. Your next portal is always nearby.'}];
 return <div className="modal-backdrop"><section className="world-help" role="dialog" aria-modal="true" aria-labelledby="world-help-title"><header><span>HELP · {project.category==='Watch'?'STORY':project.category==='Play'?'GAME':'WORLD'}</span><button className="close-modal" aria-label="Close help" onClick={onClose}><X size={20}/></button></header><h2 id="world-help-title">{project.title}</h2><p className="help-intro">{project.subtitle}</p><div className="help-slide" aria-live="polite">{project.image&&<img src={project.image} alt={`${project.title} scene preview`}/>}<div className="help-slide-copy"><span>{step+1} / 3</span><h3>{slides[step].title}</h3>{step===1?<div className="help-keys">{slides[step].text.split(' · ').map(k=><span key={k}>{k}</span>)}</div>:<p>{slides[step].text}</p>}</div></div><nav aria-label="Guide slides"><button disabled={step===0} onClick={()=>setStep(step-1)}><ChevronLeft size={18}/>Back</button><div>{slides.map((slide,i)=><button key={slide.title} aria-label={`Guide ${i+1}: ${slide.title}`} aria-current={step===i?'step':undefined} onClick={()=>setStep(i)}>{i+1}</button>)}</div><button disabled={step===2} onClick={()=>setStep(step+1)}>Next<ChevronRight size={18}/></button></nav><div className="help-actions"><button onClick={()=>{if(project.embed==='frame')window.dispatchEvent(new CustomEvent('pe-reset-world',{detail:{worldId:project.id}}));else location.reload();onClose();}}><RotateCcw size={17}/>Reset world</button><button onClick={()=>document.documentElement.requestFullscreen?.().catch(()=>setNotice('Fullscreen is unavailable in this browser.'))}><Expand size={17}/>Fullscreen</button><a href={`/notes/${project.id}`}>Behind this world<ArrowUpRight size={16}/></a></div><details><summary>About Arnav & resources</summary><p>Original worlds and experiments by Arnav, built with Codex. Explore, inherit an idea and credit its source.</p><div><a href={sourceUrl} target="_blank" rel="noreferrer">GitHub<ArrowUpRight size={15}/></a><a href="https://x.com/itsArnz" target="_blank" rel="noreferrer">Arnav on X<ArrowUpRight size={15}/></a></div></details>{notice&&<p role="status">{notice}</p>}</section></div>;
}
