import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';import ts from 'typescript';
const transpile=p=>ts.transpileModule(readFileSync(p,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const data=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const source=transpile('worker/explorers.ts').replace("'@clerk/backend'",JSON.stringify(import.meta.resolve('@clerk/backend'))).replace("'../app/projects'",JSON.stringify(data(transpile('app/projects.ts'))));
const {explorers,discoveryWorlds}=await import(data(source));
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));const DB={prepare(q){let args=[];const statement={bind(...a){args=a;return statement;},async run(){return sql.prepare(q).run(...args);},async all(){return {results:sql.prepare(q).all(...args)};},async first(){return sql.prepare(q).get(...args)||null;}};return statement;},async batch(s){return Promise.all(s.map(x=>x.run()));}};return{sql,DB};}
const pair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
const pem='-----BEGIN PUBLIC KEY-----\n'+Buffer.from(await crypto.subtle.exportKey('spki',pair.publicKey)).toString('base64')+'\n-----END PUBLIC KEY-----';
async function token(subject='user_one',azp='https://example.com'){const enc=x=>Buffer.from(JSON.stringify(x)).toString('base64url');const now=Math.floor(Date.now()/1000),body=enc({alg:'RS256',typ:'JWT'})+'.'+enc({sub:subject,sid:'sess_one',iss:'https://example.clerk.accounts.dev',azp,iat:now,nbf:now-5,exp:now+120});return body+'.'+Buffer.from(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',pair.privateKey,new TextEncoder().encode(body))).toString('base64url');}
const visitor='11111111-1111-1111-1111-111111111111';
function req(action,auth,extras={}){return new Request('https://example.com/api/explorers',{method:'POST',headers:{Origin:'https://example.com','Content-Type':'application/json',Cookie:'pe_visitor='+visitor,...(auth?{Authorization:'Bearer '+auth}:{})},body:JSON.stringify({action,alias:'Comet Fox',...extras})});}
const setup=()=>({...fixture(),CLERK_JWT_KEY:pem,CLERK_PUBLISHABLE_KEY:'pk_test_fixture'});
test('anonymous browsing stays available; unconfigured sign-in cannot join',async()=>{const env=fixture();let r=await explorers(new Request('https://example.com/api/explorers'),env);const body=await r.json();assert.deepEqual(body.rows,[]);assert.equal(body.configured,false);assert.equal((await explorers(req('join'),env)).status,503);});
test('verified sign-in alone does not opt in; forged and other-origin tokens fail',async()=>{const env=setup();assert.equal((await explorers(req('status',await token()),env)).status,200);assert.equal(env.sql.prepare('SELECT count(*) n FROM explorer_profiles').get().n,0);assert.equal((await explorers(req('join','forged'),env)).status,401);assert.equal((await explorers(req('join',await token('user_one','https://evil.com')),env)).status,401);const request=req('join',await token());request.headers.set('Origin','https://evil.com');assert.equal((await explorers(request,env)).status,403);});
test('join imports distinct catalog worlds only; replay cannot inflate ranks, leave and delete work',async()=>{const env=setup(),auth=await token();for(const world of ['telescope','hollow-bloom','leaderboard','made-up'])env.sql.prepare('INSERT INTO journeys(visitor,project,visits,opens,updated) VALUES(?,?,?,?,?)').run(visitor,world,9,20,1);let r=await explorers(req('join',auth,{worlds:999,badges:999}),env);assert.equal(r.status,200);let data=await r.json();assert.equal(data.rows[0].worlds,2);assert.equal(data.rows[0].rank,1);assert.ok(!JSON.stringify(data).includes('user_one'));assert.ok(discoveryWorlds.includes('hollow-bloom'));await explorers(req('sync',auth),env);data=await(await explorers(new Request('https://example.com/api/explorers'),env)).json();assert.equal(data.rows[0].worlds,2);await explorers(req('leave',auth),env);assert.equal((await(await explorers(new Request('https://example.com/api/explorers'),env)).json()).rows.length,0);assert.equal((await explorers(req('sync',auth),env)).status,409);await explorers(req('delete',auth),env);assert.equal(env.sql.prepare('SELECT count(*) n FROM explorer_worlds').get().n,0);});
test('ties share a rank and private profiles never appear',async()=>{const env=setup();for(const [id,visible] of [['one',1],['two',1],['private',0]]){env.sql.prepare('INSERT INTO explorer_profiles VALUES(?,?,?,?,?)').run(id,'public_'+id,id,visible,1);env.sql.prepare('INSERT INTO explorer_worlds VALUES(?,?,?)').run(id,'telescope',1);}const data=await(await explorers(new Request('https://example.com/api/explorers'),env)).json();assert.equal(data.rows.length,2);assert.deepEqual(data.rows.map(x=>x.rank),[1,1]);});

test('deleting a visible profile returns refreshed rankings immediately',async()=>{const env=setup(),auth=await token();await explorers(req('join',auth),env);const result=await(await explorers(req('delete',auth),env)).json();assert.equal(result.profile,null);assert.deepEqual(result.rows,[]);assert.equal(env.sql.prepare('SELECT count(*) n FROM explorer_profiles').get().n,0);});
