import test from 'node:test';import assert from 'node:assert/strict';import{readFileSync}from'node:fs';import{createRequire}from'node:module';import vm from'node:vm';
const require=createRequire(import.meta.url),ts=require('typescript');
const source=readFileSync(new URL('../app/components/google-analytics.tsx',import.meta.url),'utf8'),code=ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
function runtime({origin='https://pure-exploration.arnz.chatgpt.site',privacy=false,dnt=null,choice=null,storageFails=false}={}){
 const hooks=[],listeners=new Map(),stored=new Map(choice?[['pe-optional-analytics-v1',choice]]:[]),scripts=[],cookieWrites=[],win={},doc={getElementById:id=>scripts.find(s=>s.id===id),createElement:()=>({remove(){const i=scripts.indexOf(this);if(i>=0)scripts.splice(i,1);}}),head:{appendChild:s=>scripts.push(s)}};
 Object.defineProperty(doc,'cookie',{get:()=>'',set:v=>cookieWrites.push(v)});win.addEventListener=(k,fn)=>{if(!listeners.has(k))listeners.set(k,new Set());listeners.get(k).add(fn);};win.removeEventListener=(k,fn)=>listeners.get(k)?.delete(fn);win.dispatchEvent=e=>{for(const fn of listeners.get(e.type)||[])fn(e);};
 const ctx={exports:{},window:win,location:{origin,hostname:new URL(origin).hostname,pathname:'/telescope',search:'?secret=private',hash:'#secret'},document:doc,navigator:{globalPrivacyControl:privacy,doNotTrack:dnt},localStorage:{getItem:k=>{if(storageFails)throw Error();return stored.get(k)||null;},setItem:(k,v)=>{if(storageFails)throw Error();stored.set(k,v);}},Event:class{constructor(type){this.type=type;}},require:p=>p==='react'?{useEffect:fn=>hooks.push(fn),useRef:v=>({current:v}),useState:v=>[v,()=>{}]}:p==='next/navigation'?{usePathname:()=>'/telescope'}:p==='react/jsx-runtime'?{jsx:()=>null,jsxs:()=>null}:{},console};
 vm.runInNewContext(code,ctx);ctx.exports.default();hooks.forEach(fn=>fn());return{api:ctx.exports,win,scripts,cookieWrites,ctx};
}
test('only explicit opt-in on exact production origin without a privacy signal qualifies',()=>{const{api}=runtime();for(const choice of[null,'declined'])assert.equal(api.analyticsAllowed(choice,api.ANALYTICS_ORIGIN,false),false);assert.equal(api.analyticsAllowed('accepted',api.ANALYTICS_ORIGIN,false),true);assert.equal(api.analyticsAllowed('accepted','http://localhost:4317',false),false);assert.equal(api.analyticsAllowed('accepted',api.ANALYTICS_ORIGIN+'.evil.example',false),false);assert.equal(api.analyticsAllowed('accepted',api.ANALYTICS_ORIGIN,true),false);assert.equal(api.privacySignal({globalPrivacyControl:true}),true);assert.equal(api.privacySignal({doNotTrack:'1'}),true);});
test('page and event allowlists exclude private paths and arbitrary data',()=>{const{api}=runtime();assert.equal(api.analyticsPage('/telescope?email=secret#secret'),api.ANALYTICS_ORIGIN+'/telescope');assert.equal(api.analyticsPage('/studio'),null);assert.equal(api.analyticsPage('/world/person@example.com'),null);assert.equal(api.analyticsEvent('comment','garden'),null);assert.equal(api.analyticsEvent('share','private-email@example.com'),null);assert.equal(api.analyticsEvent('__proto__','garden'),null);assert.equal(api.analyticsEvent('share','garden').world_id,'garden');});
test('mount and decline produce no script; accepting loads once with sanitized manual pageview',()=>{const r=runtime();assert.equal(r.scripts.length,0);r.api.setAnalyticsChoice('declined');assert.equal(r.scripts.length,0);r.api.setAnalyticsChoice('accepted');assert.equal(r.scripts.length,1);assert.equal(r.scripts[0].referrerPolicy,'no-referrer');r.win.dispatchEvent(new r.ctx.Event('pe-analytics-preference'));assert.equal(r.scripts.length,1);const rows=r.win.dataLayer.map(v=>Array.from(v));assert.equal(rows.filter(v=>v[0]==='event'&&v[1]==='page_view').length,1);const cfg=rows.find(v=>v[0]==='config')[2];assert.equal(cfg.send_page_view,false);assert.equal(cfg.allow_google_signals,false);assert.equal(cfg.allow_ad_personalization_signals,false);assert.equal(cfg.page_referrer,'');assert.equal(cfg.page_location,'https://pure-exploration.arnz.chatgpt.site/telescope');assert.ok(!JSON.stringify(rows).includes('secret'));});
test('privacy signals and development origins never load Google even after acceptance',()=>{for(const props of[{privacy:true},{dnt:'1'},{origin:'http://localhost:4317'}]){const r=runtime(props);r.api.setAnalyticsChoice('accepted');assert.equal(r.scripts.length,0);r.api.trackOptionalAnalytics('share','telescope');assert.equal(r.win.dataLayer,undefined);}});
test('revocation disables sending; only allowlisted event names and world IDs reach the queue',()=>{const r=runtime();r.api.setAnalyticsChoice('accepted');r.scripts[0].onload();r.api.trackOptionalAnalytics('share','telescope');r.api.trackOptionalAnalytics('comment','telescope');r.api.trackOptionalAnalytics('share','my-secret-id');const before=r.win.dataLayer.length;assert.equal(Array.from(r.win.dataLayer.at(-1))[1],'world_share');r.api.setAnalyticsChoice('declined');assert.equal(r.win['ga-disable-'+r.api.GA_MEASUREMENT_ID],true);r.api.trackOptionalAnalytics('share','garden');assert.equal(r.win.dataLayer.length,before);});
test('storage failure keeps explicit choice in memory and still permits decline',()=>{const r=runtime({storageFails:true});assert.equal(r.scripts.length,0);r.api.setAnalyticsChoice('accepted');assert.equal(r.scripts.length,1);assert.equal(r.api.readAnalyticsChoice(),'accepted');r.api.setAnalyticsChoice('declined');assert.equal(r.api.readAnalyticsChoice(),'declined');assert.equal(r.win['ga-disable-'+r.api.GA_MEASUREMENT_ID],true);});
