import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {loaded} from '../public/games/hollow-bloom/assets.js';
import {Enemy} from '../public/games/hollow-bloom/ai.js';
function fixtureRig(){const scene=new THREE.Group();const hips=new THREE.Bone();hips.name='Hips';const geometry=new THREE.BoxGeometry(.5,1.7,.3),count=geometry.attributes.position.count;geometry.setAttribute('skinIndex',new THREE.Uint16BufferAttribute(new Uint16Array(count*4),4));const weights=new Float32Array(count*4);for(let i=0;i<count;i++)weights[i*4]=1;geometry.setAttribute('skinWeight',new THREE.Float32BufferAttribute(weights,4));const mesh=new THREE.SkinnedMesh(geometry,new THREE.MeshStandardMaterial());mesh.add(hips);mesh.bind(new THREE.Skeleton([hips]));scene.add(mesh);const clips={};for(const name of ['idle','walk','run','attack','death','scream'])clips[name]=new THREE.AnimationClip(name,1,[new THREE.QuaternionKeyframeTrack('Hips.quaternion',[0,1],[0,0,0,1,0,0,0,1])]);return {base:{scene},clips,def:{height:1.72}}}
function world(){return {scene:new THREE.Scene(),audio:{},fx:{},player:{},enemies:[]}}
test('production Enemy mounts existing animated rig inside original gameplay root; big variant height and fallback stay valid',()=>{loaded.chars.knocker=fixtureRig();const w=world(),e=new Enemy({id:'fixture',type:'knocker',x:2,z:2},w);assert.equal(e.c.ok,true);assert.equal(e.c.root.parent,e.h.root);const base=e.c.meshes[0],silhouette=base.parent.children.find(c=>c.isSkinnedMesh&&c.material===e.h.silMat);assert.ok(silhouette);assert.equal(silhouette.skeleton,base.skeleton);assert.equal(e.h.root.children.filter(c=>c!==e.c.root).every(c=>!c.visible),true);assert.equal(w.scene.children.includes(e.h.root),true);assert.equal(e.cfg.reach,1.15);const big=new Enemy({id:'big',type:'bigknocker',x:3,z:2},w);big.h.root.updateMatrixWorld(true);big.c.root.traverse(o=>{if(o.isSkinnedMesh){o.skeleton.update();o.computeBoundingBox()}});assert.ok(Math.abs(new THREE.Box3().setFromObject(big.c.root,true).getSize(new THREE.Vector3()).y-2.15)<.001);const fallback=new Enemy({id:'fallback',type:'frenzied',x:4,z:2},w);assert.equal(fallback.c,null);assert.equal(fallback.h.root.children.some(c=>c.visible),true);e.dispose();assert.equal(w.scene.children.includes(e.h.root),false);delete loaded.chars.knocker});
test('production rig follows actual displacement, attack window and one-shot death without restarting each frame',()=>{loaded.chars.lurker=fixtureRig();const e=new Enemy({id:'fixture',type:'lurker',x:2,z:2},world());e.updateRig(.1,0);assert.equal(e.c.currentName,'idle');e.updateRig(.1,1.4);assert.equal(e.c.currentName,'walk');e.updateRig(.1,4.7);assert.equal(e.c.currentName,'run');e.rigAttackT=.8;e.updateRig(.1,0);assert.equal(e.c.currentName,'attack');e.alive=false;e.updateRig(.1,0);assert.equal(e.c.currentName,'death');const before=e.c.current.time;e.updateRig(.1,0);assert.ok(e.c.current.time>before);assert.equal(e.c.current.loop,THREE.LoopOnce);e.rigAttackT=0;e.alive=true;e.updateRig(.1,0);assert.equal(e.c.currentName,'idle');delete loaded.chars.lurker});
