import test from 'node:test';import assert from 'node:assert/strict';import{initial,optics,parseState,stateQuery}from'../app/optics.ts';import{makeSim,step,dispatch,reposition,defaults,metrics}from'../app/airport/simulation.ts';
test('optics: dimensional formulas and aperture scaling',()=>{const a=optics({...initial,aperture:100,focal:800,eyepiece:20});assert.equal(a.magnification,40);assert.equal(a.exitPupil,2.5);assert.equal(a.field,1.3);assert.ok(Math.abs(a.resolution-1.384)<.003);const b=optics({...initial,aperture:200,focal:800,eyepiece:20});assert.equal(b.lightGain/a.lightGain,4);assert.equal(b.resolution/a.resolution,.5);});
test('share state clamps invalid input and round trips controls',()=>{const s=parseState('?aperture=Infinity&focus=NaN&scope=evil&focal=-80&eyepiece=100');assert.equal(s.aperture,initial.aperture);assert.equal(s.focus,initial.focus);assert.equal(s.scope,'refractor');assert.equal(s.focal,400);assert.equal(s.eyepiece,40);const v={...initial,scope:'reflector',target:'moon',aperture:200,focus:1.5};const round=parseState('?'+stateQuery(v));for(const key of['scope','target','aperture','focus'])assert.equal(round[key],v[key]);});
test('airport seeded state and independent object updates',()=>{const a=makeSim(),b=makeSim();assert.deepEqual(a,b);step(a,defaults,.2);assert.deepEqual(a,b);assert.equal(a.assets.length,28);});
test('edge guardian holds stale assets and rejects dispatch',()=>{let s=makeSim();const c={...defaults,scenario:'stale'};for(let i=0;i<40;i++)s=step(s,c,.2);const a=s.assets[0];assert.equal(a.mode,'held');assert.ok(a.age>5);const pos=[a.x,a.z];for(let i=0;i<10;i++)s=step(s,c,.2);assert.deepEqual([s.assets[0].x,s.assets[0].z],pos);const refused=dispatch(s,'R-01',3);assert.equal(refused.requests,s.requests);assert.equal(refused.prevented,s.prevented+1);assert.match(refused.log[0].text,/refused/);});
test('occupied seats cannot be dispatched',()=>{const s=makeSim(),a=s.assets.find(a=>a.occupied);const after=dispatch(s,a.id,2);assert.match(after.log[0].text,/seat occupied/);assert.equal(after.requests,0);});
test('adaptive polling consumes less simulated sensing energy in the same baseline',()=>{let a=makeSim(),b=makeSim();for(let i=0;i<600;i++){a=step(a,defaults,.2);b=step(b,{...defaults,policy:'fixed'},.2);}assert.ok(a.energy<b.energy*.6);assert.ok(a.packets<b.packets);assert.ok(a.assets.every(x=>Number.isFinite(x.x)&&Number.isFinite(x.uncertainty)&&x.battery>=0&&x.battery<=100));assert.ok(metrics(a).power>0);});
test('all sensors unavailable eventually holds all movable assets',()=>{let s=makeSim();const c={...defaults,sensors:{rfid:false,uwb:false,vision:false,imu:false,textile:false}};for(let i=0;i<40;i++)s=step(s,c,.2);assert.ok(s.assets.every(a=>a.mode==='held'));assert.equal(s.packets,0);});
test('layout editing is bounded and cannot inject invalid positions',()=>{const s=makeSim();assert.equal(reposition(s,'R-01',NaN,2),s);const b=reposition(s,'R-01',100,-100).assets[0];assert.equal(b.x,17);assert.equal(b.z,-6.5);assert.equal(b.mode,'idle');});
