import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';import ts from 'typescript';
const source=ts.transpileModule(readFileSync('worker/skyline-billing.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const {skylineBilling}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const keys=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
const pem='-----BEGIN PRIVATE KEY-----\n'+Buffer.from(await crypto.subtle.exportKey('pkcs8',keys.privateKey)).toString('base64')+'\n-----END PRIVATE KEY-----';
function setup(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync('docs/pending-migrations/0003_skyline_billing.sql','utf8'));sql.exec(readFileSync('docs/pending-migrations/0004_skyline_coin_shop.sql','utf8'));const db={prepare(q){let values=[];return {bind(...args){values=args;return this},async first(){return sql.prepare(q).get(...values)??null},async all(){return {results:sql.prepare(q).all(...values)}},async run(){return {meta:{changes:sql.prepare(q).run(...values).changes}}}}},async batch(statements){sql.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};return {sql,env:{DB:db,SKYLINE_PAYMENTS_ENABLED:'sandbox',GOOGLE_PLAY_SERVICE_ACCOUNT_EMAIL:'test@example.invalid',GOOGLE_PLAY_SERVICE_ACCOUNT_PRIVATE_KEY:pem}}}
function request(path,body,session){return new Request('https://example.invalid/api/skyline/'+path,{method:body===undefined?'GET':'POST',headers:{...(session?{Authorization:'Bearer '+session}:{}),'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)})}
async function account(env){return (await skylineBilling(request('account',{}),env)).json()}
function purchase(member,product='skyline_coins_1500'){return {obfuscatedExternalAccountId:member,testPurchaseContext:{fopType:'TEST'},purchaseStateContext:{purchaseState:'PURCHASED'},acknowledgementState:'ACKNOWLEDGEMENT_STATE_PENDING',productLineItem:[{productId:product,productOfferDetails:{quantity:1,refundableQuantity:1,consumptionState:'CONSUMPTION_STATE_YET_TO_BE_CONSUMED'}}]}}
function google(p,failAck=false){return async(url)=>String(url).includes('oauth2')?Response.json({access_token:'fixture'}):String(url).includes('productsv2')?Response.json(p):new Response(null,{status:failAck?503:204})}
async function verify(env,a,p,token='fixture-token',fail=false){const response=await skylineBilling(request('verify',{productId:p.productLineItem[0].productId,purchaseToken:token},a.sessionToken),env,google(p,fail));return {response,data:await response.json()}}
test('server-created credentials hashed, recovery rotates and invalidates old session',async()=>{const {env,sql}=setup(),a=await account(env);assert.match(a.sessionToken,/^[a-f0-9]{64}$/);assert.notEqual(sql.prepare('SELECT session_hash FROM skyline_members').get().session_hash,a.sessionToken);const r=await skylineBilling(request('recover',{memberId:a.memberId,recoveryToken:a.recoveryToken}),env);assert.equal(r.status,200);assert.equal((await skylineBilling(request('entitlements',undefined,a.sessionToken),env)).status,401);assert.equal((await skylineBilling(request('recover',{memberId:a.memberId,recoveryToken:a.recoveryToken}),env)).status,401)});
test('missing auth and disabled server cannot grant',async()=>{const {env}=setup(),a=await account(env);assert.equal((await skylineBilling(request('verify',{}),env)).status,401);env.SKYLINE_PAYMENTS_ENABLED=undefined;assert.equal((await verify(env,a,purchase(a.memberId))).response.status,503)});
test('pending and cancelled purchases grant nothing',async()=>{for(const state of ['PENDING','CANCELLED']){const {env}=setup(),a=await account(env),p=purchase(a.memberId);p.purchaseStateContext.purchaseState=state;const r=await verify(env,a,p);assert.equal(r.data.wallet?.coins??0,0);assert.equal(r.response.status,state==='PENDING'?200:409)}});
test('wrong account, non-test, refunded quantity and product mismatch rejected',async()=>{for(const mutation of [p=>p.obfuscatedExternalAccountId='other',p=>delete p.testPurchaseContext,p=>p.productLineItem[0].productOfferDetails.refundableQuantity=0,p=>p.productLineItem.push(p.productLineItem[0])]){const {env}=setup(),a=await account(env),p=purchase(a.memberId);mutation(p);assert.notEqual((await verify(env,a,p)).response.status,200)}});
test('replay and concurrent verification credit exactly once',async()=>{const {env,sql}=setup(),a=await account(env),p=purchase(a.memberId);await Promise.all([verify(env,a,p),verify(env,a,p),verify(env,a,p)]);assert.equal(sql.prepare('SELECT coins FROM skyline_wallets').get().coins,1500);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_purchases').get().n,1);const b=await account(env);assert.equal((await verify(env,b,p)).response.status,409)});
test('failed settlement is retryable without duplicate grant',async()=>{const {env}=setup(),a=await account(env),p=purchase(a.memberId);const first=await verify(env,a,p,'fixture-token',true);assert.equal(first.data.settlement,'retry');assert.equal(first.data.wallet.coins,1500);const second=await verify(env,a,p);assert.equal(second.data.settlement,'complete');assert.equal(second.data.wallet.coins,1500)});
test('already consumed unknown token is not granted',async()=>{const {env}=setup(),a=await account(env),p=purchase(a.memberId);p.productLineItem[0].productOfferDetails.consumptionState='CONSUMPTION_STATE_CONSUMED';assert.equal((await verify(env,a,p)).response.status,409)});
test('founder bundle once, durable gadgets spend with replay and overspend protection',async()=>{const {env}=setup(),a=await account(env),p=purchase(a.memberId,'skyline_founder_bundle');let r=await verify(env,a,p);assert.deepEqual(r.data.entitlements,['founder']);assert.deepEqual(r.data.wallet,{coins:1500,net:3,smoke:3});assert.equal((await verify(env,a,p,'different-token')).response.status,409);for(let i=0;i<3;i++){const id='spend-request-000'+i;const res=await skylineBilling(request('spend',{item:'net',requestId:id},a.sessionToken),env);assert.equal(res.status,200);assert.equal((await skylineBilling(request('spend',{item:'net',requestId:id},a.sessionToken),env)).status,200)}assert.equal((await skylineBilling(request('spend',{item:'net',requestId:'spend-request-9999'},a.sessionToken),env)).status,409)});
test('public account input bounded and provisioning rate limited',async()=>{const {env}=setup();const huge=await skylineBilling(request('account',{x:'a'.repeat(8193)}),env);assert.equal(huge.status,413);for(let i=0;i<60;i++)assert.equal((await skylineBilling(request('account',{}),env)).status,200);assert.equal((await skylineBilling(request('account',{}),env)).status,429)});
test('concurrent paid gadget spend cannot overdraw or reuse id across items',async()=>{const {env,sql}=setup(),a=await account(env);await verify(env,a,purchase(a.memberId,'skyline_gadget_pack'));const answers=await Promise.all(Array.from({length:5},(_,i)=>skylineBilling(request('spend',{item:'net',requestId:'concurrent-spend-00'+i},a.sessionToken),env)));assert.equal(answers.filter(r=>r.status===200).length,3);assert.equal(sql.prepare('SELECT net FROM skyline_wallets').get().net,0);const id='concurrent-spend-000';assert.equal((await skylineBilling(request('spend',{item:'smoke',requestId:id},a.sessionToken),env)).status,409)});
test('paid coins buy fixed catalogue gadgets once and return authoritative balances',async()=>{const {env}=setup(),a=await account(env);await verify(env,a,purchase(a.memberId));const body={item:'net',requestId:'coin-buy-request-0001'};let res=await skylineBilling(request('buy',body,a.sessionToken),env);assert.equal(res.status,200);assert.deepEqual((await res.json()).wallet,{coins:1300,net:1,smoke:0});res=await skylineBilling(request('buy',body,a.sessionToken),env);assert.deepEqual((await res.json()).wallet,{coins:1300,net:1,smoke:0});res=await skylineBilling(request('buy',{item:'smoke',requestId:'coin-buy-request-0002'},a.sessionToken),env);assert.deepEqual((await res.json()).wallet,{coins:1150,net:1,smoke:1});assert.equal((await skylineBilling(request('buy',{item:'smoke',requestId:body.requestId},a.sessionToken),env)).status,409)});
test('concurrent paid coin buys cannot overdraw and concurrent identical id grants once',async()=>{const {env,sql}=setup(),a=await account(env);await verify(env,a,purchase(a.memberId));let answers=await Promise.all(Array.from({length:5},()=>skylineBilling(request('buy',{item:'net',requestId:'repeated-coin-buy-0001'},a.sessionToken),env)));assert.equal(answers.filter(r=>r.status===200).length,5);assert.deepEqual(sql.prepare('SELECT coins,net,smoke FROM skyline_wallets').get(),Object.assign(Object.create(null),{coins:1300,net:1,smoke:0}));answers=await Promise.all(Array.from({length:10},(_,i)=>skylineBilling(request('buy',{item:'net',requestId:'unique-coin-buy-000'+i},a.sessionToken),env)));assert.equal(answers.filter(r=>r.status===200).length,6);assert.equal(sql.prepare('SELECT coins FROM skyline_wallets').get().coins,100);assert.equal(sql.prepare('SELECT net FROM skyline_wallets').get().net,7)});
test('client prices quantities unknown items and unauthenticated buys rejected',async()=>{const {env}=setup(),a=await account(env);await verify(env,a,purchase(a.memberId));for(const body of [{item:'net',price:1},{item:'net',quantity:100},{item:'__proto__'},{item:'revive'},{item:'net',cost:0}])assert.equal((await skylineBilling(request('buy',{...body,requestId:'wrong-price-buy-0001'},a.sessionToken),env)).status,400);assert.equal((await skylineBilling(request('buy',{item:'net',requestId:'anonymous-buy-0001'}),env)).status,401);const res=await skylineBilling(request('entitlements',undefined,a.sessionToken),env);assert.deepEqual((await res.json()).wallet,{coins:1500,net:0,smoke:0})});
test('sandbox economy remains closed when server flag disabled',async()=>{const {env}=setup(),a=await account(env);await verify(env,a,purchase(a.memberId,'skyline_founder_bundle'));env.SKYLINE_PAYMENTS_ENABLED=undefined;for(const path of ['buy','spend'])assert.equal((await skylineBilling(request(path,{item:'net',requestId:'closed-economy-0001'},a.sessionToken),env)).status,503);const res=await skylineBilling(request('entitlements',undefined,a.sessionToken),env);assert.deepEqual((await res.json()).wallet,{coins:1500,net:3,smoke:3})});
