import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';import ts from 'typescript';
const source=ts.transpileModule(readFileSync('worker/skyline-billing.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const {skylineBilling,skylineDeletionMaintenance}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const keys=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
const pem='-----BEGIN PRIVATE KEY-----\n'+Buffer.from(await crypto.subtle.exportKey('pkcs8',keys.privateKey)).toString('base64')+'\n-----END PRIVATE KEY-----';
function setup(){let failBatchAt=-1;const sql=new DatabaseSync(':memory:');sql.exec(readFileSync('drizzle/0003_skyline_billing.sql','utf8'));sql.exec(readFileSync('drizzle/0004_skyline_coin_shop.sql','utf8'));sql.exec(readFileSync('drizzle/0005_skyline_refunds.sql','utf8'));sql.exec(readFileSync('drizzle/0006_skyline_partial_refunds.sql','utf8'));sql.exec(readFileSync('drizzle/0008_skyline_deletion_requests.sql','utf8'));sql.exec(readFileSync('drizzle/0009_skyline_deletion_completion.sql','utf8'));sql.exec(readFileSync('drizzle/0010_skyline_deletion_health.sql','utf8'));sql.exec(readFileSync('drizzle/0011_skyline_production_billing.sql','utf8'));const db={prepare(q){let values=[];return {bind(...args){values=args;return this},async first(){return sql.prepare(q).get(...values)??null},async all(){return {results:sql.prepare(q).all(...values)}},execute(){return /^SELECT\b/i.test(q)?{results:sql.prepare(q).all(...values),meta:{changes:0}}:{results:[],meta:{changes:sql.prepare(q).run(...values).changes}}},async run(){return this.execute()}}},async batch(statements){sql.exec('BEGIN');try{const out=[];for(let i=0;i<statements.length;i++){if(i===failBatchAt){failBatchAt=-1;throw new Error("injected_batch_failure");}out.push(statements[i].execute())};sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};return {sql,failBatchAt(index){failBatchAt=index},env:{DB:db,SKYLINE_PAYMENTS_ENABLED:'sandbox',GOOGLE_PLAY_SERVICE_ACCOUNT_EMAIL:'test@example.invalid',GOOGLE_PLAY_SERVICE_ACCOUNT_PRIVATE_KEY:pem}}}
function request(path,body,session){return new Request('https://example.invalid/api/skyline/'+path,{method:body===undefined?'GET':'POST',headers:{...(session?{Authorization:'Bearer '+session}:{}),'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)})}
async function account(env){return (await skylineBilling(request('account',{}),env)).json()}
function purchase(member,product='skyline_coins_1500'){return {obfuscatedExternalAccountId:member,testPurchaseContext:{fopType:'TEST'},purchaseStateContext:{purchaseState:'PURCHASED'},acknowledgementState:'ACKNOWLEDGEMENT_STATE_PENDING',productLineItem:[{productId:product,productOfferDetails:{quantity:1,refundableQuantity:1,consumptionState:'CONSUMPTION_STATE_YET_TO_BE_CONSUMED'}}]}}
function google(p,failAck=false){return async(url)=>String(url).includes('oauth2')?Response.json({access_token:'fixture'}):String(url).includes('productsv2')?Response.json(p):new Response(null,{status:failAck?503:204})}
async function verify(env,a,p,token='fixture-token',fail=false){const response=await skylineBilling(request('verify',{productId:p.productLineItem[0].productId,purchaseToken:token},a.sessionToken),env,google(p,fail));return {response,data:await response.json()}}
test('server-created credentials hashed, recovery rotates and invalidates old session',async()=>{const {env,sql}=setup(),a=await account(env);assert.match(a.sessionToken,/^[a-f0-9]{64}$/);assert.notEqual(sql.prepare('SELECT session_hash FROM skyline_members').get().session_hash,a.sessionToken);const r=await skylineBilling(request('recover',{memberId:a.memberId,recoveryToken:a.recoveryToken}),env);assert.equal(r.status,200);assert.equal((await skylineBilling(request('entitlements',undefined,a.sessionToken),env)).status,401);assert.equal((await skylineBilling(request('recover',{memberId:a.memberId,recoveryToken:a.recoveryToken}),env)).status,401)});
test('missing auth and disabled server cannot grant',async()=>{const {env}=setup(),a=await account(env);assert.equal((await skylineBilling(request('verify',{}),env)).status,401);env.SKYLINE_PAYMENTS_ENABLED=undefined;assert.equal((await verify(env,a,purchase(a.memberId))).response.status,503)});
test('pending and cancelled purchases grant nothing',async()=>{for(const state of ['PENDING','CANCELLED']){const {env}=setup(),a=await account(env),p=purchase(a.memberId);p.purchaseStateContext.purchaseState=state;const r=await verify(env,a,p);assert.equal(r.data.wallet?.coins??0,0);assert.equal(r.response.status,state==='PENDING'?200:409)}});
test('wrong account, non-test, refunded quantity and product mismatch rejected',async()=>{for(const mutation of [p=>p.obfuscatedExternalAccountId='other',p=>delete p.testPurchaseContext,p=>p.productLineItem[0].productOfferDetails.refundableQuantity=0,p=>p.productLineItem.push(p.productLineItem[0])]){const {env}=setup(),a=await account(env),p=purchase(a.memberId);mutation(p);assert.notEqual((await verify(env,a,p)).response.status,200)}});
test('replay and concurrent verification credit exactly once',async()=>{const {env,sql}=setup(),a=await account(env),p=purchase(a.memberId);await Promise.all([verify(env,a,p),verify(env,a,p),verify(env,a,p)]);assert.equal(sql.prepare('SELECT coins FROM skyline_wallets').get().coins,1500);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_purchases_v2').get().n,1);const b=await account(env);assert.equal((await verify(env,b,p)).response.status,409)});
test('failed settlement is retryable without duplicate grant',async()=>{const {env}=setup(),a=await account(env),p=purchase(a.memberId);const first=await verify(env,a,p,'fixture-token',true);assert.equal(first.data.settlement,'retry');assert.equal(first.data.wallet.coins,1500);const second=await verify(env,a,p);assert.equal(second.data.settlement,'complete');assert.equal(second.data.wallet.coins,1500)});
test('already consumed unknown token is not granted',async()=>{const {env}=setup(),a=await account(env),p=purchase(a.memberId);p.productLineItem[0].productOfferDetails.consumptionState='CONSUMPTION_STATE_CONSUMED';assert.equal((await verify(env,a,p)).response.status,409)});
test('founder bundle once, durable gadgets spend with replay and overspend protection',async()=>{const {env}=setup(),a=await account(env),p=purchase(a.memberId,'skyline_founder_bundle');let r=await verify(env,a,p);assert.deepEqual(r.data.entitlements,['founder']);assert.deepEqual(r.data.wallet,{coins:1500,net:3,smoke:3});assert.equal((await verify(env,a,p,'different-token')).response.status,409);for(let i=0;i<3;i++){const id='spend-request-000'+i;const res=await skylineBilling(request('spend',{item:'net',requestId:id},a.sessionToken),env);assert.equal(res.status,200);assert.equal((await skylineBilling(request('spend',{item:'net',requestId:id},a.sessionToken),env)).status,200)}assert.equal((await skylineBilling(request('spend',{item:'net',requestId:'spend-request-9999'},a.sessionToken),env)).status,409)});
test('public account input bounded and provisioning rate limited',async()=>{const {env}=setup();const huge=await skylineBilling(request('account',{x:'a'.repeat(8193)}),env);assert.equal(huge.status,413);for(let i=0;i<60;i++)assert.equal((await skylineBilling(request('account',{}),env)).status,200);assert.equal((await skylineBilling(request('account',{}),env)).status,429)});
test('concurrent paid gadget spend cannot overdraw or reuse id across items',async()=>{const {env,sql}=setup(),a=await account(env);await verify(env,a,purchase(a.memberId,'skyline_gadget_pack'));const answers=await Promise.all(Array.from({length:5},(_,i)=>skylineBilling(request('spend',{item:'net',requestId:'concurrent-spend-00'+i},a.sessionToken),env)));assert.equal(answers.filter(r=>r.status===200).length,3);assert.equal(sql.prepare('SELECT net FROM skyline_wallets').get().net,0);const id='concurrent-spend-000';assert.equal((await skylineBilling(request('spend',{item:'smoke',requestId:id},a.sessionToken),env)).status,409)});
test('paid coins buy fixed catalogue gadgets once and return authoritative balances',async()=>{const {env}=setup(),a=await account(env);await verify(env,a,purchase(a.memberId));const body={item:'net',requestId:'coin-buy-request-0001'};let res=await skylineBilling(request('buy',body,a.sessionToken),env);assert.equal(res.status,200);assert.deepEqual((await res.json()).wallet,{coins:1300,net:1,smoke:0});res=await skylineBilling(request('buy',body,a.sessionToken),env);assert.deepEqual((await res.json()).wallet,{coins:1300,net:1,smoke:0});res=await skylineBilling(request('buy',{item:'smoke',requestId:'coin-buy-request-0002'},a.sessionToken),env);assert.deepEqual((await res.json()).wallet,{coins:1150,net:1,smoke:1});assert.equal((await skylineBilling(request('buy',{item:'smoke',requestId:body.requestId},a.sessionToken),env)).status,409)});
test('concurrent paid coin buys cannot overdraw and concurrent identical id grants once',async()=>{const {env,sql}=setup(),a=await account(env);await verify(env,a,purchase(a.memberId));let answers=await Promise.all(Array.from({length:5},()=>skylineBilling(request('buy',{item:'net',requestId:'repeated-coin-buy-0001'},a.sessionToken),env)));assert.equal(answers.filter(r=>r.status===200).length,5);assert.deepEqual(sql.prepare('SELECT coins,net,smoke FROM skyline_wallets').get(),Object.assign(Object.create(null),{coins:1300,net:1,smoke:0}));answers=await Promise.all(Array.from({length:10},(_,i)=>skylineBilling(request('buy',{item:'net',requestId:'unique-coin-buy-000'+i},a.sessionToken),env)));assert.equal(answers.filter(r=>r.status===200).length,6);assert.equal(sql.prepare('SELECT coins FROM skyline_wallets').get().coins,100);assert.equal(sql.prepare('SELECT net FROM skyline_wallets').get().net,7)});
test('client prices quantities unknown items and unauthenticated buys rejected',async()=>{const {env}=setup(),a=await account(env);await verify(env,a,purchase(a.memberId));for(const body of [{item:'net',price:1},{item:'net',quantity:100},{item:'__proto__'},{item:'revive'},{item:'net',cost:0}])assert.equal((await skylineBilling(request('buy',{...body,requestId:'wrong-price-buy-0001'},a.sessionToken),env)).status,400);assert.equal((await skylineBilling(request('buy',{item:'net',requestId:'anonymous-buy-0001'}),env)).status,401);const res=await skylineBilling(request('entitlements',undefined,a.sessionToken),env);assert.deepEqual((await res.json()).wallet,{coins:1500,net:0,smoke:0})});
test('sandbox economy remains closed when server flag disabled',async()=>{const {env}=setup(),a=await account(env);await verify(env,a,purchase(a.memberId,'skyline_founder_bundle'));env.SKYLINE_PAYMENTS_ENABLED=undefined;for(const path of ['buy','spend'])assert.equal((await skylineBilling(request(path,{item:'net',requestId:'closed-economy-0001'},a.sessionToken),env)).status,503);const res=await skylineBilling(request('entitlements',undefined,a.sessionToken),env);assert.deepEqual((await res.json()).wallet,{coins:1500,net:3,smoke:3})});
test('hosting runner can execute every semicolon-split pending migration independently',()=>{const db=new DatabaseSync(':memory:');for(const name of ['0003_skyline_billing.sql','0004_skyline_coin_shop.sql','0005_skyline_refunds.sql','0006_skyline_partial_refunds.sql']){const source=readFileSync('drizzle/'+name,'utf8');assert.doesNotMatch(source,/CREATE TRIGGER/i);for(const statement of source.split(';').map(s=>s.replace(/^--.*$/gm,'').trim()).filter(Boolean))db.prepare(statement).run()}assert.equal(db.prepare("SELECT count(*) n FROM sqlite_master WHERE type='trigger'").get().n,0);assert.ok(db.prepare("SELECT name FROM sqlite_master WHERE name='skyline_coin_buys_v2'").get());db.close()});
test('purchase batch failure rolls back admitted token and all inventory; retry grants once',async()=>{for(const index of [1,2,3]){const state=setup(),a=await account(state.env),p=purchase(a.memberId,'skyline_founder_bundle');state.failBatchAt(index);assert.equal((await verify(state.env,a,p)).response.status,503);assert.equal(state.sql.prepare('SELECT count(*) n FROM skyline_purchases_v2').get().n,0);assert.equal(state.sql.prepare('SELECT coins FROM skyline_wallets').get().coins,0);const result=await verify(state.env,a,p);assert.equal(result.data.wallet.coins,1500);assert.equal(result.data.wallet.net,3);assert.deepEqual(result.data.entitlements,['founder'])}});
test('buy and spend batch failures roll back debit/grant and request admission',async()=>{const state=setup(),a=await account(state.env);await verify(state.env,a,purchase(a.memberId,'skyline_founder_bundle'));for(const path of ['buy','spend'])for(const index of [1,2]){const id='failed-'+path+'-request-000'+index;state.failBatchAt(index);assert.equal((await skylineBilling(request(path,{item:'net',requestId:id},a.sessionToken),state.env)).status,503);const res=await skylineBilling(request('entitlements',undefined,a.sessionToken),state.env);assert.deepEqual((await res.json()).wallet,{coins:1500,net:3,smoke:3})}});
test('local D1 runtime runs split migrations and atomic billing under concurrency',{skip:process.env.SKYLINE_TEST_D1!=='1'},async()=>{const {Miniflare}=await import('miniflare');const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("local")}}',d1Databases:{DB:'skyline-local-test'},compatibilityDate:'2026-05-22'});try{const db=await mf.getD1Database('DB');for(const name of ['0003_skyline_billing.sql','0004_skyline_coin_shop.sql','0005_skyline_refunds.sql','0006_skyline_partial_refunds.sql'])for(const statement of readFileSync('drizzle/'+name,'utf8').split(';').map(s=>s.replace(/^--.*$/gm,'').trim()).filter(Boolean))await db.prepare(statement).run();const env={DB:db,SKYLINE_PAYMENTS_ENABLED:'sandbox',GOOGLE_PLAY_SERVICE_ACCOUNT_EMAIL:'test@example.invalid',GOOGLE_PLAY_SERVICE_ACCOUNT_PRIVATE_KEY:pem},a=await account(env),p=purchase(a.memberId);const verified=await Promise.all(Array.from({length:4},()=>verify(env,a,p)));assert.ok(verified.every(r=>r.response.status===200));let wallet=await db.prepare('SELECT coins,net,smoke FROM skyline_wallets').first();assert.equal(wallet.coins,1500);const buys=await Promise.all(Array.from({length:10},(_,i)=>skylineBilling(request('buy',{item:'net',requestId:'d1-concurrent-buy-'+i},a.sessionToken),env)));assert.equal(buys.filter(r=>r.status===200).length,7);wallet=await db.prepare('SELECT coins,net,smoke FROM skyline_wallets').first();assert.equal(wallet.coins,100);assert.equal(wallet.net,7);const uses=await Promise.all(Array.from({length:10},(_,i)=>skylineBilling(request('spend',{item:'net',requestId:'d1-concurrent-use-'+i},a.sessionToken),env)));assert.equal(uses.filter(r=>r.status===200).length,7);assert.equal((await db.prepare('SELECT net FROM skyline_wallets').first()).net,0);const refunds=await Promise.all(Array.from({length:3},()=>reconcileRefunds(env,['fixture-token'])));assert.equal(refunds.reduce((n,r)=>n+r.data.revoked,0),1);assert.equal((await db.prepare('SELECT coins FROM skyline_wallets').first()).coins,0);assert.equal((await db.prepare('SELECT coins_debt FROM skyline_refunds').first()).coins_debt,1400);assert.equal((await verify(env,a,p)).response.status,409)}finally{await mf.dispose()}});
const ownerKey='fixture-owner-secret-0001';
async function reconcileRefunds(env,tokens,{partial,remaining,at=Date.now()-1000,fail=false,pages=false,invalid=false}={}){env.OWNER_KEY_HASH=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ownerKey))).toString('hex');let calls=0;const send=async url=>{if(String(url).includes('oauth2'))return Response.json({access_token:'fixture'});if(String(url).includes('productsv2')){const token=decodeURIComponent(String(url).split('/').at(-1)),tokenHash=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token))).toString('hex'),p=await env.DB.prepare('SELECT member,product,quantity FROM '+(env.SKYLINE_BILLING_ENVIRONMENT==='production'?'skyline_production_purchases_v2':'skyline_purchases_v2')+' WHERE token_hash=?').bind(tokenHash).first();const proof=purchase(p.member,p.product);if(env.SKYLINE_BILLING_ENVIRONMENT==='production')delete proof.testPurchaseContext;proof.productLineItem[0].productOfferDetails.quantity=p.quantity;proof.productLineItem[0].productOfferDetails.refundableQuantity=remaining??p.quantity-partial;if(invalid)proof.obfuscatedExternalAccountId='wrong';return Response.json(proof)}calls++;if(fail)return new Response(null,{status:503});assert.match(String(url),/includeQuantityBasedPartialRefund=true/);return Response.json({voidedPurchases:tokens.map(token=>({purchaseToken:token,voidedTimeMillis:String(at),...(partial?{voidedQuantity:partial}:{})})),...(pages?{tokenPagination:{nextPageToken:'opaque-next-page'}}:{})})};const response=await skylineBilling(request('reconcile',{},ownerKey),env,send);return {response,data:await response.json(),calls}}
test('refund revoke and replay deduct once; permanent suit revoked and token cannot regrant',async()=>{const {env,sql}=setup(),a=await account(env),p=purchase(a.memberId,'skyline_founder_bundle');await verify(env,a,p);let r=await reconcileRefunds(env,['fixture-token']);assert.equal(r.data.revoked,1);r=await reconcileRefunds(env,['fixture-token']);assert.equal(r.data.revoked,0);assert.equal(sql.prepare('SELECT settlement FROM skyline_purchases_v2').get().settlement,'revoked');const snapshot=await(await skylineBilling(request('entitlements',undefined,a.sessionToken),env)).json();assert.deepEqual(snapshot.entitlements,[]);assert.deepEqual(snapshot.wallet,{coins:0,net:0,smoke:0});assert.equal(snapshot.paymentHold,false);assert.equal((await verify(env,a,p)).response.status,409)});
test('concurrent refund replay clamps spent balances, stores deficit and blocks paid economy',async()=>{const {env,sql}=setup(),a=await account(env);await verify(env,a,purchase(a.memberId,'skyline_founder_bundle'));await skylineBilling(request('buy',{item:'net',requestId:'before-refund-buy-001'},a.sessionToken),env);for(let i=0;i<4;i++)await skylineBilling(request('spend',{item:'net',requestId:'before-refund-use-00'+i},a.sessionToken),env);await Promise.all(Array.from({length:4},()=>reconcileRefunds(env,['fixture-token'])));assert.deepEqual(sql.prepare('SELECT coins,net,smoke FROM skyline_wallets').get(),Object.assign(Object.create(null),{coins:0,net:0,smoke:0}));assert.deepEqual(sql.prepare('SELECT coins_debt,net_debt,smoke_debt FROM skyline_refunds').get(),Object.assign(Object.create(null),{coins_debt:200,net_debt:3,smoke_debt:0}));for(const path of ['buy','spend'])assert.equal((await skylineBilling(request(path,{item:'net',requestId:'held-refund-action01'},a.sessionToken),env)).status,409);assert.equal((await verify(env,a,purchase(a.memberId),'brand-new-token')).response.status,409)});
test('unknown token tombstone blocks delayed stale purchased proof',async()=>{const {env,sql}=setup(),a=await account(env);const result=await reconcileRefunds(env,['future-purchase-token']);assert.equal(result.data.unknown,1);assert.equal((await verify(env,a,purchase(a.memberId),'future-purchase-token')).response.status,409);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_purchases_v2').get().n,0)});
test('partial quantity refund removes only refunded units without an unspent hold',async()=>{const {env}=setup(),a=await account(env),p=purchase(a.memberId);p.productLineItem[0].productOfferDetails.quantity=2;p.productLineItem[0].productOfferDetails.refundableQuantity=2;await verify(env,a,p);const r=await reconcileRefunds(env,['fixture-token'],{partial:1});assert.equal(r.data.partialHeld,0);const state=await(await skylineBilling(request('entitlements',undefined,a.sessionToken),env)).json();assert.equal(state.wallet.coins,1500);assert.equal(state.paymentHold,false)});
test('reconciliation unauthenticated member keys and disabled sandbox fail closed before Google',async()=>{const {env}=setup(),a=await account(env);env.OWNER_KEY_HASH=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ownerKey))).toString('hex');let calls=0;const send=async()=>{calls++;throw Error('must not call Google')};for(const auth of [undefined,a.sessionToken,'incorrect-owner-secret01'])assert.equal((await skylineBilling(request('reconcile',{},auth),env,send)).status,401);env.SKYLINE_PAYMENTS_ENABLED=undefined;assert.equal((await skylineBilling(request('reconcile',{},ownerKey),env,send)).status,503);assert.equal(calls,0)});
test('source error applies no refund; bounded pagination reports incomplete without tokens',async()=>{const {env,sql}=setup(),a=await account(env);await verify(env,a,purchase(a.memberId));assert.equal((await reconcileRefunds(env,['fixture-token'],{fail:true})).response.status,503);assert.equal(sql.prepare('SELECT coins FROM skyline_wallets').get().coins,1500);const r=await reconcileRefunds(env,[],{pages:true});assert.equal(r.calls,3);assert.equal(r.data.complete,false);assert.equal(JSON.stringify(r.data).includes('opaque-next-page'),false)});
test('mid-refund batch failure rolls back tombstone wallet and entitlement; retry works',async()=>{for(const index of [1,3,5,6]){const state=setup(),a=await account(state.env);await verify(state.env,a,purchase(a.memberId,'skyline_founder_bundle'));state.failBatchAt(index);assert.equal((await reconcileRefunds(state.env,['fixture-token'])).response.status,503);assert.equal(state.sql.prepare('SELECT count(*) n FROM skyline_refunds').get().n,0);assert.equal(state.sql.prepare('SELECT coins FROM skyline_wallets').get().coins,1500);assert.equal((await reconcileRefunds(state.env,['fixture-token'])).data.revoked,1)}});
test('refund arriving during delayed Google verification cannot admit stale grant',async()=>{const {env,sql}=setup(),a=await account(env),p=purchase(a.memberId);let ready;const reached=new Promise(resolve=>ready=resolve);let release;const delayed=new Promise(resolve=>release=resolve);const send=async url=>{if(String(url).includes('oauth2'))return Response.json({access_token:'fixture'});if(String(url).includes('productsv2')){ready();await delayed;return Response.json(p)}return new Response(null,{status:204})};const checking=skylineBilling(request('verify',{productId:'skyline_coins_1500',purchaseToken:'delayed-refund-token'},a.sessionToken),env,send);await reached;await reconcileRefunds(env,['delayed-refund-token']);release();assert.equal((await checking).status,409);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_purchases_v2').get().n,0);assert.equal(sql.prepare('SELECT coins FROM skyline_wallets').get().coins,0)});
test('fresh suit repurchase after full unspent refund allowed; old refund replay does not revoke new suit',async()=>{const {env}=setup(),a=await account(env),p=purchase(a.memberId,'skyline_neon_suit');await verify(env,a,p);await reconcileRefunds(env,['fixture-token']);assert.equal((await verify(env,a,p,'fresh-neon-token')).response.status,200);await reconcileRefunds(env,['fixture-token']);const snap=await(await skylineBilling(request('entitlements',undefined,a.sessionToken),env)).json();assert.deepEqual(snap.entitlements,['neon']);assert.equal(snap.paymentHold,false)});

function quantityPurchase(member,quantity,product='skyline_coins_1500'){const p=purchase(member,product);Object.assign(p.productLineItem[0].productOfferDetails,{quantity,refundableQuantity:quantity});return p}
test('incremental partial refunds use cumulative authority; duplicate event and stale proof cannot double debit; final full drains remainder',async()=>{const {env,sql}=setup(),a=await account(env);await verify(env,a,quantityPurchase(a.memberId,10));const at=Date.now()-1000;await Promise.all(Array.from({length:4},()=>reconcileRefunds(env,['fixture-token'],{partial:2,remaining:8,at})));assert.equal(sql.prepare('SELECT coins FROM skyline_wallets').get().coins,12000);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_refund_events').get().n,1);await reconcileRefunds(env,['fixture-token'],{partial:3,remaining:5,at:at+1});assert.equal(sql.prepare('SELECT coins FROM skyline_wallets').get().coins,7500);await reconcileRefunds(env,['fixture-token'],{partial:2,remaining:8,at});assert.equal(sql.prepare('SELECT coins FROM skyline_wallets').get().coins,7500);assert.equal(sql.prepare('SELECT settlement FROM skyline_purchases_v2').get().settlement,'partially_refunded');await reconcileRefunds(env,['fixture-token']);assert.equal(sql.prepare('SELECT coins FROM skyline_wallets').get().coins,0);assert.equal(sql.prepare('SELECT refunded_quantity FROM skyline_refunds').get().refunded_quantity,10);assert.equal(sql.prepare('SELECT settlement FROM skyline_purchases_v2').get().settlement,'revoked');await reconcileRefunds(env,['fixture-token'],{partial:2,remaining:8,at});assert.equal(sql.prepare('SELECT coins_debt FROM skyline_refunds').get().coins_debt,0)});
test('same-time same-quantity events reconcile authoritative remaining rather than event fingerprint sums',async()=>{const {env,sql}=setup(),a=await account(env);await verify(env,a,quantityPurchase(a.memberId,5));const at=Date.now()-1000;await reconcileRefunds(env,['fixture-token'],{partial:1,remaining:4,at});await reconcileRefunds(env,['fixture-token'],{partial:1,remaining:3,at});assert.equal(sql.prepare('SELECT coins FROM skyline_wallets').get().coins,4500);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_refund_events').get().n,1)});
test('spent partial refund records only missing refunded units and holds paid balance once',async()=>{const {env,sql}=setup(),a=await account(env);await verify(env,a,quantityPurchase(a.memberId,2,'skyline_gadget_pack'));for(let i=0;i<5;i++)await skylineBilling(request('spend',{item:'net',requestId:'partial-spent-use-0'+i},a.sessionToken),env);const at=Date.now()-1000;await Promise.all(Array.from({length:3},()=>reconcileRefunds(env,['fixture-token'],{partial:1,remaining:1,at})));assert.equal(sql.prepare('SELECT net FROM skyline_wallets').get().net,0);assert.equal(sql.prepare('SELECT smoke FROM skyline_wallets').get().smoke,3);assert.equal(sql.prepare('SELECT net_debt FROM skyline_refunds').get().net_debt,2);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_payment_holds').get().n,1)});
test('partial quantity authority mismatch fails without modifying wallet or refund ledger',async()=>{const {env,sql}=setup(),a=await account(env);await verify(env,a,quantityPurchase(a.memberId,2));for(const opts of [{partial:1,remaining:2},{partial:1,remaining:3},{partial:1,remaining:1,invalid:true}])assert.equal((await reconcileRefunds(env,['fixture-token'],opts)).response.status,503);assert.equal(sql.prepare('SELECT coins FROM skyline_wallets').get().coins,3000);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_refunds').get().n,0)});
test('returned voided time outside query window remains valid; unknown partial still prevents late grant',async()=>{const {env,sql}=setup(),a=await account(env);const r=await reconcileRefunds(env,['future-partial-token'],{partial:1,at:Date.now()-40*86400000});assert.equal(r.response.status,200);assert.equal((await verify(env,a,quantityPurchase(a.memberId,2),'future-partial-token')).response.status,409);assert.equal(sql.prepare('SELECT coins FROM skyline_wallets').get().coins,0)});
test('migration preserves legacy conservative revoke watermark without refunding or debiting again',async()=>{const {env,sql}=setup(),a=await account(env);await verify(env,a,quantityPurchase(a.memberId,2));await reconcileRefunds(env,['fixture-token']);sql.exec('DROP TABLE skyline_refund_events; ALTER TABLE skyline_refunds DROP COLUMN desired_quantity; ALTER TABLE skyline_refunds DROP COLUMN refunded_quantity;');sql.exec(readFileSync('drizzle/0006_skyline_partial_refunds.sql','utf8'));sql.exec(readFileSync('drizzle/0008_skyline_deletion_requests.sql','utf8'));sql.exec(readFileSync('drizzle/0009_skyline_deletion_completion.sql','utf8'));sql.exec(readFileSync('drizzle/0010_skyline_deletion_health.sql','utf8'));assert.equal(sql.prepare('SELECT refunded_quantity FROM skyline_refunds').get().refunded_quantity,2);await reconcileRefunds(env,['fixture-token'],{partial:1,remaining:1});assert.equal(sql.prepare('SELECT coins FROM skyline_wallets').get().coins,0);assert.equal(sql.prepare('SELECT coins_debt FROM skyline_refunds').get().coins_debt,0)});
test('local D1 concurrent stale partial snapshots and full refund debit bounded original quantity',{skip:process.env.SKYLINE_TEST_D1!=='1'},async()=>{const {Miniflare}=await import('miniflare');const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("local")}}',d1Databases:{DB:'skyline-partial-test'},compatibilityDate:'2026-05-22'});try{const db=await mf.getD1Database('DB');for(const name of ['0003_skyline_billing.sql','0004_skyline_coin_shop.sql','0005_skyline_refunds.sql','0006_skyline_partial_refunds.sql'])for(const statement of readFileSync('drizzle/'+name,'utf8').split(';').map(s=>s.replace(/^--.*$/gm,'').trim()).filter(Boolean))await db.prepare(statement).run();const env={DB:db,SKYLINE_PAYMENTS_ENABLED:'sandbox',GOOGLE_PLAY_SERVICE_ACCOUNT_EMAIL:'test@example.invalid',GOOGLE_PLAY_SERVICE_ACCOUNT_PRIVATE_KEY:pem},a=await account(env);await verify(env,a,quantityPurchase(a.memberId,10));const at=Date.now()-1000;const results=await Promise.all([reconcileRefunds(env,['fixture-token'],{partial:2,remaining:8,at}),reconcileRefunds(env,['fixture-token'],{partial:3,remaining:5,at:at+1}),reconcileRefunds(env,['fixture-token'],{partial:2,remaining:8,at})]);assert.ok(results.every(r=>r.response.status===200));assert.equal((await db.prepare('SELECT coins FROM skyline_wallets').first()).coins,7500);await Promise.all([reconcileRefunds(env,['fixture-token']),reconcileRefunds(env,['fixture-token'],{partial:3,remaining:5,at:at+1})]);assert.equal((await db.prepare('SELECT coins FROM skyline_wallets').first()).coins,0);const record=await db.prepare('SELECT refunded_quantity,coins_debt FROM skyline_refunds').first();assert.equal(record.refunded_quantity,10);assert.equal(record.coins_debt,0);assert.equal((await db.prepare('SELECT count(*) n FROM skyline_payment_holds').first()).n,0)}finally{await mf.dispose()}});
test('partial refund while native settlement awaits cannot overwrite refund settlement watermark',async()=>{const {env,sql}=setup(),a=await account(env),p=quantityPurchase(a.memberId,2);let entered,release;const reached=new Promise(resolve=>entered=resolve),pause=new Promise(resolve=>release=resolve);const send=async url=>{if(String(url).includes('oauth2'))return Response.json({access_token:'fixture'});if(String(url).includes('productsv2'))return Response.json(p);entered();await pause;return new Response(null,{status:204})};const checking=skylineBilling(request('verify',{productId:'skyline_coins_1500',purchaseToken:'fixture-token'},a.sessionToken),env,send);await reached;await reconcileRefunds(env,['fixture-token'],{partial:1,remaining:1});release();assert.equal((await checking).status,409);assert.equal(sql.prepare('SELECT settlement FROM skyline_purchases_v2').get().settlement,'partially_refunded');assert.equal(sql.prepare('SELECT coins FROM skyline_wallets').get().coins,1500)});
test('purchase admitted between unknown refund lookup and transaction cannot escape revocation',async()=>{for(const partial of [undefined,1]){const {env,sql}=setup(),a=await account(env);let entered,release;const reached=new Promise(resolve=>entered=resolve),pause=new Promise(resolve=>release=resolve),basePrepare=env.DB.prepare.bind(env.DB);let paused=false;env.DB.prepare=q=>{const statement=basePrepare(q);if(q==='SELECT member,product,quantity FROM skyline_purchases_v2 WHERE token_hash=?'&&!paused){const original=statement.first.bind(statement);statement.first=async()=>{const result=await original();paused=true;entered();await pause;return result}}return statement};const refund=reconcileRefunds(env,['fixture-token'],{partial});await reached;assert.equal((await verify(env,a,quantityPurchase(a.memberId,2))).response.status,200);release();assert.equal((await refund).response.status,200);assert.equal(sql.prepare('SELECT coins FROM skyline_wallets').get().coins,0);assert.equal(sql.prepare('SELECT settlement FROM skyline_purchases_v2').get().settlement,'revoked');assert.equal(sql.prepare('SELECT count(*) n FROM skyline_payment_holds').get().n,partial?1:0)}});

test('deletion requests require valid session and never provision an account',async()=>{const {env,sql}=setup();assert.equal((await skylineBilling(request('deletion-request',{}),env)).status,401);assert.equal((await skylineBilling(request('deletion-request',{},'a'.repeat(64)),env)).status,401);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_members').get().n,0);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_deletion_requests').get().n,0);});
test('deletion request retries preserve one durable reference and all paid inventory',async()=>{const {env,sql}=setup(),a=await account(env);await verify(env,a,purchase(a.memberId,'skyline_founder_bundle'));const before=await(await skylineBilling(request('entitlements',undefined,a.sessionToken),env)).json();const rows=await Promise.all(Array.from({length:3},async()=>{const r=await skylineBilling(request('deletion-request',{},a.sessionToken),env);assert.equal(r.status,202);return r.json();}));assert.equal(new Set(rows.map(r=>r.requestId)).size,1);assert.equal(new Set(rows.map(r=>r.requestedAt)).size,1);assert.equal(rows[0].status,'pending');assert.equal(sql.prepare('SELECT count(*) n FROM skyline_deletion_requests').get().n,1);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_purchases_v2').get().n,1);assert.deepEqual(await(await skylineBilling(request('entitlements',undefined,a.sessionToken),env)).json(),before);});
test('deletion status is scoped to the authenticated account and rejects target IDs',async()=>{const {env}=setup(),a=await account(env),b=await account(env);assert.equal((await skylineBilling(request('deletion-request',{memberId:b.memberId},a.sessionToken),env)).status,400);await skylineBilling(request('deletion-request',{},a.sessionToken),env);assert.equal((await(await skylineBilling(request('deletion-request',undefined,b.sessionToken),env)).json()).status,'not_requested');const recovered=await(await skylineBilling(request('recover',{memberId:a.memberId,recoveryToken:a.recoveryToken}),env)).json();assert.equal((await skylineBilling(request('deletion-request',{},a.sessionToken),env)).status,401);assert.equal((await(await skylineBilling(request('deletion-request',undefined,recovered.sessionToken),env)).json()).status,'pending');});

test('owner deletion queue is read-only and rejects member credentials',async()=>{const {env,sql}=setup(),a=await account(env);await skylineBilling(request('deletion-request',{},a.sessionToken),env);env.OWNER_KEY_HASH=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ownerKey))).toString('hex');for(const auth of [undefined,a.sessionToken,'incorrect-owner-secret01'])assert.equal((await skylineBilling(request('deletion-requests',undefined,auth),env)).status,401);const response=await skylineBilling(request('deletion-requests',undefined,ownerKey),env);assert.equal(response.status,200);const data=await response.json();assert.equal(data.requests.length,1);assert.equal(data.requests[0].member,a.memberId);assert.equal(data.next,null);assert.equal(JSON.stringify(data).includes(a.sessionToken),false);assert.equal(JSON.stringify(data).includes(a.recoveryToken),false);assert.equal(sql.prepare('SELECT status FROM skyline_deletion_requests').get().status,'pending');});
test('owner deletion queue pagination is bounded and rejects malformed cursors',async()=>{const {env,sql}=setup(),a=await account(env);env.OWNER_KEY_HASH=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ownerKey))).toString('hex');for(let i=0;i<102;i++){const member='fixture-member-'+i,id='00000000-0000-4000-8000-'+String(i).padStart(12,'0');sql.prepare('INSERT INTO skyline_members VALUES(?,?,?,?)').run(member,'session-'+i,'recovery-'+i,1);sql.prepare('INSERT INTO skyline_deletion_requests VALUES(?,?,?,?)').run(member,id,1,'pending');}const first=await(await skylineBilling(request('deletion-requests',undefined,ownerKey),env)).json();assert.equal(first.requests.length,100);assert.ok(first.next);const second=await(await skylineBilling(request('deletion-requests?after='+first.next,undefined,ownerKey),env)).json();assert.equal(second.requests.length,2);assert.equal(second.next,null);for(const suffix of ['?after=bad','?member='+a.memberId,'?after=&after='])assert.equal((await skylineBilling(request('deletion-requests'+suffix,undefined,ownerKey),env)).status,400);});
test('failed deletion persistence never reports accepted',async()=>{const {env,sql}=setup(),a=await account(env);sql.exec('DROP TABLE skyline_deletion_requests');const r=await skylineBilling(request('deletion-request',{},a.sessionToken),env);assert.notEqual(r.status,202);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_members').get().n,1);});


test('web deletion recovery validates ownership without provisioning or rotating credentials',async()=>{
 const {env,sql}=setup(),a=await account(env),b=await account(env);
 const identity=sql.prepare('SELECT * FROM skyline_members WHERE id=?').get(a.memberId);
 for(const body of [{},{memberId:a.memberId,recoveryToken:b.recoveryToken},{memberId:a.memberId,recoveryToken:a.recoveryToken,target:b.memberId}])assert.equal((await skylineBilling(request('deletion-request/recovery',body),env)).status,401);
 assert.equal(sql.prepare('SELECT count(*) n FROM skyline_deletion_requests').get().n,0);
 const body={memberId:a.memberId,recoveryToken:a.recoveryToken};
 const first=await skylineBilling(request('deletion-request/recovery',body),env);assert.equal(first.status,202);const result=await first.json();assert.equal(result.status,'pending');
 assert.deepEqual(await(await skylineBilling(request('deletion-request/recovery',body),env)).json(),result);
 assert.deepEqual(sql.prepare('SELECT * FROM skyline_members WHERE id=?').get(a.memberId),identity);
 assert.equal(sql.prepare('SELECT count(*) n FROM skyline_members').get().n,2);
 assert.equal(JSON.stringify(result).includes(a.recoveryToken),false);assert.equal(JSON.stringify(result).includes(a.sessionToken),false);
 assert.equal((await skylineBilling(request('entitlements',undefined,a.sessionToken),env)).status,200);
 assert.equal((await(await skylineBilling(request('deletion-request',undefined,b.sessionToken),env)).json()).status,'not_requested');
});
test('web deletion recovery rejects foreign origins and throttles invalid attempts',async()=>{
 const {env,sql}=setup(),a=await account(env),body={memberId:a.memberId,recoveryToken:a.recoveryToken};
 const foreign=request('deletion-request/recovery',body);foreign.headers.set('Origin','https://other.invalid');assert.equal((await skylineBilling(foreign,env)).status,403);
 const same=request('deletion-request/recovery',body);same.headers.set('Origin','https://example.invalid');assert.equal((await skylineBilling(same,env)).status,202);
 for(let i=0;i<19;i++)assert.equal((await skylineBilling(request('deletion-request/recovery',{}),env)).status,401);
 assert.equal((await skylineBilling(request('deletion-request/recovery',body),env)).status,429);
 assert.equal(sql.prepare('SELECT count(*) n FROM skyline_deletion_requests').get().n,1);
});
test('web deletion request cannot confirm when persistence fails',async()=>{
 const {env,sql}=setup(),a=await account(env);sql.exec('DROP TABLE skyline_deletion_requests');
 assert.notEqual((await skylineBilling(request('deletion-request/recovery',{memberId:a.memberId,recoveryToken:a.recoveryToken}),env)).status,202);
 assert.equal((await skylineBilling(request('entitlements',undefined,a.sessionToken),env)).status,200);
});

async function deletionOwner(env){env.OWNER_KEY_HASH=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(ownerKey))).toString('hex');env.SKYLINE_DELETION_PROCESSING_ENABLED='true';}
async function queuedDeletion(env,a){return (await(await skylineBilling(request('deletion-request',{},a.sessionToken),env)).json()).requestId;}
function completeDeletion(env,id,key=ownerKey,extra={}){return skylineBilling(request('deletion-requests/complete',{requestId:id,confirmation:'delete-account',...extra},key),env);}
test('deletion completion requires owner, explicit confirmation, pending request and processing gate',async()=>{
 const {env,sql}=setup(),a=await account(env);await deletionOwner(env);const id=await queuedDeletion(env,a);
 for(const key of [null,a.sessionToken,'incorrect-owner-secret01'])assert.equal((await completeDeletion(env,id,key)).status,401);
 env.SKYLINE_DELETION_PROCESSING_ENABLED=undefined;assert.equal((await completeDeletion(env,id)).status,503);env.SKYLINE_DELETION_PROCESSING_ENABLED='true';
 for(const extra of [{confirmation:'yes'},{memberId:a.memberId},{requestId:'bad'}])assert.equal((await completeDeletion(env,id,ownerKey,extra)).status,400);
 assert.equal((await completeDeletion(env,crypto.randomUUID())).status,404);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_members').get().n,1);
});
test('deletion completion removes all linked billing data and invalidates credentials; retries preserve receipt',async()=>{
 const {env,sql}=setup(),a=await account(env),b=await account(env);await deletionOwner(env);
 await verify(env,a,purchase(a.memberId,'skyline_founder_bundle'),'deleted-player-token');await verify(env,b,purchase(b.memberId),'other-player-token');
 await skylineBilling(request('buy',{item:'smoke',requestId:'delete-test-buy-0001'},a.sessionToken),env);
 await skylineBilling(request('spend',{item:'net',requestId:'delete-test-use-0001'},a.sessionToken),env);
 const token=sql.prepare('SELECT token_hash FROM skyline_purchases_v2 WHERE member=?').get(a.memberId).token_hash;
 sql.prepare('INSERT INTO skyline_refunds(token_hash,voided_at) VALUES(?,?)').run(token,1);
 sql.prepare('INSERT INTO skyline_refund_events VALUES(?,?,?,?)').run('event-fixture',token,1,null);
 sql.prepare('INSERT INTO skyline_payment_holds VALUES(?,?,?)').run(a.memberId,'fixture',1);
 const bBefore=await(await skylineBilling(request('entitlements',undefined,b.sessionToken),env)).json();const id=await queuedDeletion(env,a);
 const first=await completeDeletion(env,id);assert.equal(first.status,200);const receipt=await first.json();assert.equal(receipt.status,'completed');
 assert.deepEqual(await(await completeDeletion(env,id)).json(),receipt);
 for(const table of ['skyline_wallets','skyline_purchases_v2','skyline_entitlements','skyline_spends_v2','skyline_coin_buys_v2','skyline_payment_holds','skyline_deletion_requests'])assert.equal(sql.prepare('SELECT count(*) n FROM '+table+' WHERE member=?').get(a.memberId).n,0,table);
 assert.equal(sql.prepare('SELECT count(*) n FROM skyline_members WHERE id=?').get(a.memberId).n,0);
 for(const table of ['skyline_refunds','skyline_refund_events'])assert.equal(sql.prepare('SELECT count(*) n FROM '+table+' WHERE token_hash=?').get(token).n,0);
 assert.equal((await skylineBilling(request('entitlements',undefined,a.sessionToken),env)).status,401);
 assert.equal((await skylineBilling(request('recover',{memberId:a.memberId,recoveryToken:a.recoveryToken}),env)).status,401);
 assert.equal((await skylineBilling(request('deletion-request/recovery',{memberId:a.memberId,recoveryToken:a.recoveryToken}),env)).status,401);
 assert.deepEqual(await(await skylineBilling(request('entitlements',undefined,b.sessionToken),env)).json(),bBefore);
 const saved=sql.prepare('SELECT * FROM skyline_deletion_completions').get();assert.deepEqual(Object.keys(saved),['request_hash','completed']);assert.notEqual(saved.request_hash,id);assert.equal(JSON.stringify(saved).includes(a.memberId),false);
 assert.equal((await(await skylineBilling(request('deletion-requests',undefined,ownerKey),env)).json()).requests.length,0);
});
test('deletion completion rolls back every stage on storage failure',async()=>{
 for(const index of Array.from({length:11},(_,i)=>i)){const state=setup(),{env,sql}=state,a=await account(env);await deletionOwner(env);await verify(env,a,purchase(a.memberId,'skyline_founder_bundle'));const id=await queuedDeletion(env,a),before=await(await skylineBilling(request('entitlements',undefined,a.sessionToken),env)).json();state.failBatchAt(index);
 assert.equal((await completeDeletion(env,id)).status,503);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_deletion_completions').get().n,0);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_members').get().n,1);assert.deepEqual(await(await skylineBilling(request('entitlements',undefined,a.sessionToken),env)).json(),before);assert.equal((await completeDeletion(env,id)).status,200);
 }
});
test('deletion during delayed Google verification cannot recreate purchase records or report a grant',async()=>{
 const {env,sql}=setup(),a=await account(env);await deletionOwner(env);const id=await queuedDeletion(env,a);let reached,release;const waiting=new Promise(resolve=>reached=resolve),paused=new Promise(resolve=>release=resolve);
 const send=async(url)=>{if(String(url).includes('oauth2'))return Response.json({access_token:'fixture'});if(String(url).includes('productsv2')){reached();await paused;return Response.json(purchase(a.memberId,'skyline_founder_bundle'));}return new Response(null,{status:204});};
 const inflight=skylineBilling(request('verify',{productId:'skyline_founder_bundle',purchaseToken:'delayed-delete-token'},a.sessionToken),env,send);await waiting;assert.equal((await completeDeletion(env,id)).status,200);release();assert.notEqual((await inflight).status,200);
 for(const table of ['skyline_members','skyline_wallets','skyline_purchases_v2','skyline_entitlements'])assert.equal(sql.prepare('SELECT count(*) n FROM '+table).get().n,0,table);
});
test('local D1 completes concurrent deletion retries atomically and preserves another member',{skip:process.env.SKYLINE_TEST_D1!=='1'},async()=>{
 const {Miniflare}=await import('miniflare');const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("local")}}',d1Databases:{DB:'skyline-local-delete-test'},compatibilityDate:'2026-05-22'});
 try{
  const db=await mf.getD1Database('DB');
  for(const name of ['0003_skyline_billing.sql','0004_skyline_coin_shop.sql','0005_skyline_refunds.sql','0006_skyline_partial_refunds.sql','0008_skyline_deletion_requests.sql','0009_skyline_deletion_completion.sql','0010_skyline_deletion_health.sql'])for(const statement of readFileSync('drizzle/'+name,'utf8').split(';').map(s=>s.replace(/^--.*$/gm,'').trim()).filter(Boolean))await db.prepare(statement).run();
  const env={DB:db,SKYLINE_PAYMENTS_ENABLED:'sandbox',GOOGLE_PLAY_SERVICE_ACCOUNT_EMAIL:'test@example.invalid',GOOGLE_PLAY_SERVICE_ACCOUNT_PRIVATE_KEY:pem};await deletionOwner(env);const a=await account(env),b=await account(env);await verify(env,a,purchase(a.memberId,'skyline_founder_bundle'));const id=await queuedDeletion(env,a);
  const results=await Promise.all(Array.from({length:3},async()=>{const r=await completeDeletion(env,id);assert.equal(r.status,200);return r.json();}));assert.equal(new Set(results.map(r=>r.completedAt)).size,1);
  assert.equal((await db.prepare('SELECT count(*) n FROM skyline_members').first()).n,1);assert.equal((await db.prepare('SELECT count(*) n FROM skyline_purchases_v2').first()).n,0);assert.equal((await skylineBilling(request('entitlements',undefined,a.sessionToken),env)).status,401);assert.equal((await skylineBilling(request('entitlements',undefined,b.sessionToken),env)).status,200);
  const expiry=Date.now();await db.prepare('UPDATE skyline_deletion_completions SET completed=?').bind(expiry-30*86400000).run();
  const cleaned=await skylineDeletionMaintenance(env,expiry);assert.equal(cleaned.purgedReceipts,1);assert.equal((await db.prepare('SELECT count(*) n FROM skyline_deletion_completions').first()).n,0);assert.equal((await completeDeletion(env,id)).status,404);
 }finally{await mf.dispose();}
});

test('receipt expiry rejects lookup at 30 days and maintenance purges only expired rows',async t=>{
 const {env,sql}=setup();await deletionOwner(env);const a=await account(env),id=await queuedDeletion(env,a);assert.equal((await completeDeletion(env,id)).status,200);
 const base=Date.now();sql.prepare('UPDATE skyline_deletion_completions SET completed=?').run(base-30*86400000);
 sql.prepare('INSERT INTO skyline_deletion_completions VALUES(?,?)').run('unexpired-fixture',base-30*86400000+1);
 t.mock.method(Date,'now',()=>base);
 assert.equal((await completeDeletion(env,id)).status,404);
 const result=await skylineDeletionMaintenance(env,base);assert.equal(result.purgedReceipts,1);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_deletion_completions').get().n,1);assert.equal((await skylineDeletionMaintenance(env,base)).purgedReceipts,0);
});
test('maintenance enforces owner authorization and cannot take a caller-supplied time',async()=>{
 const {env,sql}=setup(),a=await account(env);await deletionOwner(env);
 sql.prepare('INSERT INTO skyline_deletion_completions VALUES(?,?)').run('expired-fixture',1);
 for(const key of [null,a.sessionToken,'incorrect-owner-secret01'])assert.equal((await skylineBilling(request('deletion-maintenance',{},key),env)).status,401);
 assert.equal((await skylineBilling(request('deletion-maintenance',{now:Date.now()+365*86400000},ownerKey),env)).status,400);
 env.SKYLINE_DELETION_PROCESSING_ENABLED=undefined;assert.equal((await skylineBilling(request('deletion-maintenance',{},ownerKey),env)).status,503);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_deletion_completions').get().n,1);
 env.SKYLINE_DELETION_PROCESSING_ENABLED='true';const r=await skylineBilling(request('deletion-maintenance',{},ownerKey),env);assert.equal(r.status,200);assert.equal((await r.json()).purgedReceipts,1);
});
test('owner queue exposes seven-day deadline and maintenance reports exact overdue boundary',async()=>{
 const {env,sql}=setup(),a=await account(env),b=await account(env);await deletionOwner(env);await queuedDeletion(env,a);await queuedDeletion(env,b);const now=Date.now();
 sql.prepare('UPDATE skyline_deletion_requests SET requested=? WHERE member=?').run(now-7*86400000,a.memberId);sql.prepare('UPDATE skyline_deletion_requests SET requested=? WHERE member=?').run(now-7*86400000+1,b.memberId);
 const queue=await(await skylineBilling(request('deletion-requests',undefined,ownerKey),env)).json();assert.equal(queue.requests.find(r=>r.member===a.memberId).deadlineAt,now);
 const report=await skylineDeletionMaintenance(env,now);assert.equal(report.pending,2);assert.equal(report.overdue,1);assert.equal(report.nextDeadline,now);
 assert.equal(sql.prepare('SELECT count(*) n FROM skyline_members').get().n,2,'maintenance never completes deletion without an owner completion action');
 assert.equal(JSON.stringify(report).includes(a.memberId),false);
});

test('owner health is read-only, rejects visitor access, and distinguishes manual cleanup from a scheduled invocation',async()=>{
 const {env,sql}=setup(),a=await account(env);await deletionOwner(env);await queuedDeletion(env,a);
 const counts=()=>({members:sql.prepare('SELECT count(*) n FROM skyline_members').get().n,receipts:sql.prepare('SELECT count(*) n FROM skyline_deletion_completions').get().n});
 const before=counts();
 for(const key of [null,a.sessionToken,'incorrect-owner-secret01'])assert.equal((await skylineBilling(request('deletion-health',undefined,key),env)).status,401);
 env.SKYLINE_DELETION_PROCESSING_ENABLED=undefined;
 const fresh=await(await skylineBilling(request('deletion-health',undefined,ownerKey),env)).json();
 assert.equal(fresh.processingEnabled,false);assert.equal(fresh.pending,1);assert.equal(fresh.lastMaintenanceAt,null);assert.equal(fresh.scheduledRecently,false);
 assert.deepEqual(counts(),before);assert.equal(JSON.stringify(fresh).includes(a.memberId),false);
 assert.equal((await skylineBilling(request('deletion-health?now=1',undefined,ownerKey),env)).status,400);
 env.SKYLINE_DELETION_PROCESSING_ENABLED='true';const now=Date.now();
 await skylineDeletionMaintenance(env,now);
 const manual=await(await skylineBilling(request('deletion-health',undefined,ownerKey),env)).json();assert.equal(manual.lastMaintenanceAt,now);assert.equal(manual.lastScheduledAt,null);assert.equal(manual.scheduledRecently,false);
 await skylineDeletionMaintenance(env,now,'scheduled');
 const scheduled=await(await skylineBilling(request('deletion-health',undefined,ownerKey),env)).json();assert.equal(scheduled.lastScheduledAt,now);assert.equal(scheduled.scheduledRecently,true);
 await skylineDeletionMaintenance(env,now+1);assert.equal(sql.prepare('SELECT last_scheduled FROM skyline_deletion_health').get().last_scheduled,now,'manual runs cannot refresh the scheduled heartbeat');
 sql.prepare('UPDATE skyline_deletion_health SET last_scheduled=?').run(Date.now()-2*3600000);
 assert.equal((await(await skylineBilling(request('deletion-health',undefined,ownerKey),env)).json()).scheduledRecently,false);
});
test('failed maintenance cannot purge a receipt or write a success heartbeat',async()=>{
 for(const stage of [0,1]){
  const {env,sql,failBatchAt}=setup();await deletionOwner(env);sql.prepare('INSERT INTO skyline_deletion_completions VALUES(?,?)').run('expired-fixture',1);
  failBatchAt(stage);await assert.rejects(()=>skylineDeletionMaintenance(env,Date.now(),'scheduled'));
  assert.equal(sql.prepare('SELECT count(*) n FROM skyline_deletion_completions').get().n,1);
  assert.equal(sql.prepare('SELECT count(*) n FROM skyline_deletion_health').get().n,0);
 }
});

function productionEnv(env){return {...env,SKYLINE_BILLING_ENVIRONMENT:'production',SKYLINE_PAYMENTS_ENABLED:'production'}}
function realPurchase(member,quantity=1,product='skyline_coins_1500'){const p=quantityPurchase(member,quantity,product);delete p.testPurchaseContext;return p}

test('unknown environment and mismatched payment mode fail closed before database or Google',async()=>{
 for(const [environment,payments] of [['invalid',undefined],['',undefined],['production','sandbox'],['sandbox','production'],[undefined,'true'],['production','true']]){
  let touched=0;const env={DB:{prepare(){touched++;throw Error('database must remain untouched')}},SKYLINE_BILLING_ENVIRONMENT:environment,SKYLINE_PAYMENTS_ENABLED:payments};
  for(const path of ['account','entitlements','deletion-request','reconcile'])assert.equal((await skylineBilling(request(path,path==='entitlements'?undefined:{}),env,async()=>{touched++;throw Error('Google must remain untouched')})).status,503);
  assert.equal(touched,0);
 }
});
test('production never falls back when production migration is absent',async()=>{
 const {env,sql}=setup();sql.exec('DROP TABLE skyline_production_members');assert.equal((await skylineBilling(request('account',{}),productionEnv(env))).status,503);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_members').get().n,0);
});
test('production rejects present test context including null or malformed contexts and invalid proof',async()=>{
 for(const mutate of [p=>p.testPurchaseContext={fopType:'TEST'},p=>p.testPurchaseContext=null,p=>p.testPurchaseContext={},p=>p.testPurchaseContext='TEST',p=>p.obfuscatedExternalAccountId='wrong',p=>p.productLineItem[0].productOfferDetails.refundableQuantity=0,p=>p.productLineItem.push(p.productLineItem[0])]){
  const {env:base,sql}=setup(),env=productionEnv(base),a=await account(env),p=realPurchase(a.memberId);mutate(p);assert.notEqual((await verify(env,a,p)).response.status,200);assert.equal(sql.prepare('SELECT coins FROM skyline_production_wallets').get().coins,0);
 }
});
test('production pending cancelled and already consumed unknown receipts grant nothing',async()=>{
 for(const state of ['PENDING','CANCELLED','CONSUMED']){const {env:base,sql}=setup(),env=productionEnv(base),a=await account(env),p=realPurchase(a.memberId);
  if(state==='CONSUMED')p.productLineItem[0].productOfferDetails.consumptionState='CONSUMPTION_STATE_CONSUMED';else p.purchaseStateContext.purchaseState=state;
  assert.equal((await verify(env,a,p)).response.status,state==='PENDING'?200:409);assert.equal(sql.prepare('SELECT coins FROM skyline_production_wallets').get().coins,0);
 }
});
test('production settlement retry and concurrent grants are idempotent; paid economy remains isolated',async()=>{
 const {env:base,sql}=setup(),env=productionEnv(base),a=await account(env),p=realPurchase(a.memberId);
 assert.equal((await verify(env,a,p,'production-retry-token',true)).data.settlement,'retry');const retries=await Promise.all(Array.from({length:3},()=>verify(env,a,p,'production-retry-token')));assert.ok(retries.every(r=>r.data.settlement==='complete'));
 assert.equal(sql.prepare('SELECT coins FROM skyline_production_wallets').get().coins,1500);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_production_purchases_v2').get().n,1);
 for(const path of ['buy','spend'])for(let i=0;i<2;i++)assert.equal((await skylineBilling(request(path,{item:'net',requestId:'production-fixed-'+path},a.sessionToken),env)).status,200);
 const wallet=sql.prepare('SELECT coins,net FROM skyline_production_wallets').get();assert.equal(wallet.coins,1300);assert.equal(wallet.net,0);
 for(const table of ['members','wallets','purchases_v2','coin_buys_v2','spends_v2'])assert.equal(sql.prepare('SELECT count(*) n FROM skyline_'+table).get().n,0);
});
test('production partial refund rejects test-context proof before debit',async()=>{
 const {env:base,sql}=setup(),env=productionEnv(base),a=await account(env);await verify(env,a,realPurchase(a.memberId,2));await deletionOwner(env);
 const proof=quantityPurchase(a.memberId,2);proof.productLineItem[0].productOfferDetails.refundableQuantity=1;
 const send=async url=>String(url).includes('oauth2')?Response.json({access_token:'fixture'}):String(url).includes('productsv2')?Response.json(proof):Response.json({voidedPurchases:[{purchaseToken:'fixture-token',voidedTimeMillis:String(Date.now()-1000),voidedQuantity:1}]});
 assert.equal((await skylineBilling(request('reconcile',{},ownerKey),env,send)).status,503);assert.equal(sql.prepare('SELECT coins FROM skyline_production_wallets').get().coins,3000);
});

test('actual local D1 production namespace isolates accounts inventory refunds recovery deletion and maintenance',{skip:process.env.SKYLINE_TEST_D1!=='1'},async()=>{
 const {Miniflare}=await import('miniflare');const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("local")}}',d1Databases:{DB:'skyline-production-isolation-test'},compatibilityDate:'2026-05-22'});
 try{
  const db=await mf.getD1Database('DB');for(const name of ['0003_skyline_billing','0004_skyline_coin_shop','0005_skyline_refunds','0006_skyline_partial_refunds','0008_skyline_deletion_requests','0009_skyline_deletion_completion','0010_skyline_deletion_health','0011_skyline_production_billing'])for(const statement of readFileSync('drizzle/'+name+'.sql','utf8').split(';').map(s=>s.replace(/^--.*$/gm,'').trim()).filter(Boolean))await db.prepare(statement).run();
  const sandbox={DB:db,SKYLINE_PAYMENTS_ENABLED:'sandbox',GOOGLE_PLAY_SERVICE_ACCOUNT_EMAIL:'test@example.invalid',GOOGLE_PLAY_SERVICE_ACCOUNT_PRIVATE_KEY:pem},production=productionEnv(sandbox),a=await account(sandbox),b=await account(production);
  assert.notEqual(a.memberId,b.memberId);await verify(sandbox,a,quantityPurchase(a.memberId,4));const grants=await Promise.all(Array.from({length:4},()=>verify(production,b,realPurchase(b.memberId,4))));assert.ok(grants.every(r=>r.response.status===200));
  assert.equal((await db.prepare('SELECT coins FROM skyline_wallets').first()).coins,6000);assert.equal((await db.prepare('SELECT coins FROM skyline_production_wallets').first()).coins,6000);assert.equal((await db.prepare('SELECT count(*) n FROM skyline_production_purchases_v2').first()).n,1);
  for(const [env,foreign] of [[sandbox,b],[production,a]]){
   assert.equal((await skylineBilling(request('entitlements',undefined,foreign.sessionToken),env)).status,401);
   assert.equal((await skylineBilling(request('recover',{memberId:foreign.memberId,recoveryToken:foreign.recoveryToken}),env)).status,401);
   assert.equal((await skylineBilling(request('deletion-request',{},foreign.sessionToken),env)).status,401);
  }
  const at=Date.now()-1000;for(let i=0;i<2;i++)assert.equal((await reconcileRefunds(production,['fixture-token'],{partial:1,remaining:3,at})).response.status,200);
  assert.equal((await db.prepare('SELECT coins FROM skyline_production_wallets').first()).coins,4500);assert.equal((await db.prepare('SELECT coins FROM skyline_wallets').first()).coins,6000);
  for(let i=0;i<2;i++)assert.equal((await reconcileRefunds(production,['fixture-token'])).response.status,200);
  assert.equal((await db.prepare('SELECT coins FROM skyline_production_wallets').first()).coins,0);assert.equal((await db.prepare('SELECT refunded_quantity FROM skyline_production_refunds').first()).refunded_quantity,4);
  assert.equal((await verify(production,b,realPurchase(b.memberId,4))).response.status,409);assert.equal((await db.prepare('SELECT coins FROM skyline_wallets').first()).coins,6000);
  production.SKYLINE_PAYMENTS_ENABLED=undefined;
  const recovered=await skylineBilling(request('recover',{memberId:b.memberId,recoveryToken:b.recoveryToken}),production);assert.equal(recovered.status,200);const rotated=await recovered.json();assert.equal((await skylineBilling(request('entitlements',undefined,b.sessionToken),production)).status,401);assert.equal((await skylineBilling(request('entitlements',undefined,rotated.sessionToken),production)).status,200);
  assert.equal((await skylineBilling(request('buy',{item:'net',requestId:'disabled-production-buy'},rotated.sessionToken),production)).status,503);
  await deletionOwner(production);const id=await queuedDeletion(production,rotated);const completions=await Promise.all([completeDeletion(production,id),completeDeletion(production,id)]);assert.ok(completions.every(r=>r.status===200));assert.equal((await db.prepare('SELECT count(*) n FROM skyline_production_members').first()).n,0);assert.equal((await db.prepare('SELECT count(*) n FROM skyline_members').first()).n,1);
  await skylineDeletionMaintenance(production,Date.now(),'scheduled');assert.equal((await db.prepare('SELECT count(*) n FROM skyline_deletion_health').first()).n,0);assert.equal((await db.prepare('SELECT count(*) n FROM skyline_production_deletion_health').first()).n,1);
  assert.equal((await skylineBilling(request('entitlements',undefined,a.sessionToken),sandbox)).status,200);assert.equal((await skylineBilling(request('entitlements',undefined,rotated.sessionToken),production)).status,401);
 }finally{await mf.dispose()}
});

test('unauthenticated environment preflight reports mode without touching database or Google',async()=>{
 for(const mode of ['sandbox','production'])for(const enabled of [undefined,mode]){
  let calls=0;const env={DB:{prepare(){calls++;throw Error('must not touch database')}},SKYLINE_BILLING_ENVIRONMENT:mode,SKYLINE_PAYMENTS_ENABLED:enabled};
  const response=await skylineBilling(request('environment'),env,async()=>{calls++;throw Error('must not touch Google')});assert.equal(response.status,200);assert.deepEqual(await response.json(),{billingEnvironment:mode,paymentsOpen:enabled===mode});assert.equal(calls,0);
 }
});
test('native environment mismatch or invalid header rejects before account or ledger mutation',async()=>{
 for(const mode of ['sandbox','production'])for(const expected of [mode==='sandbox'?'production':'sandbox','invalid','']){
  const {env:base,sql}=setup(),env={...base,SKYLINE_BILLING_ENVIRONMENT:mode,SKYLINE_PAYMENTS_ENABLED:mode};
  for(const path of ['account','environment','deletion-request']){const r=request(path,path==='environment'?undefined:{});r.headers.set('X-Skyline-Billing-Environment',expected);assert.equal((await skylineBilling(r,env)).status,409);}
  assert.equal(sql.prepare('SELECT count(*) n FROM skyline_members').get().n,0);assert.equal(sql.prepare('SELECT count(*) n FROM skyline_production_members').get().n,0);
 }
 const {env}=setup(),r=request('account',{});r.headers.set('X-Skyline-Billing-Environment','sandbox');assert.equal((await skylineBilling(r,env)).status,200);
});
