'use client';
import{useEffect,useRef}from'react';import{optics,targetNotes,type LabState}from'./optics';
export default function Eyepiece({state}:{state:LabState}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;const v=optics(state),size=420,c=size/2;canvas.width=size;canvas.height=size;ctx.clearRect(0,0,size,size);ctx.save();ctx.beginPath();ctx.arc(c,c,190,0,Math.PI*2);ctx.clip();const bg=ctx.createRadialGradient(c,c,1,c,c,195);bg.addColorStop(0,'#0c1720');bg.addColorStop(1,'#010306');ctx.fillStyle=bg;ctx.fillRect(0,0,size,size);
 const zoom=targetNotes[state.target].crop;const scale=380/(v.field*3600)*zoom;const geometricBlur=v.defocusDisc/state.focal*206265;const blur=Math.min(40,Math.hypot(v.effectiveResolution*.35,geometricBlur*.25,v.aberrationDisc/state.focal*206265*.2)*scale);const object=document.createElement('canvas');object.width=size;object.height=size;const g=object.getContext('2d')!;g.translate(c,c);g.rotate(Math.PI);g.globalAlpha=Math.min(1,.38+v.exitPupil*.27)*Math.sqrt(v.transmission);
 if(state.target==='saturn'){g.rotate(-.4);const R=9*scale,outer=21*scale;g.save();g.scale(1,.34);for(let j=0;j<24;j++){g.beginPath();g.strokeStyle=`rgba(${185+j},${166+j},${134+j},${.35+(j%3)*.16})`;g.lineWidth=outer*.014;g.arc(0,0,outer*(.61+j*.016),0,Math.PI*2);g.stroke();}g.restore();const ball=g.createRadialGradient(-R*.45,-R*.4,1,R*.3,R*.1,R*1.2);ball.addColorStop(0,'#ecdbb6');ball.addColorStop(.45,'#bfaa86');ball.addColorStop(1,'#15212b');g.fillStyle=ball;g.beginPath();g.arc(0,0,R,0,Math.PI*2);g.fill();g.save();g.beginPath();g.arc(0,0,R,0,Math.PI*2);g.clip();for(let y=-R;y<R;y+=R/11){g.fillStyle=y%3?'#806f5535':'#eee4b738';g.fillRect(-R,y,R*2,R/19);}g.restore();g.save();g.scale(1,.34);for(let j=0;j<24;j++){g.beginPath();g.strokeStyle=`rgba(${185+j},${166+j},${134+j},.7)`;g.lineWidth=outer*.014;g.arc(0,0,outer*(.61+j*.016),0,Math.PI);g.stroke();}g.restore();
 }else if(state.target==='moon'){const R=900*scale;g.save();g.beginPath();g.arc(0,0,R,0,Math.PI*2);g.clip();const grad=g.createLinearGradient(-R,0,R,0);grad.addColorStop(0,'#eee5d0');grad.addColorStop(.6,'#a4a6a0');grad.addColorStop(1,'#17222a');g.fillStyle=grad;g.fillRect(-R,-R,R*2,R*2);let seed=82;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<180;i++){const x=(rnd()-.5)*R*2,y=(rnd()-.5)*R*2,r=(.01+rnd()*.075)*R;g.beginPath();g.fillStyle=i%4?'#6d74733f':'#515d6266';g.arc(x,y,r,0,Math.PI*2);g.fill();g.beginPath();g.strokeStyle='#f2f1df55';g.lineWidth=Math.max(.5,r*.1);g.arc(x-1,y-1,r,-2.4,.2);g.stroke();}g.restore();
 }else if(state.target==='jupiter'||state.target==='mars'||state.target==='venus'){
 const R=(state.target==='jupiter'?20:state.target==='mars'?7:15)*scale;
 const base=state.target==='jupiter'?'#e0c8a3':state.target==='mars'?'#c77d52':'#e5ddc3';
 g.save();g.beginPath();g.arc(0,0,R,0,Math.PI*2);g.clip();g.fillStyle=base;g.fillRect(-R,-R,R*2,R*2);
 if(state.target==='jupiter'){
  for(let j=0;j<13;j++){const y=(-.92+j*.15)*R;g.fillStyle=j%3===0?'#795841':j%3===1?'#b99070':'#ead9b7';g.beginPath();g.ellipse(0,y,R*1.4,R*.065,0,0,Math.PI*2);g.fill();}
  g.fillStyle='#b97450';g.beginPath();g.ellipse(R*.35,R*.35,R*.25,R*.12,-.15,0,Math.PI*2);g.fill();g.strokeStyle='#e0bf92';g.lineWidth=R*.025;g.stroke();
 }else if(state.target==='mars'){
  g.fillStyle='#6f6b5077';for(let j=0;j<6;j++){g.beginPath();g.ellipse(Math.sin(j*2.6)*R*.55,Math.cos(j*1.4)*R*.45,R*.3,R*.14,j*.7,0,Math.PI*2);g.fill();}
  g.fillStyle='#e7e7dd';g.beginPath();g.ellipse(0,-R*.9,R*.36,R*.12,0,0,Math.PI*2);g.fill();
 }else{
  // A fixed crescent teaching preset; this is not today's planetary phase.
  g.fillStyle='#06101a';g.beginPath();g.ellipse(R*.4,0,R*.88,R*1.08,0,0,Math.PI*2);g.fill();
 }
 const shade=g.createLinearGradient(-R,0,R,0);shade.addColorStop(0,'#04101800');shade.addColorStop(.65,'#04101810');shade.addColorStop(1,'#02060ba8');g.fillStyle=shade;g.fillRect(-R,-R,R*2,R*2);g.restore();
 if(state.target==='jupiter')for(let j=0;j<4;j++){const x=[-4.8,-2.7,2.8,4.6][j]*R,y=[.18,-.08,.05,-.21][j]*R;g.fillStyle='#e5dccb';g.beginPath();g.arc(x,y,Math.max(1.1,R*.025),0,Math.PI*2);g.fill();}
 }else{for(const x of[-1,1]){const R=Math.max(2,v.effectiveResolution*.44*scale);const grad=g.createRadialGradient(x*1.25*scale,0,0,x*1.25*scale,0,R*3);grad.addColorStop(0,x<0?'#ffdfaf':'#dae9ff');grad.addColorStop(.18,'#e6eaff');grad.addColorStop(1,'#96c7ff00');g.fillStyle=grad;g.beginPath();g.arc(x*1.25*scale,0,R*3,0,Math.PI*2);g.fill();}}
 ctx.filter=`blur(${state.target==='binary'?Math.min(25,Math.hypot(geometricBlur*.25,v.aberrationDisc/state.focal*206265*.2)*scale):blur}px)`;ctx.drawImage(object,0,0);ctx.filter='none';ctx.restore();ctx.strokeStyle='#69869740';ctx.lineWidth=1;ctx.beginPath();ctx.arc(c,c,190,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#72919f55';for(let i=0;i<4;i++){ctx.save();ctx.translate(c,c);ctx.rotate(i*Math.PI/2);ctx.beginPath();ctx.moveTo(0,-184);ctx.lineTo(0,-175);ctx.stroke();ctx.restore();}
 },[state]);return <canvas ref={ref} className="eyepiece-canvas" role="img" aria-label={`${state.target} through the eyepiece at ${optics(state).magnification.toFixed(0)} times magnification, ${Math.abs(state.focus)<.1?'in focus':'defocused'}. Illustrative rendering.`}/>;}
