'use client';
import{useEffect,useRef,useState}from'react';import*as T from'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';import{kit,material,textSprite,fox,foxColors,disposeScene}from'./three-kit';import{landscape}from'./garden-landscape';import type{Person}from'./activity';
export const portals=[{id:'telescope',title:'Through the Glass',x:0,z:-6.9,color:0xf0ca8d},{id:'airport',title:'Airside Intelligence',x:6.6,z:-4.8,color:0x89d3db},{id:'lightning',title:'Lightning Lab',x:8.5,z:2.9,color:0xcab4eb},{id:'aeolith',title:'AEOLITH',x:3.5,z:7,color:0xd69baf},{id:'fable-flight',title:'Fable Flight',x:-3.5,z:7,color:0xb5ce95},{id:'galevein',title:'Galevein',x:-8.5,z:2.9,color:0x9ecccc},{id:'universe-clash',title:'Universe Clash',x:-6.6,z:-4.8,color:0xddad8c}];
export type GardenState={people:Person[];you:string;me:Person|null;view:string;motion:boolean;form:'fox'|'guardian';move:{x:number;z:number};running:boolean};
export default function GardenScene({state,onPosition,onPortal,onPerson}:{state:GardenState;onPosition:(x:number,z:number)=>void;onPortal:(id:string)=>void;onPerson:(p:Person)=>void}){
 const host=useRef<HTMLDivElement>(null),latest=useRef({state,onPosition,onPortal,onPerson});latest.current={state,onPosition,onPortal,onPerson};const[failed,setFailed]=useState(false);
 useEffect(()=>{
  if(!host.current)return;const mount=host.current;let r:T.WebGLRenderer;try{r=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:true});}catch{setFailed(true);return;}
  r.setPixelRatio(Math.min(devicePixelRatio,1.5));r.setClearColor(0x0c1c22);r.toneMapping=T.ACESFilmicToneMapping;r.toneMappingExposure=1;r.shadowMap.enabled=true;r.shadowMap.type=T.PCFShadowMap;mount.appendChild(r.domElement);r.domElement.setAttribute('aria-label','A futuristic garden with fox avatars and seven world portals. Find a world opens an accessible list.');
  const scene=new T.Scene();scene.fog=new T.FogExp2(0x0c1c22,.0035);const camera=new T.PerspectiveCamera(40,1,.1,400),controls=new OrbitControls(camera,r.domElement);controls.enableDamping=true;controls.minDistance=8;controls.maxDistance=225;controls.maxPolarAngle=Math.PI*.475;controls.enablePan=false;controls.target.set(0,1.2,0);camera.position.set(20,14,28);controls.update();
  scene.add(new T.HemisphereLight(0xd6eeef,0x193733,1.8));const sun=new T.DirectionalLight(0xffd8ab,2.6);sun.position.set(-12,20,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-17,right:17,top:17,bottom:-17,near:.5,far:65});sun.shadow.bias=-.0004;sun.shadow.normalBias=.045;scene.add(sun);const blue=new T.DirectionalLight(0x91d5e3,2);blue.position.set(12,9,-15);scene.add(blue);
  const animateLandscape=landscape(scene);
  const world=new T.Group();scene.add(world);const{box,cyl,ball,rod}=kit(world),stone=material(0x435953,.83),rim=material(0x233c3b,.35,.65),gold=material(0x92794e,.32,.7),grass=material(0x365d49),bark=material(0x4c4940),leaf=material(0x55836a),pearl=material(0x96aca2),mintGlow=new T.MeshBasicMaterial({color:0x8ecdc1}),waterMat=new T.MeshPhysicalMaterial({color:0x204844,roughness:.18,metalness:.6,transparent:true,opacity:.95});
  cyl(0,-.55,0,12,.8,rim);cyl(0,-.11,0,11.85,.08,gold);cyl(0,-.06,0,11.72,.08,stone);cyl(0,-.01,0,3.6,.045,waterMat);
  for(const radius of[3.7,10.9,11.5]){const ring=new T.Mesh(new T.TorusGeometry(radius,.035,8,180),radius===10.9?mintGlow:gold);ring.rotation.x=Math.PI/2;ring.position.y=.03;world.add(ring);}
  // Inlaid radial paths, luminous seams and island planters.
  for(let i=0;i<16;i++){const a=i/16*Math.PI*2;rod(new T.Vector3(Math.sin(a)*3.9,.01,Math.cos(a)*3.9),new T.Vector3(Math.sin(a)*10.8,.01,Math.cos(a)*10.8),.009,gold);}
  let seed=61;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
  const canopyMotion:{mesh:T.Mesh;x:number;z:number;phase:number}[]=[];
  const tree=(x:number,z:number,scale=1)=>{cyl(x,.23,z,1.5*scale,.46,rim);cyl(x,.49,z,1.43*scale,.06,grass);cyl(x,1.65*scale,z,.16*scale,2.9*scale,bark,.09*scale,10);for(let j=0;j<6;j++){const a=j*2.399,p=new T.Vector3(x+Math.sin(a)*.9*scale,(2.5+rand())*scale,z+Math.cos(a)*.9*scale);rod(new T.Vector3(x,1.8*scale,z),p,.05*scale,bark);const crown=ball(p.x,p.y,p.z,.92*scale,leaf);crown.scale.y=.7;canopyMotion.push({mesh:crown,x:p.x,z:p.z,phase:x+z+j});}for(let j=0;j<8;j++){const a=j*2.4;const b=ball(x+Math.sin(a)*scale,.66,z+Math.cos(a)*scale,.23,grass);b.scale.set(1,1.9,.8);}};
  for(const[x,z,s]of[[-4,-1,1.1],[4.3,1,1],[-.7,4.4,.8],[4.9,-8.5,.9],[-5,-8.2,.9]])tree(x,z,s);
  // Central solar tree with six photovoltaic leaves; a visible closed water loop.
  cyl(0,2,0,.14,4,rim,.11);for(let i=0;i<6;i++){const a=i*Math.PI/3,end=new T.Vector3(Math.sin(a)*2.2,4.5,Math.cos(a)*2.2);rod(new T.Vector3(0,3.15,0),end,.055,gold);const panel=box(end.x,4.45,end.z,1.4,.07,2.1,rim);panel.rotation.set(.14,a,.1);for(let j=0;j<5;j++){const c=box(end.x+Math.cos(a)*(j-2)*.24,4.5,end.z-Math.sin(a)*(j-2)*.24,.2,.025,1.85,material(0x346975,.22,.55));c.rotation.set(.14,a,.1);}}
  cyl(0,.18,0,1.25,.35,rim);cyl(0,.38,0,1.05,.04,waterMat);for(let i=0;i<4;i++){const ring=new T.Mesh(new T.TorusGeometry(.4+i*.2,.009,6,64),mintGlow);ring.rotation.x=Math.PI/2;ring.position.y=.41;world.add(ring);}
  // Hydroponic terraces, seating, a transparent biodome frame.
  for(const sign of[-1,1])for(let row=0;row<3;row++){box(sign*8,.4+row*.3,-7.5+row*.65,2.4,.18,.4,pearl);for(let j=0;j<8;j++){const b=ball(sign*8+(j-3.5)*.26,.65+row*.3,-7.5+row*.65,.15,leaf);b.scale.y=1.7;}}
  for(const[x,z,a]of[[-5,4,.5],[5,4,-.5]]){const seat=box(x,.65,z,2.3,.2,.7,pearl);seat.rotation.y=a;for(const dx of[-.8,.8])box(x+dx,.32,z,.12,.64,.5,gold);}
  for(let i=0;i<7;i++){const a=i*Math.PI/6,points:T.Vector3[]=[];for(let j=0;j<=60;j++){const t=j/60*Math.PI;points.push(new T.Vector3(Math.cos(t)*13*Math.cos(a),Math.sin(t)*11,Math.cos(t)*13*Math.sin(a)));}world.add(new T.Line(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color:0x487d78,transparent:true,opacity:.35})));}
  for(let i=0;i<20;i++){const a=i/20*Math.PI*2;const x=Math.sin(a)*16,z=Math.cos(a)*16;box(x,-.5,z,1.6,1+rand()*4,1.6,material(0x182d30));}
  // One shared clock and shared particle geometry keep each luminous doorway inexpensive.
  const portalClock={value:0},gateEffects:{arcs:T.Group;floor:T.Mesh;phase:number}[]=[];
  const traceGeometry=new T.BufferGeometry(),traceSeeds=[];for(let i=0;i<96;i++)traceSeeds.push(i/96,((i*37)%96)/96,0);traceGeometry.setAttribute('position',new T.Float32BufferAttribute(traceSeeds,3));
  const arcGeometry=new T.TorusGeometry(1.3,.013,6,64,Math.PI*.56),floorGeometry=new T.RingGeometry(.9,1.42,64);
  const pickables:T.Object3D[]=[];for(const [index,p]of portals.entries()){
   const gate=new T.Group();gate.position.set(p.x,0,p.z);gate.lookAt(0,0,0);world.add(gate);const g=kit(gate),tint=new T.Color(p.color),emissive=new T.MeshStandardMaterial({color:p.color,emissive:p.color,emissiveIntensity:1.4,roughness:.2,metalness:.65});
   g.cyl(0,.16,0,1.35,.3,rim);g.cyl(0,.33,0,1.15,.04,gold);const hoop=new T.Mesh(new T.TorusGeometry(1.13,.045,12,96),emissive);hoop.position.y=1.75;gate.add(hoop);
   const veil=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,blending:T.AdditiveBlending,uniforms:{time:portalClock,tint:{value:tint},phase:{value:index}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec2 vUv;uniform float time;uniform float phase;uniform vec3 tint;void main(){vec2 p=vUv-.5;float r=length(p)*2.;float a=atan(p.y,p.x);float edge=pow(smoothstep(.35,1.,r),4.)*(1.-smoothstep(.97,1.,r));float swirl=pow(.5+.5*sin(a*3.+r*12.-time*.6+phase),10.)*.13;float pool=(1.-r)*.12;gl_FragColor=vec4(tint,clamp(edge*.72+swirl+pool,0.,.8));}`});
   const inner=new T.Mesh(new T.CircleGeometry(1.07,64),veil);inner.position.set(0,1.75,0);gate.add(inner);
   const icon=new T.Mesh(p.id==='telescope'?new T.TorusGeometry(.4,.075,12,50):p.id==='airport'?new T.OctahedronGeometry(.5):p.id==='fable-flight'?new T.BoxGeometry(.62,.62,.62):new T.IcosahedronGeometry(.47,0),emissive);icon.position.set(0,1.75,.13);gate.add(icon);gate.userData.icon=icon;
   const arcs=new T.Group();arcs.position.y=1.75;for(let j=0;j<3;j++){const arc=new T.Mesh(arcGeometry,new T.MeshBasicMaterial({color:p.color,transparent:true,opacity:.55,depthWrite:false,blending:T.AdditiveBlending}));arc.rotation.z=j*Math.PI*2/3;arcs.add(arc);}gate.add(arcs);
   const floor=new T.Mesh(floorGeometry,new T.MeshBasicMaterial({color:p.color,transparent:true,opacity:.14,side:T.DoubleSide,depthWrite:false,blending:T.AdditiveBlending}));floor.rotation.x=-Math.PI/2;floor.position.y=.35;gate.add(floor);gateEffects.push({arcs,floor,phase:index});
   const tracers=new T.Points(traceGeometry,new T.ShaderMaterial({transparent:true,depthWrite:false,blending:T.AdditiveBlending,uniforms:{time:portalClock,tint:{value:tint},phase:{value:index}},vertexShader:`uniform float time;uniform float phase;varying float strength;void main(){float a=position.x*6.28318+time*.23+phase;float r=1.15+position.y*.21;vec3 p=vec3(cos(a)*r,1.75+sin(a)*r,sin(a*2.+time*.3)*.12);vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=clamp(46./-mv.z,1.1,7.);strength=.35+.65*pow(.5+.5*sin(a-time*.8),5.);}`,fragmentShader:`uniform vec3 tint;varying float strength;void main(){float d=length(gl_PointCoord-.5)*2.;float alpha=pow(max(0.,1.-d),2.)*strength;gl_FragColor=vec4(tint,alpha);}`}));tracers.frustumCulled=false;gate.add(tracers);
   const label=textSprite(p.title,'#e8eee4',2.6);label.position.set(0,3.35,0);gate.add(label);gate.traverse(o=>{o.userData.portal=p.id;if(o instanceof T.Mesh)pickables.push(o);});
  }
  const particles=[];for(let i=0;i<170;i++)particles.push((rand()-.5)*24,rand()*6+.3,(rand()-.5)*22);const pg=new T.BufferGeometry();pg.setAttribute('position',new T.Float32BufferAttribute(particles,3));const motes=new T.Points(pg,new T.PointsMaterial({color:0xefcf96,size:.032,transparent:true,opacity:.65,depthWrite:false,blending:T.AdditiveBlending}));scene.add(motes);
  // All connected visitors share geometry: 18 draws for up to 200 original foxes.
  const avatarRoot=new T.Group();scene.add(avatarRoot);
  const flockRoot=new T.Group();scene.add(flockRoot);const capacity=200;
  const coat=material(0xffffff,.85),cream=material(0xffebce,.94),ink=material(0x152d31),collarMat=material(0x88e3d7,.3,.55);
  const parts:{mesh:T.InstancedMesh;local:T.Matrix4;tint:boolean}[]=[];
  const part=(geo:T.BufferGeometry,mat:T.Material,x:number,y:number,z:number,sx=1,sy=1,sz=1,rz=0,ry=0,tint=false)=>{const mesh=new T.InstancedMesh(geo,mat,capacity),o=new T.Object3D();o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.rotation.set(0,ry,rz);o.updateMatrix();mesh.count=0;mesh.frustumCulled=false;mesh.instanceMatrix.setUsage(T.DynamicDrawUsage);flockRoot.add(mesh);parts.push({mesh,local:o.matrix.clone(),tint});};
  const sphere=new T.SphereGeometry(1,10,7),cone=new T.ConeGeometry(1,1,4);
  part(sphere,coat,0,.7,0,.34,.5,.45,0,0,true);part(sphere,cream,0,.84,.27,.22,.32,.2);
  part(sphere,coat,0,1.32,.13,.43,.37,.39,0,0,true);part(sphere,cream,0,1.18,.48,.28,.15,.23);part(sphere,ink,0,1.22,.68,.065,.065,.065);
  for(const sign of[-1,1]){part(cone,coat,sign*.28,1.75,.1,.2,.55,.2,-sign*.2,0,true);part(cone,cream,sign*.28,1.77,.18,.115,.33,.09,-sign*.2);part(sphere,ink,sign*.2,1.36,.48,.05,.05,.05);part(sphere,ink,sign*.21,.14,.1,.14,.12,.2);part(sphere,coat,sign*.35,.68,.07,.1,.26,.1,sign*.18,0,true);}
  part(sphere,coat,.18,.54,-.64,.26,.25,.62,0,-.35,true);part(sphere,cream,.36,.58,-1.09,.22,.22,.24);part(new T.CylinderGeometry(.3,.3,.07,10),collarMat,0,1.03,.12);
  type Guest={person:Person;position:T.Vector3;target:T.Vector3;yaw:number};let guests:Guest[]=[];const guestCache=new Map<string,Guest>(),guestLabels:T.Sprite[]=[];
  for(let i=0;i<6;i++){const label=textSprite('','#dfefe6',2.5);label.visible=false;scene.add(label);guestLabels.push(label);}
  let mine=fox('amber');mine.scale.setScalar(.85);mine.position.set(0,.06,5);avatarRoot.add(mine);let mineColor='amber',mineForm='',lastPeople='',lastView='',spawned=false,entering=false,travel=0;
  const selfLabel=textSprite('YOU','#f4dec0',.8);selfLabel.position.y=2.1;scene.add(selfLabel);
  const selfRing=new T.Mesh(new T.RingGeometry(.58,.63,48),new T.MeshBasicMaterial({color:0xd7bb7d,transparent:true,opacity:.8,side:T.DoubleSide,depthWrite:false}));selfRing.rotation.x=-Math.PI/2;scene.add(selfRing);
  const destination=new T.Vector3(0,.06,5),keys=new Set<string>(),ray=new T.Raycaster(),mouse=new T.Vector2(),ground=new T.Plane(new T.Vector3(0,1,0),0);let down=[0,0];
  const guardian=(root:T.Group)=>{const g=new T.Group(),q=kit(g),armour=material(0x315762,.25,.7),brass=material(0xcfb26c,.3,.7),light=new T.MeshBasicMaterial({color:0xb1f4e6});g.name='guardian';for(const sign of[-1,1]){const shoulder=q.ball(sign*.42,1.02,.04,.23,armour);shoulder.scale.set(1.4,.75,1);q.box(sign*.21,.35,.11,.28,.35,.28,armour);const spike=new T.Mesh(new T.ConeGeometry(.065,.3,4),brass);spike.position.set(sign*.46,1.3,.02);g.add(spike);}q.box(0,.79,.41,.47,.46,.09,armour);q.box(0,.83,.465,.2,.18,.025,light);q.rod(new T.Vector3(.65,.2,.03),new T.Vector3(.65,2.2,.03),.035,brass);for(const x of[-.18,0,.18]){q.rod(new T.Vector3(.65,1.93,.03),new T.Vector3(.65+x,2.16,.03),.025,brass);q.rod(new T.Vector3(.65+x,2.16,.03),new T.Vector3(.65+x,2.43,.03),.018,light);}root.add(g);};
  const keyDown=(e:KeyboardEvent)=>{if(e.target instanceof HTMLElement&&e.target.closest('input,textarea,select,[contenteditable="true"],[role="dialog"]'))return;if(['w','a','s','d','W','A','S','D','ArrowUp','ArrowLeft','ArrowDown','ArrowRight','Shift'].includes(e.key)){keys.add(e.key.toLowerCase());e.preventDefault();}};const keyUp=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());const blur=()=>keys.clear();window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',blur);
  const pointerDown=(e:PointerEvent)=>{down=[e.clientX,e.clientY];};const click=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const b=r.domElement.getBoundingClientRect();mouse.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(mouse,camera);const hits=ray.intersectObjects([...pickables,...parts.map(p=>p.mesh)],false);if(hits[0]){const o=hits[0].object;if(o.userData.portal){latest.current.onPortal(o.userData.portal);return;}const index=hits[0].instanceId;if(index!==undefined&&guests[index]){latest.current.onPerson(guests[index].person);return;}}const hit=new T.Vector3();if(ray.ray.intersectPlane(ground,hit)&&hit.length()<110){destination.set(Math.max(-90,Math.min(90,hit.x)),.06,Math.max(-70,Math.min(80,hit.z)));}};r.domElement.addEventListener('pointerdown',pointerDown);r.domElement.addEventListener('pointerup',click);
  const resize=()=>{r.setSize(mount.clientWidth,mount.clientHeight);camera.aspect=mount.clientWidth/mount.clientHeight;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(mount);resize();let frame=0,last=0,report=0,visible=true;const io=new IntersectionObserver(e=>{visible=e[0].isIntersecting;});io.observe(mount);
  function animate(t:number){frame=requestAnimationFrame(animate);if(document.hidden||!visible||t-last<32)return;const dt=Math.min(.06,(t-last)/1000);last=t;const s=latest.current.state;if(s.view!==lastView){lastView=s.view;if(s.view==='ground'){camera.position.copy(mine.position).add(new T.Vector3(0,4.2,8));controls.target.copy(mine.position).add(new T.Vector3(0,1,0));controls.minDistance=2;controls.maxDistance=24;}else if(s.view==='above'){camera.position.set(0,155,42);controls.target.set(0,0,0);controls.minDistance=15;controls.maxDistance=225;}else if(s.view==='waterfall'){camera.position.set(0,26,25);controls.target.set(0,6,-39);controls.minDistance=5;controls.maxDistance=90;}else{camera.position.set(20,14,28);controls.target.set(0,1.2,-2);controls.minDistance=8;controls.maxDistance=180;}}
   if(s.me&&!spawned){spawned=true;const n=parseInt(s.me.id.slice(0,4),16),a=(n/65535-.5)*.9;mine.position.set(Math.sin(a)*6.3,.06,Math.cos(a)*6.3);destination.copy(mine.position);}
   const color=s.me?.color||'amber';if(color!==mineColor||s.form!==mineForm){mineColor=color;mineForm=s.form;const pos=mine.position.clone(),yaw=mine.rotation.y;avatarRoot.remove(mine);disposeScene(mine);mine=fox(color);mine.scale.setScalar(.85);mine.position.copy(pos);mine.rotation.y=yaw;if(s.form==='guardian')guardian(mine);avatarRoot.add(mine);}
   const signature=JSON.stringify(s.people);if(lastPeople!==signature){lastPeople=signature;const remote=s.people.filter(p=>p.id!==s.you).slice(0,capacity),ids=new Set(remote.map(p=>p.id));for(const id of guestCache.keys())if(!ids.has(id))guestCache.delete(id);guests=remote.map(p=>{let g=guestCache.get(p.id);if(!g){g={person:p,position:new T.Vector3(p.x||0,.06,p.z||0),target:new T.Vector3(),yaw:0};guestCache.set(p.id,g);}g.person=p;g.target.set(p.x||0,.06,p.z||0);return g;});for(const part of parts){part.mesh.count=guests.length;if(part.tint){guests.forEach((g,i)=>part.mesh.setColorAt(i,new T.Color(foxColors[g.person.color]||foxColors.amber)));if(part.mesh.instanceColor)part.mesh.instanceColor.needsUpdate=true;}}}
   let dx=s.move.x,dz=s.move.z;if(keys.has('w')||keys.has('arrowup'))dz-=1;if(keys.has('s')||keys.has('arrowdown'))dz+=1;if(keys.has('a')||keys.has('arrowleft'))dx-=1;if(keys.has('d')||keys.has('arrowright'))dx+=1;
   if(dx||dz){const forward=new T.Vector3();camera.getWorldDirection(forward);forward.y=0;forward.normalize();const right=new T.Vector3(-forward.z,0,forward.x);const dir=right.multiplyScalar(dx).addScaledVector(forward,-dz).normalize();destination.copy(mine.position).addScaledVector(dir,2);destination.x=T.MathUtils.clamp(destination.x,-90,90);destination.z=T.MathUtils.clamp(destination.z,-70,80);}
   const before=mine.position.clone(),d=destination.clone().sub(mine.position),distance=d.length(),moving=distance>.04;
   if(moving){mine.rotation.y=Math.atan2(d.x,d.z);mine.position.addScaledVector(d.normalize(),Math.min(dt*(keys.has('shift')||s.running?13:4.8),distance));travel+=mine.position.distanceTo(before);}mine.position.y=.06+(s.motion&&moving?Math.sin(t*.017)*.04:0);selfLabel.position.copy(mine.position).add(new T.Vector3(0,2.05,0));selfLabel.visible=s.view!=='above';selfRing.position.set(mine.position.x,.045,mine.position.z);selfRing.scale.setScalar(1+(s.motion?Math.sin(t*.002)*.035:0));
   if(t-report>500){report=t;latest.current.onPosition(mine.position.x,mine.position.z);}
   const avatarMatrix=new T.Matrix4(),q=new T.Quaternion(),partMatrix=new T.Matrix4(),scale=new T.Vector3(.85,.85,.85),up=new T.Vector3(0,1,0);
   guests.forEach((g,i)=>{const diff=g.target.clone().sub(g.position);if(diff.length()>.05)g.yaw=Math.atan2(diff.x,diff.z);g.position.lerp(g.target,Math.min(1,dt*3));q.setFromAxisAngle(up,g.yaw);avatarMatrix.compose(g.position,q,scale);for(const part of parts){partMatrix.multiplyMatrices(avatarMatrix,part.local);part.mesh.setMatrixAt(i,partMatrix);}});parts.forEach(p=>{p.mesh.instanceMatrix.needsUpdate=true;p.mesh.boundingSphere=null;});
   // Names only appear nearby; the complete flock stays rendered at every distance.
   const nearest=guests.map(g=>({g,d:g.position.distanceTo(camera.position)})).filter(v=>v.d<24).sort((a,b)=>a.d-b.d).slice(0,6);guestLabels.forEach((label,i)=>{const guest=nearest[i]?.g;label.visible=!!guest;if(!guest)return;label.position.copy(guest.position).add(new T.Vector3(0,1.98,0));if(label.userData.name!==guest.person.alias){const canvas=label.material.map!.image as HTMLCanvasElement,ctx=canvas.getContext('2d')!;ctx.clearRect(0,0,640,128);ctx.fillStyle='rgba(8,24,25,.86)';ctx.beginPath();ctx.roundRect(8,16,624,96,28);ctx.fill();ctx.fillStyle='#dfefe6';ctx.font='500 34px system-ui';ctx.textAlign='center';ctx.fillText(guest.person.alias,320,78);label.material.map!.needsUpdate=true;label.userData.name=guest.person.alias;}});
   if(s.view==='ground'){camera.position.add(mine.position.clone().sub(before));controls.target.lerp(mine.position.clone().add(new T.Vector3(0,1,0)),.15);}
   if(!entering&&travel>1&&moving){const near=portals.find(p=>Math.hypot(p.x-mine.position.x,p.z-mine.position.z)<.85);if(near){entering=true;latest.current.onPortal(near.id);}}animateLandscape(t,s.motion);
   if(s.motion){portalClock.value=t*.001;gateEffects.forEach(g=>{g.arcs.rotation.z=t*.00012+g.phase;g.floor.scale.setScalar(1+Math.sin(t*.001+g.phase)*.035);});canopyMotion.forEach(c=>{c.mesh.position.x=c.x+Math.sin(t*.00065+c.phase)*.025;c.mesh.position.z=c.z+Math.cos(t*.0005+c.phase)*.02;});motes.rotation.y=t*.000008;world.children.forEach(o=>{if(o.userData.icon){o.userData.icon.rotation.y=t*.0003;o.userData.icon.position.y=1.75+Math.sin(t*.001)*.08;}});if(mine.userData.tail)mine.userData.tail.rotation.y=Math.sin(t*.0018)*.16;}controls.update();r.render(scene,camera);
  }frame=requestAnimationFrame(animate);
  return()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',blur);r.domElement.removeEventListener('pointerdown',pointerDown);r.domElement.removeEventListener('pointerup',click);controls.dispose();disposeScene(scene);r.dispose();r.domElement.remove();};
 },[]);
 return <div className="garden-canvas" ref={host}>{failed&&<div className="scene-fallback"><h2>The garden needs WebGL.</h2><p>Use Find a world to explore without the 3D view.</p></div>}</div>;
}
