import * as T from 'three';

/** Procedural distant scenery: five draw calls, no textures or post-processing. */
export function buildOrbitalBackdrop(scene:T.Scene){
 const root=new T.Group();root.name='orbital-garden-backdrop';scene.add(root);const clock={value:0};
 const sky=new T.Mesh(new T.SphereGeometry(740,32,16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,fog:false,uniforms:{time:clock},vertexShader:`varying vec3 direction;void main(){direction=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec3 direction;uniform float time;
 float cloud(vec3 p){return sin(p.x*3.+sin(p.y*5.))*sin(p.y*4.+cos(p.z*3.))*.5+.5;}
 void main(){vec3 d=normalize(direction);float band=exp(-pow((d.y*.7+d.x*.35-.27)*4.,2.));float dust=cloud(d*4.+vec3(time*.002,0.,0.))*cloud(d*9.);float halo=pow(max(0.,dot(d,normalize(vec3(-.5,.4,-.8)))),18.);vec3 col=vec3(.004,.007,.021)+band*dust*vec3(.052,.029,.087)+halo*vec3(.038,.065,.09);gl_FragColor=vec4(col,1.);}`}));sky.renderOrder=-20;root.add(sky);
 let seed=194;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};const positions:number[]=[],colors:number[]=[];
 for(let i=0;i<1500;i++){const y=rand()*2-1,a=rand()*Math.PI*2,r=Math.sqrt(1-y*y),brightness=.45+rand()*.55;positions.push(Math.cos(a)*r*670,y*670,Math.sin(a)*r*670);colors.push(brightness*(i%3===0?.77:1),brightness*(i%3===1?.83:1),brightness);}
 const starGeo=new T.BufferGeometry();starGeo.setAttribute('position',new T.Float32BufferAttribute(positions,3));starGeo.setAttribute('color',new T.Float32BufferAttribute(colors,3));
 const stars=new T.Points(starGeo,new T.PointsMaterial({vertexColors:true,size:.9,sizeAttenuation:true,transparent:true,opacity:.88,depthWrite:false,fog:false}));stars.renderOrder=-19;root.add(stars);
 const planet=new T.Mesh(new T.SphereGeometry(125,64,32),new T.ShaderMaterial({fog:false,uniforms:{time:clock},vertexShader:`varying vec3 vNormal;varying vec3 vLocal;void main(){vNormal=normalize(normalMatrix*normal);vLocal=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`varying vec3 vNormal;varying vec3 vLocal;uniform float time;void main(){vec3 p=normalize(vLocal);float bands=sin(p.y*26.+sin(p.x*8.+p.z*11.)*.9);float cloud=sin(p.x*19.+sin(p.z*15.))*sin(p.y*31.+p.z*9.);vec3 surface=mix(vec3(.035,.082,.14),vec3(.24,.34,.39),smoothstep(-.3,.7,bands+cloud*.3));float sunlight=max(0.,dot(normalize(vNormal),normalize(vec3(-.7,.35,1.))));float rim=pow(1.-max(0.,vNormal.z),3.);gl_FragColor=vec4(surface*(.035+sunlight*.92)+rim*vec3(.026,.064,.09),1.);}`}));planet.position.set(-185,115,-450);planet.rotation.z=.2;root.add(planet);
 const air=new T.Mesh(new T.SphereGeometry(129,48,24),new T.ShaderMaterial({side:T.BackSide,transparent:true,depthWrite:false,fog:false,blending:T.AdditiveBlending,vertexShader:`varying vec3 n;varying vec3 eye;void main(){vec4 p=modelViewMatrix*vec4(position,1.);n=normalize(normalMatrix*normal);eye=normalize(-p.xyz);gl_Position=projectionMatrix*p;}`,fragmentShader:`varying vec3 n;varying vec3 eye;void main(){float glow=pow(1.-abs(dot(normalize(n),normalize(eye))),3.);gl_FragColor=vec4(.16,.4,.57,glow*.4);}`}));air.position.copy(planet.position);root.add(air);
 const orbitPoints:T.Vector3[]=[];for(let i=0;i<=160;i++){const a=i/160*Math.PI*2;orbitPoints.push(new T.Vector3(Math.cos(a)*190,Math.sin(a)*35,Math.sin(a)*170));}const orbit=new T.LineLoop(new T.BufferGeometry().setFromPoints(orbitPoints),new T.LineBasicMaterial({color:0x91b7be,transparent:true,opacity:.13,depthWrite:false,fog:false}));orbit.position.copy(planet.position);orbit.rotation.z=.26;root.add(orbit);
 let elapsed=0,last:number|null=null;return{root,animate(t:number,motion:boolean,camera:T.Camera){const dt=last===null?0:Math.min(.06,Math.max(0,(t-last)/1000));last=t;if(motion)elapsed+=dt;clock.value=elapsed;sky.position.copy(camera.position);stars.position.copy(camera.position);stars.rotation.y=elapsed*.00035;planet.rotation.y=elapsed*.003;}};
}
