'use client';
import{discoveriesCourt}from'./garden-architecture';
import{buildGardenFountain}from'./garden-fountain';
import{buildOrbitalBackdrop}from'./garden-orbit';
import{buildPortalLabels}from'./garden-labels';
import{portalRecycleStep}from'./portal-recycling';
import{useEffect,useRef,useState}from'react';import*as T from'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';import{kit,material,textSprite,fox,foxColors,disposeScene,type FoxAccessory}from'./three-kit';import{landscape,gardenPath,resolveGardenPosition,type GardenPoint}from'./garden-landscape';import{buildShrines,shrinePortals,shrineBatch}from'./garden-shrines';import type{Person}from'./activity';
export const portals=shrinePortals;
export type GardenState={people:Person[];you:string;me:Person|null;view:string;motion:boolean;form:'fox'|'guardian';accessory:FoxAccessory;move:{x:number;z:number};running:boolean;focusPerson:string|null;community:{views:number|null;favorites:number|null}};
export default function GardenScene({state,onPosition,onPortal,onPerson,onLeaderboard}:{state:GardenState;onPosition:(x:number,z:number)=>void;onPortal:(id:string)=>void;onPerson:(p:Person)=>void;onLeaderboard:()=>void}){
 const host=useRef<HTMLDivElement>(null),latest=useRef({state,onPosition,onPortal,onPerson,onLeaderboard});latest.current={state,onPosition,onPortal,onPerson,onLeaderboard};const[failed,setFailed]=useState(false);
 useEffect(()=>{
  if(!host.current)return;const mount=host.current;let r:T.WebGLRenderer;try{r=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:true});}catch{setFailed(true);return;}
  r.setPixelRatio(Math.min(devicePixelRatio,mount.clientWidth<700?1:1.25));r.setClearColor(0x02040c);r.toneMapping=T.ACESFilmicToneMapping;r.toneMappingExposure=1.1;r.shadowMap.enabled=true;r.shadowMap.type=T.PCFShadowMap;mount.appendChild(r.domElement);r.domElement.setAttribute('aria-label',`A shrine garden with live fox avatars and ${shrineBatch(0).length} rotating world portals. Find a world opens an accessible list.`);
  let portals=shrineBatch(0),portalOffset=0,recycleElapsed=0,recycleLast=performance.now(),revealStarted=-Infinity;
  const scene=new T.Scene();scene.fog=new T.FogExp2(0x06121b,.0023);const camera=new T.PerspectiveCamera(48,1,.1,1100),controls=new OrbitControls(camera,r.domElement);controls.enableDamping=true;controls.minDistance=8;controls.maxDistance=225;controls.maxPolarAngle=Math.PI*.475;controls.enablePan=false;controls.target.set(0,3,0);camera.position.set(52,50,86);controls.update();
  const hemisphere=new T.HemisphereLight(0xd6eeef,0x193733,2.05);scene.add(hemisphere);const sun=new T.DirectionalLight(0xffd8ab,2.6);sun.position.set(-30,48,20);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-48,right:48,top:48,bottom:-48,near:.5,far:140});sun.shadow.bias=-.0004;sun.shadow.normalBias=.045;scene.add(sun);const blue=new T.DirectionalLight(0x91d5e3,2);blue.position.set(12,9,-15);scene.add(blue);
  const orbitBackdrop=buildOrbitalBackdrop(scene);
  const animateLandscape=landscape(scene);
  const world=new T.Group();scene.add(world);const{box,cyl,ball,rod}=kit(world),stone=material(0x435953,.83),rim=material(0x233c3b,.35,.65),gold=material(0x92794e,.32,.7),grass=material(0x365d49),bark=material(0x4c4940),leaf=material(0x55836a),pearl=material(0x96aca2),mintGlow=new T.MeshBasicMaterial({color:0x8ecdc1}),waterMat=animateLandscape.waterMaterial;
  cyl(0,-.55,0,12,.8,rim);cyl(0,-.11,0,11.85,.08,gold);cyl(0,-.06,0,11.72,.08,stone);cyl(0,-.01,0,3.6,.045,waterMat);
  for(const radius of[3.7,10.9,11.5]){const ring=new T.Mesh(new T.TorusGeometry(radius,.035,8,180),radius===10.9?mintGlow:gold);ring.rotation.x=Math.PI/2;ring.position.y=.03;world.add(ring);}
  // Inlaid radial paths, luminous seams and island planters.
  for(let i=0;i<16;i++){const a=i/16*Math.PI*2;rod(new T.Vector3(Math.sin(a)*3.9,.01,Math.cos(a)*3.9),new T.Vector3(Math.sin(a)*10.8,.01,Math.cos(a)*10.8),.009,gold);}
  let seed=61;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
  const canopyMotion:{mesh:T.Mesh;x:number;z:number;phase:number}[]=[];
  const tree=(x:number,z:number,scale=1)=>{cyl(x,.23,z,1.5*scale,.46,rim);cyl(x,.49,z,1.43*scale,.06,grass);cyl(x,1.65*scale,z,.16*scale,2.9*scale,bark,.09*scale,10);for(let j=0;j<6;j++){const a=j*2.399,p=new T.Vector3(x+Math.sin(a)*.9*scale,(2.5+rand())*scale,z+Math.cos(a)*.9*scale);rod(new T.Vector3(x,1.8*scale,z),p,.05*scale,bark);const crown=ball(p.x,p.y,p.z,.92*scale,leaf);crown.scale.y=.7;canopyMotion.push({mesh:crown,x:p.x,z:p.z,phase:x+z+j});}for(let j=0;j<8;j++){const a=j*2.4;const b=ball(x+Math.sin(a)*scale,.66,z+Math.cos(a)*scale,.23,grass);b.scale.set(1,1.9,.8);}};
  for(const[x,z,s]of[[-4,-1,1.1],[4.3,1,1],[-8.2,1.8,.8],[4.9,-8.5,.9],[-5,-8.2,.9]])tree(x,z,s);
  const fountain=buildGardenFountain(world,waterMat);
  // Hydroponic terraces, seating, a transparent biodome frame.
  for(const sign of[-1,1])for(let row=0;row<3;row++){box(sign*8,.4+row*.3,-7.5+row*.65,2.4,.18,.4,pearl);for(let j=0;j<8;j++){const b=ball(sign*8+(j-3.5)*.26,.65+row*.3,-7.5+row*.65,.15,leaf);b.scale.y=1.7;}}
  for(const[x,z,a]of[[-5,4,.5],[5,4,-.5]]){const seat=box(x,.65,z,2.3,.2,.7,pearl);seat.rotation.y=a;for(const dx of[-.8,.8])box(x+dx,.32,z,.12,.64,.5,gold);}
  for(let i=0;i<7;i++){const a=i*Math.PI/6,points:T.Vector3[]=[];for(let j=0;j<=60;j++){const t=j/60*Math.PI;points.push(new T.Vector3(Math.cos(t)*13*Math.cos(a),Math.sin(t)*11,Math.cos(t)*13*Math.sin(a)));}world.add(new T.Line(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color:0x487d78,transparent:true,opacity:.35})));}
  let shrines=buildShrines(scene,portals),pickables=shrines.pickables;
  let portalLabels=buildPortalLabels(mount,portals,id=>latest.current.onPortal(id));
  const particles=[];for(let i=0;i<170;i++)particles.push((rand()-.5)*24,rand()*6+.3,(rand()-.5)*22);const pg=new T.BufferGeometry();pg.setAttribute('position',new T.Float32BufferAttribute(particles,3));const motes=new T.Points(pg,new T.PointsMaterial({color:0xefcf96,size:.032,transparent:true,opacity:.65,depthWrite:false,blending:T.AdditiveBlending}));scene.add(motes);
  // All connected visitors share geometry: 18 draws for up to 200 original foxes.
  const avatarRoot=new T.Group();scene.add(avatarRoot);
  const flockRoot=new T.Group();scene.add(flockRoot);const capacity=200;
  const coat=material(0xffffff,.85),cream=material(0xffebce,.94),ink=material(0x152d31),collarMat=material(0x88e3d7,.3,.55);
  const parts:{mesh:T.InstancedMesh;local:T.Matrix4;tint:boolean}[]=[];
  const part=(geo:T.BufferGeometry,mat:T.Material,x:number,y:number,z:number,sx=1,sy=1,sz=1,rz=0,ry=0,tint=false)=>{const mesh=new T.InstancedMesh(geo,mat,capacity),o=new T.Object3D();o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.rotation.set(0,ry,rz);o.updateMatrix();mesh.count=0;mesh.frustumCulled=false;mesh.instanceMatrix.setUsage(T.DynamicDrawUsage);flockRoot.add(mesh);parts.push({mesh,local:o.matrix.clone(),tint});};
  const sphere=new T.SphereGeometry(1,10,7),cone=new T.ConeGeometry(1,1,4);
  part(sphere,coat,0,.7,0,.34,.5,.45,0,0,true);part(sphere,cream,0,.84,.27,.22,.32,.2);
  part(sphere,coat,0,1.32,.13,.43,.37,.39,0,0,true);part(sphere,cream,0,1.18,.48,.28,.15,.23);part(sphere,ink,0,1.22,.68,.065,.065,.065);
  for(const sign of[-1,1]){part(cone,coat,sign*.28,1.75,.1,.2,.55,.2,-sign*.2,0,true);part(cone,cream,sign*.28,1.77,.18,.115,.33,.09,-sign*.2);part(sphere,ink,sign*.2,1.36,.48,.05,.05,.05);part(sphere,ink,sign*.21,.14,.1,.14,.12,.2);part(sphere,coat,sign*.35,.68,.07,.1,.26,.1,sign*.18,0,true);}
  part(sphere,coat,.18,.54,-.64,.26,.25,.62,0,-.35,true);part(sphere,cream,.36,.58,-1.09,.22,.22,.24);part(new T.CylinderGeometry(.3,.3,.07,10),collarMat,0,1.03,.12);
  type Guest={person:Person;position:T.Vector3;target:T.Vector3;yaw:number;sampleAt:number;duration:number;origin:T.Vector3;progress:number;gait:number;speed:number};let guests:Guest[]=[];const guestCache=new Map<string,Guest>(),guestLabels:T.Sprite[]=[];
  for(let i=0;i<6;i++){const label=textSprite('','#dfefe6',2.5);label.visible=false;scene.add(label);guestLabels.push(label);}
  const beaconGeometry=new T.SphereGeometry(1,8,6),beaconMaterial=new T.MeshBasicMaterial({color:0xa8ebe0,transparent:true,opacity:.82,depthTest:false,depthWrite:false});const beacons=new T.InstancedMesh(beaconGeometry,beaconMaterial,capacity);beacons.count=0;beacons.frustumCulled=false;beacons.instanceMatrix.setUsage(T.DynamicDrawUsage);beacons.renderOrder=10;scene.add(beacons);
  let mine=fox('amber');mine.scale.setScalar(.85);mine.position.set(0,.06,5);avatarRoot.add(mine);let mineColor='amber',mineForm='',mineAccessory:FoxAccessory='none',lastPeople:Person[]|null=null,lastView='',spawned=false,entering=false,travel=0,lastFocus='';
  const selfLabel=textSprite('YOU','#f4dec0',.8);selfLabel.position.y=2.1;scene.add(selfLabel);
  const selfRing=new T.Mesh(new T.RingGeometry(.58,.63,48),new T.MeshBasicMaterial({color:0xd7bb7d,transparent:true,opacity:.8,side:T.DoubleSide,depthWrite:false}));selfRing.rotation.x=-Math.PI/2;scene.add(selfRing);
  const destination=new T.Vector3(0,.06,5),velocity=new T.Vector3();let route:GardenPoint[]=[],manualWasActive=false,gait=0,stepDistance=0,footIndex=0;const groundHeight=(x:number,z:number)=>portals.some(p=>Math.hypot(x-p.x,z-p.z)<3.1)?.44:Math.hypot(x,z)<11.8?.045:-.11;
  const targetMarker=new T.Group(),targetMaterial=new T.MeshBasicMaterial({color:0xe8c993,transparent:true,opacity:.8,side:T.DoubleSide,depthWrite:false});const targetRing=new T.Mesh(new T.RingGeometry(.32,.39,40),targetMaterial);targetRing.rotation.x=-Math.PI/2;targetMarker.add(targetRing);const targetDot=new T.Mesh(new T.CircleGeometry(.045,12),targetMaterial);targetDot.rotation.x=-Math.PI/2;targetMarker.add(targetDot);targetMarker.visible=false;scene.add(targetMarker);
  const footGeometry=new T.CircleGeometry(.09,10),footprints=Array.from({length:18},()=>{const m=new T.Mesh(footGeometry,new T.MeshBasicMaterial({color:0xc8d9be,transparent:true,opacity:0,side:T.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.scale.y=1.6;m.userData.life=0;scene.add(m);return m;});
  let feet:T.Object3D[]=[],arms:T.Object3D[]=[];const findLimbs=()=>{feet=mine.children.filter(c=>c.name==='fox-foot');arms=mine.children.filter(c=>c.name==='fox-arm');};findLimbs();
  const keys=new Set<string>(),ray=new T.Raycaster(),mouse=new T.Vector2(),ground=new T.Plane(new T.Vector3(0,1,0),0);let down=[0,0],portalHovered=false,pointerHeld=false,interactionUntil=0;
  const pointerMove=(e:PointerEvent)=>{const b=r.domElement.getBoundingClientRect();mouse.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(mouse,camera);portalHovered=ray.intersectObjects(pickables,false).length>0;};
  const pointerLeave=()=>{portalHovered=false;};
  const pointerRelease=()=>{pointerHeld=false;interactionUntil=performance.now()+2000;};
  r.domElement.addEventListener('pointermove',pointerMove);r.domElement.addEventListener('pointerleave',pointerLeave);window.addEventListener('pointerup',pointerRelease);window.addEventListener('pointercancel',pointerRelease);
  const guardian=(root:T.Group)=>{const g=new T.Group(),q=kit(g),armour=material(0x315762,.25,.7),brass=material(0xcfb26c,.3,.7),light=new T.MeshBasicMaterial({color:0xb1f4e6});g.name='guardian';for(const sign of[-1,1]){const shoulder=q.ball(sign*.42,1.02,.04,.23,armour);shoulder.scale.set(1.4,.75,1);q.box(sign*.21,.35,.11,.28,.35,.28,armour);const spike=new T.Mesh(new T.ConeGeometry(.065,.3,4),brass);spike.position.set(sign*.46,1.3,.02);g.add(spike);}q.box(0,.79,.41,.47,.46,.09,armour);q.box(0,.83,.465,.2,.18,.025,light);q.rod(new T.Vector3(.65,.2,.03),new T.Vector3(.65,2.2,.03),.035,brass);for(const x of[-.18,0,.18]){q.rod(new T.Vector3(.65,1.93,.03),new T.Vector3(.65+x,2.16,.03),.025,brass);q.rod(new T.Vector3(.65+x,2.16,.03),new T.Vector3(.65+x,2.43,.03),.018,light);}root.add(g);};
  const keyDown=(e:KeyboardEvent)=>{if(e.target instanceof HTMLElement&&e.target.closest('input,textarea,select,[contenteditable="true"],[role="dialog"]'))return;if(e.key==='Enter'&&!document.querySelector('[role="dialog"]')&&!(e.target instanceof HTMLElement&&e.target.closest('button,a'))&&Math.hypot(mine.position.x-discoveriesCourt.x,mine.position.z-discoveriesCourt.z)<4.6){e.preventDefault();latest.current.onLeaderboard();return;}if(['w','a','s','d','W','A','S','D','ArrowUp','ArrowLeft','ArrowDown','ArrowRight','Shift'].includes(e.key)){keys.add(e.key.toLowerCase());e.preventDefault();}};const keyUp=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());const blur=()=>{pointerHeld=false;portalHovered=false;keys.clear();velocity.set(0,0,0);route=[];destination.copy(mine.position);targetMarker.visible=false;};window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',blur);const visibility=()=>{recycleLast=performance.now();if(document.hidden)blur();};document.addEventListener('visibilitychange',visibility);
  const pointerDown=(e:PointerEvent)=>{pointerHeld=true;down=[e.clientX,e.clientY];};const click=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const b=r.domElement.getBoundingClientRect();mouse.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(mouse,camera);const hits=ray.intersectObjects([...pickables,...animateLandscape.leaderboardPickables,...parts.map(p=>p.mesh),beacons,...guestLabels.filter(l=>l.visible)],false);const picked=hits.find(hit=>hit.object===beacons||hit.object.userData.guestId)||hits[0];if(picked){const o=picked.object;if(o.userData.guestId){const guest=guestCache.get(o.userData.guestId);if(guest){latest.current.onPerson(guest.person);return;}}if(o.userData.leaderboard){latest.current.onLeaderboard();return;}if(o.userData.portal){latest.current.onPortal(o.userData.portal);return;}const index=picked.instanceId;if(index!==undefined&&guests[index]){latest.current.onPerson(guests[index].person);return;}}const hit=new T.Vector3();if(ray.ray.intersectPlane(ground,hit)&&hit.x>=-90&&hit.x<=90&&hit.z>=-70&&hit.z<=80){const point=resolveGardenPosition({x:hit.x,z:hit.z});route=gardenPath(mine.position,point);destination.set(point.x,.06,point.z);targetMarker.position.set(point.x,groundHeight(point.x,point.z)+.03,point.z);targetMarker.visible=route.length>0;}};r.domElement.addEventListener('pointerdown',pointerDown);r.domElement.addEventListener('pointerup',click);
  const resize=()=>{r.setSize(mount.clientWidth,mount.clientHeight);camera.aspect=mount.clientWidth/mount.clientHeight;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(mount);resize();let frame=0,last=0,report=0,visible=true;const io=new IntersectionObserver(e=>{visible=e[0].isIntersecting;});io.observe(mount);
  const avatarMatrix=new T.Matrix4(),q=new T.Quaternion(),partMatrix=new T.Matrix4(),scale=new T.Vector3(.85,.85,.85),up=new T.Vector3(0,1,0),marker=new T.Object3D(),jointOffset=new T.Matrix4();
  function animate(t:number){frame=requestAnimationFrame(animate);if(document.hidden||!visible){recycleLast=t;return;}if(t-last<32)return;const recycleSeconds=Math.max(0,(t-recycleLast)/1000);recycleLast=t;const dt=Math.min(.06,(t-last)/1000);last=t;const s=latest.current.state;if(s.view!==lastView){lastView=s.view;if(s.view==='ground'){camera.position.copy(mine.position).add(new T.Vector3(0,6.3,13.5));controls.target.copy(mine.position).add(new T.Vector3(0,1,0));controls.minDistance=7;controls.maxDistance=42;}else if(s.view==='visitor'){controls.minDistance=3;controls.maxDistance=35;}else if(s.view==='above'){camera.position.set(0,155,42);controls.target.set(0,0,0);controls.minDistance=15;controls.maxDistance=225;}else if(s.view==='discoveries'){camera.position.set(discoveriesCourt.x+.8,3.5,discoveriesCourt.z-7);controls.target.set(discoveriesCourt.x,1.7,discoveriesCourt.z);controls.minDistance=2;controls.maxDistance=18;}else if(s.view==='waterfall'){camera.position.set(0,27,18);controls.target.set(0,7,-49);controls.minDistance=5;controls.maxDistance=90;}else{camera.position.set(52,50,86);controls.target.set(0,3,-18);controls.minDistance=8;controls.maxDistance=180;}}
   if(s.me&&!spawned){spawned=true;const n=parseInt(s.me.id.slice(0,4),16),a=(n/65535-.5)*.9;mine.position.set(Math.sin(a)*6.3,.06,Math.cos(a)*6.3);destination.copy(mine.position);velocity.set(0,0,0);route=[];}
   const color=s.me?.color||'amber';if(color!==mineColor||s.form!==mineForm||s.accessory!==mineAccessory){mineColor=color;mineForm=s.form;mineAccessory=s.accessory;const pos=mine.position.clone(),yaw=mine.rotation.y;avatarRoot.remove(mine);disposeScene(mine);mine=fox(color,s.accessory);mine.scale.setScalar(.85);mine.position.copy(pos);mine.rotation.y=yaw;if(s.form==='guardian')guardian(mine);avatarRoot.add(mine);findLimbs();}
   const signature=s.people;if(lastPeople!==signature){lastPeople=signature;const remote=s.people.filter(p=>p.id!==s.you).slice(0,capacity),ids=new Set(remote.map(p=>p.id));for(const id of guestCache.keys())if(!ids.has(id))guestCache.delete(id);guests=remote.map(p=>{let g=guestCache.get(p.id);if(!g){const at=new T.Vector3(p.x||0,groundHeight(p.x||0,p.z||0)+.015,p.z||0);g={person:p,position:at.clone(),target:at.clone(),origin:at.clone(),yaw:0,sampleAt:t,duration:0,progress:1,gait:0,speed:0};guestCache.set(p.id,g);}g.person=p;const next=new T.Vector3(p.x||0,groundHeight(p.x||0,p.z||0)+.015,p.z||0);if(next.distanceToSquared(g.target)>.0001){g.origin.copy(g.position);g.target.copy(next);g.duration=Math.max(.3,Math.min(4.5,(t-g.sampleAt)/1000*.9));g.progress=0;}g.sampleAt=t;return g;});beacons.count=guests.length;for(const part of parts){part.mesh.count=guests.length;if(part.tint){guests.forEach((g,i)=>part.mesh.setColorAt(i,new T.Color(foxColors[g.person.color]||foxColors.amber)));if(part.mesh.instanceColor)part.mesh.instanceColor.needsUpdate=true;}}}
   let dx=s.move.x,dz=s.move.z;if(keys.has('w')||keys.has('arrowup'))dz-=1;if(keys.has('s')||keys.has('arrowdown'))dz+=1;if(keys.has('a')||keys.has('arrowleft'))dx-=1;if(keys.has('d')||keys.has('arrowright'))dx+=1;
   const blocked=!!document.querySelector('[role="dialog"]');if(blocked){dx=0;dz=0;keys.clear();velocity.set(0,0,0);route=[];targetMarker.visible=false;}const manual=!!(dx||dz),before=mine.position.clone(),desired=new T.Vector3(),speed=keys.has('shift')||s.running?15:5.6;
   if(manual){route=[];targetMarker.visible=false;const forward=new T.Vector3();camera.getWorldDirection(forward);forward.y=0;forward.normalize();const right=new T.Vector3(-forward.z,0,forward.x);desired.copy(right.multiplyScalar(dx).addScaledVector(forward,-dz).normalize()).multiplyScalar(speed);destination.copy(mine.position);}
   else if(manualWasActive){route=[];destination.copy(mine.position);}
   else if(route.length){let d=new T.Vector3(route[0].x-mine.position.x,0,route[0].z-mine.position.z);if(d.length()<.2){route.shift();if(route.length)d.set(route[0].x-mine.position.x,0,route[0].z-mine.position.z);}if(route.length){const stopping=route.length===1?Math.min(speed,Math.sqrt(2*40*d.length())):speed;desired.copy(d.normalize()).multiplyScalar(stopping);}else targetMarker.visible=false;}
   if(manualWasActive&&!manual)velocity.set(0,0,0);const reversing=desired.dot(velocity)<0;const acceleration=reversing?180:desired.lengthSq()>.01?85:140,delta=desired.sub(velocity);if(delta.length()>acceleration*dt)delta.setLength(acceleration*dt);velocity.add(delta);manualWasActive=manual;if(velocity.length()<.025)velocity.set(0,0,0);
   const displacement=velocity.clone().multiplyScalar(dt),substeps=Math.max(1,Math.ceil(displacement.length()/.2));for(let step=0;step<substeps;step++){const resolved=resolveGardenPosition({x:mine.position.x+displacement.x/substeps,z:mine.position.z+displacement.z/substeps});mine.position.x=resolved.x;mine.position.z=resolved.z;}
   const moved=mine.position.distanceTo(before),moving=moved>.0005;travel+=moved;const sprint=speed>10;gait+=moved*(sprint?5.3:7.5);stepDistance+=moved;
   if(moving){const heading=Math.atan2(mine.position.x-before.x,mine.position.z-before.z),difference=Math.atan2(Math.sin(heading-mine.rotation.y),Math.cos(heading-mine.rotation.y));mine.rotation.y+=difference*(1-Math.exp(-dt*15));}
   mine.position.y=groundHeight(mine.position.x,mine.position.z)+.015+(moving?Math.abs(Math.sin(gait))*(sprint?.075:.035):0);mine.rotation.z=moving?Math.sin(gait)*(sprint?.04:.025):mine.rotation.z*Math.exp(-dt*15);mine.rotation.x=T.MathUtils.damp(mine.rotation.x,moving&&sprint?.11:0,14,dt);
   feet.forEach((foot,i)=>{foot.position.y=.16+(moving?Math.max(0,Math.sin(gait+i*Math.PI))*(sprint?.22:.15):0);foot.position.z=.06+(moving?Math.cos(gait+i*Math.PI)*(sprint?.2:.1):0);});arms.forEach((arm,i)=>{arm.rotation.x=moving?Math.sin(gait+i*Math.PI)*(sprint?.55:.28):0;});
   if(moving&&stepDistance>.58){stepDistance=0;const footprint=footprints[footIndex++%footprints.length],side=footIndex%2?-.18:.18;footprint.position.set(mine.position.x+Math.cos(mine.rotation.y)*side,groundHeight(mine.position.x,mine.position.z)+.004,mine.position.z-Math.sin(mine.rotation.y)*side);footprint.rotation.z=-mine.rotation.y;footprint.userData.life=1;}
   footprints.forEach(footprint=>{footprint.userData.life=Math.max(0,footprint.userData.life-dt*.52);(footprint.material as T.MeshBasicMaterial).opacity=footprint.userData.life*.22;});
   if(targetMarker.visible){const remaining=mine.position.distanceTo(destination);targetMarker.scale.setScalar(.94+Math.sin(t*.004)*.06);targetMaterial.opacity=remaining<1?.45:.8;}
   selfLabel.position.copy(mine.position).add(new T.Vector3(0,2.05,0));selfLabel.visible=s.view!=='above';selfRing.position.set(mine.position.x,groundHeight(mine.position.x,mine.position.z)+.008,mine.position.z);selfRing.scale.setScalar(1+(s.motion?Math.sin(t*.002)*.035:0));
   controls.enableRotate=!manual;controls.enableDamping=!manual;
   if(t-report>500){report=t;animateLandscape.updateCounts(s.community);latest.current.onPosition(mine.position.x,mine.position.z);let nearestPortal=portals[0],portalDistance=Infinity;for(const p of portals){const d=Math.hypot(p.x-mine.position.x,p.z-mine.position.z);if(d<portalDistance){nearestPortal=p;portalDistance=d;}}if(nearestPortal)window.dispatchEvent(new CustomEvent('pe-portal-proximity',{detail:{worldId:nearestPortal.id,distance:portalDistance}}));}
   guests.forEach((g,i)=>{const previousPosition=g.position.clone();g.progress=Math.min(1,g.progress+dt/Math.max(.1,g.duration));g.position.lerpVectors(g.origin,g.target,g.progress);const diff=g.position.clone().sub(previousPosition);g.speed=diff.length()/Math.max(.001,dt);if(diff.lengthSq()>.000001){const angle=Math.atan2(diff.x,diff.z)-g.yaw;g.yaw+=Math.atan2(Math.sin(angle),Math.cos(angle))*(1-Math.exp(-dt*13));g.gait+=diff.length()*(g.speed>9?5.3:7.5);}const active=g.speed>.1;const rendered=g.position.clone();rendered.y=groundHeight(rendered.x,rendered.z)+.015+(active?Math.abs(Math.sin(g.gait))*.045:0);q.setFromAxisAngle(up,g.yaw);avatarMatrix.compose(rendered,q,scale);parts.forEach((part,index)=>{partMatrix.copy(part.local);if(active&&(index===8||index===13)){const step=g.gait+(index===13?Math.PI:0);partMatrix.elements[13]+=Math.max(0,Math.sin(step))*.17;partMatrix.elements[14]+=Math.cos(step)*.14;}if(active&&(index===9||index===14)){jointOffset.makeRotationX(Math.sin(g.gait+(index===14?Math.PI:0))*.35);partMatrix.multiply(jointOffset);}partMatrix.premultiply(avatarMatrix);part.mesh.setMatrixAt(i,partMatrix);});marker.position.copy(rendered).add(new T.Vector3(0,2.2,0));const radius=Math.max(.065,Math.min(.7,camera.position.distanceTo(marker.position)*.0035));marker.scale.setScalar(radius*(s.focusPerson===g.person.id?1.5:1));marker.updateMatrix();beacons.setMatrixAt(i,marker.matrix);});beacons.instanceMatrix.needsUpdate=true;beacons.boundingSphere=null;parts.forEach(p=>{p.mesh.instanceMatrix.needsUpdate=true;p.mesh.boundingSphere=null;});
   // Names only appear nearby; the complete flock stays rendered at every distance.
   const nearest=guests.map(g=>({g,d:g.position.distanceTo(camera.position)})).filter(v=>v.d<24||v.g.person.id===s.focusPerson).sort((a,b)=>a.g.person.id===s.focusPerson?-1:b.g.person.id===s.focusPerson?1:a.d-b.d).slice(0,6);guestLabels.forEach((label,i)=>{const guest=nearest[i]?.g;label.visible=!!guest;if(!guest){label.userData.guestId='';return;}label.userData.guestId=guest.person.id;label.material.depthTest=false;label.renderOrder=11;const labelWidth=Math.max(2.5,Math.min(6.5,guest.position.distanceTo(camera.position)*.06));label.scale.set(labelWidth,labelWidth*.2,1);label.position.copy(guest.position).add(new T.Vector3(0,1.98,0));if(label.userData.name!==guest.person.alias){const canvas=label.material.map!.image as HTMLCanvasElement,ctx=canvas.getContext('2d')!;ctx.clearRect(0,0,640,128);ctx.fillStyle='rgba(8,24,25,.86)';ctx.beginPath();ctx.roundRect(8,16,624,96,28);ctx.fill();ctx.fillStyle='#dfefe6';ctx.font='500 34px system-ui';ctx.textAlign='center';ctx.fillText(guest.person.alias,320,78);label.material.map!.needsUpdate=true;label.userData.name=guest.person.alias;}});
   if(s.view==='visitor'&&s.focusPerson){const selectedGuest=guestCache.get(s.focusPerson);if(selectedGuest){if(lastFocus!==s.focusPerson){lastFocus=s.focusPerson;camera.position.copy(selectedGuest.position).add(new T.Vector3(4,3.5,7));controls.target.copy(selectedGuest.position).add(new T.Vector3(0,1,0));}else{const nextTarget=selectedGuest.position.clone().add(new T.Vector3(0,1,0));const shift=nextTarget.sub(controls.target).multiplyScalar(1-Math.exp(-dt*5));camera.position.add(shift);controls.target.add(shift);}}}else lastFocus='';
   if(s.view==='ground'){camera.position.add(mine.position.clone().sub(before));controls.target.lerp(mine.position.clone().add(new T.Vector3(0,1,0)),.15);}
   // Never exchange a doorway somebody is approaching, reading or selecting.
   const recycling=portalRecycleStep(recycleElapsed,recycleSeconds,true,blocked||entering||moving||route.length>0||pointerHeld||portalHovered||portalLabels.isEngaged()||t<interactionUntil||portals.some(p=>Math.hypot(p.x-mine.position.x,p.z-mine.position.z)<12));
   recycleElapsed=recycling.elapsed;
   if(recycling.recycle&&shrinePortals.length>portals.length){
    portalOffset=(portalOffset+portals.length)%shrinePortals.length;
    portalLabels.dispose();scene.remove(shrines.root);shrines.dispose();disposeScene(shrines.root);
    portals=shrineBatch(portalOffset);shrines=buildShrines(scene,portals);pickables=shrines.pickables;
    portalLabels=buildPortalLabels(mount,portals,id=>latest.current.onPortal(id));revealStarted=t;
   }
   const reveal=s.motion?Math.min(1,(t-revealStarted)/650):1;shrines.setReveal(reveal);portalLabels.setReveal(reveal);
   if(!entering&&travel>1&&moving){const near=portals.find(p=>Math.hypot(p.x-mine.position.x,p.z-mine.position.z)<.85);if(near){entering=true;latest.current.onPortal(near.id);}}animateLandscape(t,s.motion);fountain.animate(t,s.motion);orbitBackdrop.animate(t,s.motion,camera);
   const daylight=orbitBackdrop.daylight;hemisphere.intensity=1.35+daylight*.7;sun.intensity=1.45+daylight*2.2;blue.intensity=1.75-daylight*.85;sun.position.copy(orbitBackdrop.sunDirection).multiplyScalar(72);sun.position.y=Math.max(18,sun.position.y);sun.color.setRGB(1,.72+daylight*.15,.49+daylight*.2);(scene.fog as T.FogExp2).color.setRGB(.012+daylight*.018,.027+daylight*.04,.043+daylight*.049);animateLandscape.setDaylight(daylight,orbitBackdrop.sunDirection);
   if(s.motion){shrines.animate(t,true);canopyMotion.forEach(c=>{c.mesh.position.x=c.x+Math.sin(t*.00065+c.phase)*.025;c.mesh.position.z=c.z+Math.cos(t*.0005+c.phase)*.02;});motes.rotation.y=t*.000008;world.children.forEach(o=>{if(o.userData.icon){o.userData.icon.rotation.y=t*.0003;o.userData.icon.position.y=(o.userData.iconBase||1.75)+Math.sin(t*.001)*.08;}});if(mine.userData.tail)mine.userData.tail.rotation.y=Math.sin(t*.0018)*.16;}controls.update();portalLabels.update(t,camera,mine.position,s.view==='ground');r.render(scene,camera);
  }frame=requestAnimationFrame(animate);
  return()=>{portalLabels.dispose();animateLandscape.dispose();shrines.dispose();cancelAnimationFrame(frame);ro.disconnect();io.disconnect();window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);r.domElement.removeEventListener('pointermove',pointerMove);r.domElement.removeEventListener('pointerleave',pointerLeave);window.removeEventListener('pointerup',pointerRelease);window.removeEventListener('pointercancel',pointerRelease);r.domElement.removeEventListener('pointerdown',pointerDown);r.domElement.removeEventListener('pointerup',click);controls.dispose();disposeScene(scene);r.dispose();r.domElement.remove();};
 },[]);
 return <div className="garden-canvas" ref={host}>{failed&&<div className="scene-fallback"><h2>The garden needs WebGL.</h2><p>Use Find a world to explore without the 3D view.</p></div>}</div>;
}
