'use client';
import{useEffect,useRef,useState}from'react';import{ArrowRight,ArrowUpRight,Orbit,Users,Map,Heart,X,Pause,Play,Send,Settings2,Footprints,Waves,Shield,ChevronUp,ChevronDown,ChevronLeft,ChevronRight,Wind,Trophy}from'lucide-react';
import GardenScene,{portals}from'./garden-scene';import{api,track,usePulse,type Person}from'./activity';import{projects,worldHref}from'./projects';import{About,Membership}from'./components/about';import{Capture,CaptureControls}from'./components/capture';import{WorldDock}from'./components/world-dock';import './garden-world.css';import './components/live-moments.css';
import {travelTo} from './components/portal-travel';
import {discoveriesCourt} from './garden-architecture';
import type {FoxAccessory} from './three-kit';
type Feed={id:string;alias:string;kind:string;text:string;created:number};
const greetings=['Hello, explorers!','I found something wonderful.','Try the telescope.','Who wants to race?','The lightning lab is incredible.','Come explore the airport.'];
const emotes=[{symbol:'👋',label:'Wave',text:greetings[0]},{symbol:'✨',label:'Celebrate',text:greetings[1]},{symbol:'🔭',label:'Explore together',text:greetings[2]},{symbol:'🏁',label:'Race',text:greetings[3]}];
export default function Garden(){
 const{pulse,error,favorite}=usePulse('garden'),[people,setPeople]=useState<Person[]>([]),[total,setTotal]=useState(0),[feed,setFeed]=useState<Feed[]>([]),[connected,setConnected]=useState(false),[view,setView]=useState('ground'),[form,setForm]=useState<'fox'|'guardian'>('fox'),[accessory,setAccessory]=useState<FoxAccessory>('none'),[move,setMove]=useState({x:0,z:0}),[running,setRunning]=useState(false),[focusPerson,setFocusPerson]=useState<string|null>(null),[courtNear,setCourtNear]=useState(false),[moments,setMoments]=useState(false),[motion,setMotion]=useState(true),[person,setPerson]=useState<Person|null>(null),[modal,setModal]=useState(''),[toast,setToast]=useState(''),[profile,setProfile]=useState(''),[color,setColor]=useState('amber'),[greeting,setGreeting]=useState(greetings[0]),[busy,setBusy]=useState(false);const pos=useRef({x:0,z:5}),notice=useRef<ReturnType<typeof setTimeout>|null>(null),me=pulse?.me||null;
 function notify(text:string){setToast(text);if(notice.current)clearTimeout(notice.current);notice.current=setTimeout(()=>setToast(''),4500);}
 useEffect(()=>{if(new URLSearchParams(location.search).has('walk'))setView('ground');try{const saved=localStorage.getItem('pe-fox-accessory');if(['none','hat','mustache','boots'].includes(saved||''))setAccessory(saved as FoxAccessory);}catch{}setMotion(!matchMedia('(prefers-reduced-motion: reduce)').matches);return()=>{if(notice.current)clearTimeout(notice.current);};},[]);
 useEffect(()=>{if(!me)return;setColor(me.color);setProfile(me.link);},[me?.id]);
 useEffect(()=>{if(!me)return;let live=true,inFlight=false;const update=async()=>{if(document.hidden||inFlight)return;inFlight=true;try{const data=await api<{people:Person[];total:number;feed:Feed[]}>('garden',pos.current);if(live){setPeople(data.people);setTotal(data.total);setFeed(data.feed);setConnected(true);}}catch{if(live){setConnected(false);setPeople([]);}}finally{inFlight=false;}};void update();const id=setInterval(update,5000);document.addEventListener('visibilitychange',update);return()=>{live=false;clearInterval(id);document.removeEventListener('visibilitychange',update);};},[me?.id]);
 useEffect(()=>{if(focusPerson&&connected&&!people.some(p=>p.id===focusPerson)){setFocusPerson(null);setView('ground');notify('That explorer has stepped away.');}},[people,connected,focusPerson]);
 useEffect(()=>{const reset=()=>setMove({x:0,z:0});window.addEventListener('blur',reset);return()=>window.removeEventListener('blur',reset);},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setModal('');setPerson(null);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 async function sendGreeting(text:string){if(busy||!connected)return;setBusy(true);try{await api('signal',{text});notify('Emote sent to the garden.');const data=await api<{people:Person[];total:number;feed:Feed[]}>('garden',pos.current);setFeed(data.feed);setPeople(data.people);setTotal(data.total);}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
 async function fave(id:string){try{const added=await favorite(id);notify(added?'Saved to your worlds.':'Removed from your favorites.');}catch(e){notify((e as Error).message);}}
 const worldIds=new Set(projects.filter(p=>p.featured!==false&&p.category!=='Tools').map(p=>p.id));
 const community={views:pulse&&!error?pulse.ranking.filter(r=>worldIds.has(r.project)).reduce((n,r)=>n+r.visits,0):null,favorites:pulse&&!error?pulse.favorites.filter(r=>worldIds.has(r.project)).reduce((n,r)=>n+r.favorites,0):null};
 return <main className={`garden-page living-garden ${view==='ground'?'is-walking':''}`}><a className="skip-link" href="/telescope">Enter the telescope world</a><section className="garden-stage" id="garden"><GardenScene state={{people:connected?people:[],you:me?.id||'',me,view,motion,form,accessory,move,running,focusPerson,community}} onPosition={(x,z)=>{pos.current={x,z};setCourtNear(Math.hypot(x-discoveriesCourt.x,z-discoveriesCourt.z)<4.6);}} onPortal={id=>{const p=projects.find(p=>p.id===id);if(p?.url){track('project_open',id);travelTo(worldHref(p));}}} onPerson={setPerson} onLeaderboard={()=>travelTo('/leaderboard')}/>

 <aside className="garden-presence"><div className="presence-count"><span className={`live-dot ${connected?'':'offline'}`}/><strong>{connected?total:'—'}</strong><span>{connected?'live in the garden':'Connecting…'}</span><Users size={16}/></div><p>{connected?(total===1?'The first fox is you. A good place to begin.':'Real visitors, wandering together.'):'You can explore while the garden connects.'}</p><div className="visitor-foxes">{people.slice(0,6).map(p=><button key={p.id} onClick={()=>setPerson(p)} title={p.alias} aria-label={`Meet ${p.alias}`} style={{'--fox':({amber:'#d89763',mint:'#84bdae',silver:'#b8c7ce',rose:'#d599a9'}as Record<string,string>)[p.color]} as React.CSSProperties}><span className="fox-face">●</span>{p.id===me?.id&&<small>YOU</small>}</button>)}</div><button className="text-button" disabled={!connected} onClick={()=>setModal('explorers')} style={{marginBottom:10}}><Users size={12}/>Meet explorers</button><button className="text-button" onClick={()=>setModal('profile')}><Settings2 size={12}/>Your fox & profile</button></aside>
 <aside className={`garden-feed ${moments?'is-open':''}`}><button className="moments-toggle" aria-expanded={moments} onClick={()=>setMoments(!moments)}>Live moments <ChevronUp size={13}/></button><div className="moments-body"><div className="eyebrow">LITTLE MOMENTS, LIVE</div>{feed.length?feed.slice(0,5).map(f=><div className="feed-item" key={f.id}>{f.kind==='favorite'?<Heart size={12}/>:<span className="live-dot"/>}<p><strong>{f.alias}</strong>{f.kind==='favorite'?` saved ${projects.find(p=>p.id===f.text)?.title||'a world'}.`:f.text}</p></div>):<p className="feed-empty">Discoveries and greetings will find their way here.</p>}<div className="garden-emotes" role="group" aria-label="Send an emote">{emotes.map(e=><button key={e.label} disabled={!connected||busy} aria-label={`Send ${e.label.toLowerCase()} to the garden`} title={e.label} onClick={()=>void sendGreeting(e.text)}><span aria-hidden="true">{e.symbol}</span><small>{e.label}</small></button>)}</div><form className="greeting" onSubmit={e=>{e.preventDefault();void sendGreeting(greeting);}}><select aria-label="Choose a greeting" value={greeting} onChange={e=>setGreeting(e.target.value)}>{greetings.map(g=><option key={g}>{g}</option>)}</select><button aria-label="Send greeting to the garden" disabled={!connected||busy}><Send size={14}/></button></form></div></aside>
 <div className="garden-camera" aria-label="Garden camera and movement"><button aria-pressed={view==='orbit'} onClick={()=>setView('orbit')} title="Garden overview"><Orbit size={15}/><span>Garden</span></button><button aria-pressed={view==='ground'} onClick={()=>setView('ground')}><Footprints size={15}/><span>Walk</span></button><button aria-pressed={view==='waterfall'} onClick={()=>setView('waterfall')}><Waves size={15}/><span>Falls</span></button><button aria-pressed={view==='above'} onClick={()=>setView('above')}><Map size={15}/><span>Map</span></button><button aria-pressed={view==='discoveries'} aria-label="Find the Discoveries Court" onClick={()=>setView('discoveries')}><Trophy size={15}/><span>Discoveries</span></button><button aria-label={motion?'Pause ambient motion':'Animate garden'} aria-pressed={!motion} onClick={()=>setMotion(!motion)}>{motion?<Pause size={14}/>:<Play size={14}/>}</button></div>
 {(courtNear||view==='discoveries')&&!modal&&!person&&<a href="/leaderboard" onClick={e=>{e.preventDefault();travelTo('/leaderboard');}} className="garden-court-action"><Trophy size={17}/><span><strong>Discoveries Court</strong><small>{courtNear?'Press Enter or open the leaderboard':'Optional explorer rankings'}</small></span><ArrowRight size={17}/></a>}
 <style>{`.garden-court-action{position:absolute;z-index:4;left:30px;top:108px;display:flex;gap:11px;align-items:center;padding:13px 16px;border:1px solid #b9986059;border-radius:15px;background:#182928e6;color:#f1d6a4;backdrop-filter:blur(12px);box-shadow:0 8px 30px #0004}.garden-court-action strong{display:block;font-size:12px;font-weight:500}.garden-court-action small{display:block;font-size:10px;color:#bdb99e;margin-top:4px}.garden-court-action:focus-visible{outline:2px solid #e5c78f;outline-offset:4px}@media(max-width:600px){.garden-court-action{top:158px;left:16px;padding:11px;width:200px;gap:9px}.garden-court-action strong{font-size:11px}.garden-court-action small{font-size:9px;line-height:1.5}.garden-court-action>svg:last-child{display:none}}`}</style>
 <div className="guardian-controls"><button className={form==='guardian'?'transformed':''} aria-pressed={form==='guardian'} onClick={()=>{setForm(form==='fox'?'guardian':'fox');notify(form==='fox'?'Tidal guardian awakened. A cosmetic form, visible on your screen.':'Back to your curious fox.');}}><Shield size={15}/>{form==='guardian'?'Tidal guardian':'Awaken the guardian'}</button><span>Your form · local cosmetic</span></div>
 {view==='ground'&&<div className="garden-move-pad" aria-label="Walk controls">{[{key:'up',x:0,z:-1,Icon:ChevronUp},{key:'left',x:-1,z:0,Icon:ChevronLeft},{key:'down',x:0,z:1,Icon:ChevronDown},{key:'right',x:1,z:0,Icon:ChevronRight}].map(({key,x,z,Icon})=><button key={key} className={`move-${key}`} aria-label={`Walk ${key}`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setMove({x,z});}} onPointerUp={()=>setMove({x:0,z:0})} onPointerCancel={()=>setMove({x:0,z:0})} onLostPointerCapture={()=>setMove({x:0,z:0})} onKeyDown={e=>{if(e.key===' '||e.key==='Enter')setMove({x,z});}} onKeyUp={()=>setMove({x:0,z:0})}><Icon size={21}/></button>)}<button className="move-sprint" aria-pressed={running} onClick={()=>setRunning(!running)}><Wind size={14}/>{running?'Running':'Run'}</button></div>}
 <div className="garden-walk-hint">{view==='ground'?'WASD / arrows to walk · Shift to run · walk through a portal':view==='visitor'?'Following an explorer · choose Walk to return to your fox':view==='discoveries'?'Tap the trophy or open the leaderboard · choose Walk to return':'Drag to look around · tap a path to walk'}<span>Original worlds by Arnav · built with Codex</span></div></section>
 <WorldDock current="garden" pulse={pulse} onFavorite={fave}/><CaptureControls project="garden" title="The in-between" selector=".garden-canvas canvas"/>
 {modal==='about'&&<About onClose={()=>setModal('')}/>} {modal==='remix'&&<Membership onClose={()=>setModal('')} world="the Pure Exploration garden"/>}{modal==='capture'&&<Capture project="garden" title="The garden of what if · Pure Exploration" selector=".garden-canvas canvas" onClose={()=>setModal('')}/>}
 {modal==='explorers'&&<div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-label="Explorers in the garden" className="studio-modal"><button className="close-modal" aria-label="Close explorers" onClick={()=>setModal('')}><X size={18}/></button><span className="eyebrow">SHARING THIS GARDEN</span><h2>{connected?total:'—'} <em>explorers.</em></h2><p>Choose a fox to meet them or find where they are walking. Positions refresh every five seconds.</p>{!connected?<p>Reconnecting to the garden. You can keep exploring.</p>:people.length?<div style={{display:'grid',gap:8}}>{people.map(p=><button className="outline-button" key={p.id} style={{textAlign:'left',justifyContent:'space-between'}} onClick={()=>{setModal('');setPerson(p);}}><span>{p.alias}{p.id===me?.id?' · you':''}</span><span style={{fontSize:10,opacity:.75}}>{p.id===me?.id?'Your fox':`${Math.round(Math.hypot((p.x||0)-pos.current.x,(p.z||0)-pos.current.z))} m away`} <ArrowRight size={12}/></span></button>)}</div>:<p>Your fox will appear here when the garden connects.</p>}{total>people.length&&<p className="small-copy">Showing the most recently active {people.length} foxes. The current shared scene supports up to 200 visible visitors.</p>}</section></div>}
 {modal==='profile'&&<div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-label="Your garden fox" className="studio-modal"><button className="close-modal" aria-label="Close profile" onClick={()=>setModal('')}><X size={18}/></button><span className="eyebrow">YOUR LITTLE PLACE IN THE GARDEN</span><h2>Hello, <em>{me?.alias||'explorer'}.</em></h2><p>No account needed. Your fox and favorites belong to this browser.</p><label className="field-label">Coat color<select value={color} onChange={e=>setColor(e.target.value)}><option value="amber">Amber</option><option value="mint">Sea glass</option><option value="silver">Moonstone</option><option value="rose">Rose quartz</option></select></label><label className="field-label">Try an accessory<select value={accessory} onChange={e=>{const next=e.target.value as FoxAccessory;setAccessory(next);try{localStorage.setItem('pe-fox-accessory',next);}catch{}}}><option value="none">Just my fox</option><option value="hat">Explorer hat</option><option value="mustache">Curious mustache</option><option value="boots">Sea glass boots</option></select></label><p className="small-copy">Free to try. Your accessory stays on this device.</p><label className="field-label">Public profile · optional<input type="url" value={profile} onChange={e=>setProfile(e.target.value)} placeholder="https://x.com/yourhandle"/></label><p className="small-copy">A public X or GitHub profile. Other visitors can open it by clicking your fox. Profiles are self-declared, not verified.</p><button className="primary" disabled={!me} onClick={async()=>{try{await api('profile',{color,link:profile});window.dispatchEvent(new Event('pe-refresh'));setModal('');notify('Your fox is ready.');}catch(e){notify((e as Error).message);}}}>Save my fox <ArrowRight size={15}/></button></section></div>}
 {person&&<div className="modal-backdrop"><section className="studio-modal visitor-modal" role="dialog" aria-modal="true" aria-label="Garden visitor"><button className="close-modal" aria-label="Close visitor" onClick={()=>setPerson(null)}><X size={18}/></button><span className="eyebrow">A FELLOW EXPLORER</span><h2>{person.alias}</h2><p>{person.id===me?.id?'This is you.':'Sharing a little corner of the universe.'}</p>{person.id!==me?.id&&people.some(p=>p.id===person.id)&&<button className="outline-button" style={{marginBottom:18}} onClick={()=>{setFocusPerson(person.id);setView('visitor');setMove({x:0,z:0});setPerson(null);}}><Map size={15}/>Find this fox in the garden</button>}{person.link?<a className="primary" href={person.link} target="_blank" rel="noopener noreferrer">Visit their public profile <ArrowUpRight size={16}/></a>:<p className="small-copy">This explorer hasn’t shared a profile.</p>}<p className="small-copy">Profile links are shared by visitors and are not verified by Arnav.</p></section></div>}
 {(toast||error)&&<div role="status" className="toast">{toast||'Activity is temporarily unavailable. The worlds are still open.'}</div>}
 </main>;
}
