export type Project={id:string;title:string;subtitle:string;category:'Understand'|'Play'|'Watch'|'Tools';url?:string;art:string;tag:string;status?:string;kind?:'showcase'|'playable';image?:string;trailer?:string;embed?:'frame'|'external';edition?:string;featured?:boolean;tokens?:number;cost?:number};
export const projects:Project[]=[
{id:'telescope',title:'Through the Glass',subtitle:'A midnight study, a telescope, and a little light from very far away. Turn the focus. Follow the rays.',category:'Understand',url:'/telescope',art:'orbit',tag:'OPTICS · INTERACTIVE LAB',image:'/covers/telescope.jpg',trailer:'/trailers/telescope.webm'},
{id:'airport',title:'Airside Intelligence',subtitle:'An airport that thinks with its sensors. Break a signal, dispatch a robot, and see what changes.',category:'Understand',url:'/airport',art:'signal',tag:'IOT · OPERATIONS SIMULATOR',image:'/covers/airport.jpg',trailer:'/trailers/airport.webm'},
{id:'lightning',featured:false,title:'How lightning forms',subtitle:'From a quiet cloud to a branching bolt. A film with a field you can experiment in.',category:'Understand',url:'https://claude.ai/artifact/RNdEZfYNZBBrFsrv3oy3NB',art:'lightning',tag:'ATMOSPHERIC PHYSICS'},
{id:'galevein',featured:false,title:'Galevein: Stormflight',subtitle:'Your dragon. A storm-washed world. Find a current and disappear into the clouds.',category:'Play',url:'https://galevein-stormflight.vercel.app',art:'dragon',tag:'THE DRAGON-FLIGHT PROJECT',embed:'frame'},
{id:'aeolith',title:'AEOLITH',subtitle:'The latest local Meridian Clash build: illuminated supertrees, ship workshop, and five AI match styles.',category:'Play',url:'/games/aeolith/index.html?mode=domination',art:'racer',tag:'MERIDIAN CLASH · AI PRACTICE',embed:'frame',edition:'AI practice edition. Online matchmaking and cloud progression are not connected.',image:'/games/aeolith/media/aeolith-gameplay-poster.png',trailer:'/games/aeolith/media/aeolith-gameplay.webm'},
{id:'universe-clash',title:'Universe Clash',subtitle:'A fighting-game arena with a tournament hub. Pick a fighter and meet the next challenge.',category:'Play',url:'https://universe-clash-preview.vercel.app',art:'racer',tag:'ARENA FIGHTER · PREVIEW',featured:false},
{id:'tides',featured:false,title:'Tides of Infamy',subtitle:'Sail, fight, and survive storms. Step into the pirate world.',category:'Play',url:'https://tides-of-infamy.vercel.app/',art:'reef',tag:'PIRATE WORLD · OPEN SEA',kind:'playable',embed:'frame'},
{id:'poe',featured:false,title:'Into the House of Poe',subtitle:'A gothic, video-driven game experiment inspired by Edgar Allan Poe.',category:'Watch',url:'https://x.com/itsArnz/status/2103856553124376674',art:'poe',tag:'GOTHIC HORROR · VIDEO SHOWCASE',kind:'showcase'},
{id:'fable-flight',featured:false,title:'Fable Flight',subtitle:'The existing flight trainer. Take the controls and find the horizon.',category:'Play',url:'https://arnie016.github.io/flight-simulator-fable5/',art:'orbit',tag:'FLIGHT SIMULATOR',embed:'frame'},
];
export const reconnect=[{id:'morse',title:'Morse Battle',text:'The signal-and-strategy game.'},{id:'edge-universe',title:'Edge of the Observable Universe',text:'A journey to the edge of what we can see.'},{id:'skyline',title:'Skyline Swing',text:'The comic-book city runner.'},{id:'alien-art',title:'Alien Art',text:'The hosted alien-art game.'},{id:'ben10',title:'The alien watch games',text:'Transformation and creature experiments.'},{id:'particles',title:'The particle room',text:'Cloud chambers, tracks, and collisions.'}];
export const nextWorlds=[{title:"Don’t believe your eyes",text:"A carousel of optical illusions, with controls that let you uncover each trick.",tag:"PERCEPTION"},{title:"A lost-world adventure",text:"A detailed ruins adventure. New shared reference under review.",tag:"ADVENTURE"},{title:"A very unreasonable goat",text:"A playful physics sandbox with an original mischievous animal.",tag:"PLAY"},{title:"Strange things after sunset",text:"An original eerie cartoon adventure with a timid hero.",tag:"STORY"},{title:'Space-time, bent',text:'An interactive black hole, lensing, and the path of light.',tag:'PHYSICS'},{title:'Inside CERN',text:'Follow a particle from source to collision and detector.',tag:'PHYSICS'},{title:'Where the heat goes',text:'Trace refrigerant through compression, condensation, expansion, and evaporation.',tag:'EVERYDAY SCIENCE'},{title:'A painted night',text:'A playable world inspired by swirling paint and starlight.',tag:'ART & PLAY'},{title:'The transformation watch',text:'Choose a creature and explore a new way to move.',tag:'PLAY'},{title:'A world made of tokens',text:'A playful model atlas with dated, source-linked costs and context limits.',tag:'DATA & PLAY'}];

export const worldHref=(p:Project)=>!p.url?'#':p.embed==='frame'||!p.url.startsWith('/')?'/world/'+p.id:p.url;
