export type Project={id:string;title:string;subtitle:string;category:'Understand'|'Play'|'Watch'|'Tools';url?:string;art:string;tag:string;status?:string;kind?:'showcase'|'playable';image?:string;trailer?:string;embed?:'frame'|'external';edition?:string;featured?:boolean;tokens?:number;cost?:number};
export const projects:Project[]=[
{id:'spacetime',title:'Space-time, bent',subtitle:'Orbit a black hole. Bend a beam of light, tilt the accretion disk, and see how gravity changes the view.',category:'Understand',url:'/spacetime',art:'orbit',tag:'GRAVITY · BLACK HOLE LAB',image:'/covers/spacetime.jpg',trailer:'/trailers/spacetime.webm'},
{id:'telescope',title:'Through the Glass',subtitle:'A midnight study, a telescope, and a little light from very far away. Turn the focus. Follow the rays.',category:'Understand',url:'/telescope',art:'orbit',tag:'OPTICS · INTERACTIVE LAB',image:'/covers/telescope.jpg',trailer:'/trailers/telescope.webm'},
{id:'airport',title:'Airside Intelligence',subtitle:'An airport that thinks with its sensors. Break a signal, dispatch a robot, and see what changes.',category:'Understand',url:'/airport',art:'signal',tag:'IOT · OPERATIONS SIMULATOR',image:'/covers/airport.jpg',trailer:'/trailers/airport.webm'},
{id:'lightning',title:'How lightning forms',subtitle:'From a quiet cloud to a branching bolt. A film with a field you can experiment in.',category:'Understand',url:'/games/lightning/index.html',embed:'frame',image:'/covers/lightning.jpg',trailer:'/trailers/lightning.webm',edition:'The original 60-second lightning film and interactive field lab. No account needed.',art:'lightning',tag:'ATMOSPHERIC PHYSICS'},
{id:'skyline',title:'Skyline Swing',subtitle:'A comic-book city at full speed. Swing over traffic, chase missions, and face the Ink Hound.',category:'Play',url:'/games/skyline/index.html',embed:'frame',image:'/covers/skyline.jpg',trailer:'/trailers/skyline.webm',edition:'NYC Rush: the original city runner, with Volt, missions, checkpoints and boss encounters.',art:'racer',tag:'COMIC-BOOK CITY · SWING & RUN'},
{id:'galevein',title:'Galevein: Stormflight',subtitle:'Your dragon. A storm-washed world. Find a current and disappear into the clouds.',category:'Play',url:'/games/galevein/index.html',image:'/covers/galevein.jpg',trailer:'/trailers/galevein.webm',edition:'Stormflight exploration with the Ember Wyrm mount. Procedural scenery and original synthesized score.',art:'dragon',tag:'THE DRAGON-FLIGHT PROJECT',embed:'frame'},
{id:'aeolith',title:'AEOLITH',subtitle:'The latest local Meridian Clash build: illuminated supertrees, ship workshop, and five AI match styles.',category:'Play',url:'/games/aeolith/index.html?mode=domination',art:'racer',tag:'MERIDIAN CLASH · AI PRACTICE',embed:'frame',edition:'AI practice edition. Online matchmaking and cloud progression are not connected.',image:'/games/aeolith/media/aeolith-gameplay-poster.png',trailer:'/games/aeolith/media/aeolith-gameplay.webm'},
{id:'universe-clash',title:'Universe Clash',subtitle:'A fighting-game arena with a tournament hub. Pick a fighter and meet the next challenge.',category:'Play',url:'/games/universe-clash/index.html',embed:'frame',image:'/covers/universe-clash.jpg',trailer:'/trailers/universe-clash.webm',edition:'Local AI arena. Human matchmaking and cloud progression are not connected in this edition.',art:'racer',tag:'ARENA FIGHTER · AI PLAY'},
{id:'tides',title:'Tides of Infamy',subtitle:'Sail, fight, and survive storms. Step into the pirate world.',category:'Play',url:'/games/tides/index.html',edition:'Solo voyage edition. Multiplayer, cloud voice and cloud progression are not connected.',image:'/games/tides/landing/tides-of-infamy-hero-web.png',trailer:'/games/tides/trailer/tides-of-infamy-teaser.mp4',art:'reef',tag:'PIRATE WORLD · OPEN SEA',kind:'playable',embed:'frame'},
{id:'edge-universe',title:'Thirty Steps Down',subtitle:'From the observable universe to a quark. Descend through thirty orders of scale and find your place in between.',category:'Understand',url:'/games/edge-universe/index.html',embed:'frame',image:'/covers/edge-universe.jpg',trailer:'/trailers/edge-universe.webm',art:'orbit',tag:'COSMIC SCALE · A JOURNEY INWARD'},
{id:'poe',title:'Into the House of Poe',subtitle:'A gothic film journey through the rooms of The Masque of the Red Death. Choose a chapter or surrender to the story.',category:'Watch',url:'/games/poe/index.html',embed:'frame',image:'/covers/poe.jpg',trailer:'/games/poe/media/masque.mp4',art:'poe',tag:'GOTHIC STORY · CINEMATIC JOURNEY',kind:'playable'},
{id:'fable-flight',title:'Fable Flight',subtitle:'The existing flight trainer. Take the controls and find the horizon.',category:'Play',url:'/games/fable-flight/index.html',image:'/covers/fable-flight.jpg',trailer:'/trailers/fable-flight.webm',edition:'Browser flight trainer with local text coaching. Live voice and cloud services are not connected.',art:'orbit',tag:'FLIGHT SIMULATOR',embed:'frame'},
];
export const reconnect=[{id:'morse',title:'Morse Battle',text:'The signal-and-strategy game.'},{id:'alien-art',title:'Alien Art',text:'The hosted alien-art game.'},{id:'ben10',title:'The alien watch games',text:'Transformation and creature experiments.'},{id:'particles',title:'The particle room',text:'Cloud chambers, tracks, and collisions.'}];
export const nextWorlds=[{title:"Don’t believe your eyes",text:"A carousel of optical illusions, with controls that let you uncover each trick.",tag:"PERCEPTION"},{title:"A lost-world adventure",text:"A detailed ruins adventure. New shared reference under review.",tag:"ADVENTURE"},{title:"A very unreasonable goat",text:"A playful physics sandbox with an original mischievous animal.",tag:"PLAY"},{title:"Strange things after sunset",text:"An original eerie cartoon adventure with a timid hero.",tag:"STORY"},{title:'Inside CERN',text:'Follow a particle from source to collision and detector.',tag:'PHYSICS'},{title:'Where the heat goes',text:'Trace refrigerant through compression, condensation, expansion, and evaporation.',tag:'EVERYDAY SCIENCE'},{title:'A painted night',text:'A playable world inspired by swirling paint and starlight.',tag:'ART & PLAY'},{title:'The transformation watch',text:'Choose a creature and explore a new way to move.',tag:'PLAY'},{title:'A world made of tokens',text:'A playful model atlas with dated, source-linked costs and context limits.',tag:'DATA & PLAY'}];

export const worldHref=(p:Project)=>!p.url?'#':p.embed==='frame'||!p.url.startsWith('/')?'/world/'+p.id:p.url;
