'use client';
import{useEffect,useRef,useState}from'react';
import*as T from'three';
import{OrbitControls}from'three/addons/controls/OrbitControls.js';
import {coatingPreset,sphericalRayFocus,type LabState}from'./optics';
import {observingRoom} from './room';
type Engine={update:(s:LabState)=>void;reset:(view?:string)=>void};
export default function TelescopeScene({state,resetKey,view='optics'}:{state:LabState;resetKey:number;view?:string}){
 const host=useRef<HTMLDivElement>(null),engine=useRef<Engine|null>(null),latest=useRef(state);const[failed,setFailed]=useState(false);latest.current=state;
 useEffect(()=>{
 if(!host.current)return;const mount=host.current;let renderer:T.WebGLRenderer;
 try{renderer=new T.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:true});}catch{setFailed(true);return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0,0);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;renderer.domElement.setAttribute('aria-label','3D telescope. Drag to orbit, or use the labeled optics controls.');mount.appendChild(renderer.domElement);
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(34,1,.1,120),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=8;controls.maxDistance=24;controls.minPolarAngle=.22;controls.maxPolarAngle=2.5;
 function reset(view='optics'){if(view==='room'){camera.position.set(13,7.5,15);controls.target.set(-1.5,.3,-1.3);controls.maxDistance=36;}else if(view==='front'){camera.position.set(-10,1.5,5);controls.target.set(-.4,0,0);controls.maxDistance=24;}else{camera.position.set(-5.2,3.8,12.8);controls.target.set(0,.1,0);controls.maxDistance=24;}controls.update();}reset();
 observingRoom(scene);
 scene.add(new T.HemisphereLight(0xbcd7ff,0x171015,2.3));for(const[c,i,p]of [[0xffefd5,5,[-3,7,5]],[0x6daaff,4,[1,1,-5]]]as const){const l=new T.DirectionalLight(c,i);l.position.set(p[0],p[1],p[2]);scene.add(l);}const warm=new T.PointLight(0xfac77e,25,14);warm.position.set(-5,1,4);scene.add(warm);
 let seed=42;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};const stars=[];for(let i=0;i<600;i++)stars.push((rnd()-.5)*70,(rnd()-.3)*35,-14-rnd()*25);const sg=new T.BufferGeometry();sg.setAttribute('position',new T.Float32BufferAttribute(stars,3));scene.add(new T.Points(sg,new T.PointsMaterial({color:0xc2c6c7,size:.025,transparent:true,opacity:.65})));
 const grid=new T.PolarGridHelper(12,24,12,128,0x283b46,0x15232d);grid.position.y=-2.25;grid.visible=false;scene.add(grid);
 const instrument=new T.Group();instrument.rotation.z=-.08;scene.add(instrument);let model=new T.Group();instrument.add(model);
 const material=(color:number,metalness=.7,roughness=.3)=>new T.MeshStandardMaterial({color,metalness,roughness});const body=material(0x25414b),silver=material(0xa4afb1,.92,.25),dark=material(0x101a23),gold=material(0xc6a16a,.85,.24),glass=new T.MeshPhysicalMaterial({color:0x94d5d6,roughness:.07,metalness:.1,transparent:true,opacity:.24,side:T.DoubleSide,depthWrite:false}),light=new T.MeshBasicMaterial({color:0xffdc9c});const owned:T.Material[]=[];
 let photons:{mesh:T.Mesh;path:T.Vector3[];offset:number}[]=[];
 function cylinder(r:number,length:number,x:number,m:T.Material,open=false,theta=Math.PI*2){const mesh=new T.Mesh(new T.CylinderGeometry(r,r,length,72,1,open,0,theta),m);mesh.rotation.z=Math.PI/2;mesh.position.x=x;model.add(mesh);return mesh;}
 function ring(x:number,r:number,w:number,m:T.Material){const mesh=new T.Mesh(new T.TorusGeometry(r,w,12,80),m);mesh.rotation.y=Math.PI/2;mesh.position.x=x;model.add(mesh);return mesh;}
 function rod(a:T.Vector3,b:T.Vector3,r:number,m:T.Material){const mesh=new T.Mesh(new T.CylinderGeometry(r,r,a.distanceTo(b),10),m);mesh.position.copy(a).add(b).multiplyScalar(.5);mesh.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),b.clone().sub(a).normalize());model.add(mesh);}
 function lens(x:number,r:number){const mesh=new T.Mesh(new T.SphereGeometry(1,48,24),glass);mesh.scale.set(.08,r,r);mesh.position.x=x;model.add(mesh);ring(x,r,.035,gold);return mesh;}
 function label(text:string,p:T.Vector3,color='#c5ccc9'){const c=document.createElement('canvas');c.width=640;c.height=80;const ctx=c.getContext('2d')!;ctx.font='500 27px monospace';ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(text,320,47);const texture=new T.CanvasTexture(c),m=new T.SpriteMaterial({map:texture,transparent:true,depthTest:false});owned.push(m);const sp=new T.Sprite(m);sp.position.copy(p);sp.scale.set(2.9,.36,1);model.add(sp);}
 function path(points:T.Vector3[],color:number,index:number){const m=new T.LineBasicMaterial({color,transparent:true,opacity:.8});owned.push(m);model.add(new T.Line(new T.BufferGeometry().setFromPoints(points),m));for(let k=0;k<3;k++){const mesh=new T.Mesh(new T.SphereGeometry(.027,8,6),light);model.add(mesh);photons.push({mesh,path:points,offset:k/3+index*.041});}}
 function clear(){model.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Line)o.geometry.dispose();if(o instanceof T.Sprite)o.material.map?.dispose();});owned.splice(0).forEach(m=>m.dispose());instrument.remove(model);model=new T.Group();instrument.add(model);photons=[];}
 function update(s:LabState){clear();const coat=coatingPreset(s);glass.color.set(s.coating==='enhanced'?0x8499dd:0x94d5d6);const r=.52+s.aperture/270,front=-2.9,back=2.25;const shell=cylinder(r,5.15,-.325,body,true,s.cutaway?Math.PI:Math.PI*2);shell.rotation.x=s.cutaway?Math.PI:0;cylinder(r+.06,.4,front+.15,dark,true);cylinder(r+.05,.2,back-.1,dark,true);
 for(const x of[front-.1,front+.36,-1.6,.7,back])ring(x,r+.025,.043,x===front-.1||x===back?gold:silver);
 for(let i=0;i<24;i++){const a=i/24*Math.PI*2;const bolt=new T.Mesh(new T.SphereGeometry(.032,8,6),silver);bolt.position.set(front+.35,Math.sin(a)*(r+.07),Math.cos(a)*(r+.07));model.add(bolt);}
 for(const x of[-1.2,1.1]){const support=new T.Mesh(new T.BoxGeometry(.25,.55,.3),dark);support.position.set(x,-r-.2,0);model.add(support);}const rail=new T.Mesh(new T.BoxGeometry(4,.12,.4),silver);rail.position.set(.1,-r-.5,0);model.add(rail);for(const x of[-1.6,1.6])for(const z of[-.65,.65])rod(new T.Vector3(x,-r-.5,0),new T.Vector3(x,-2.2,z),.045,dark);
 const f=4.9+(s.focal-800)/1600,F=front+f,fe=.25+s.eyepiece/100,shift=s.focus*.17;
 if(s.scope==='refractor'){lens(front,r-.05);lens(front+.16,r-.06);const eyeX=F+fe+shift;cylinder(.31,Math.max(.3,eyeX-back),(eyeX+back)/2,silver,true);cylinder(.35,.48,eyeX,dark,true);lens(eyeX,.235);ring(eyeX+.27,.29,.065,dark);
 for(let i=0;i<32;i++){const a=i/32*Math.PI*2;rod(new T.Vector3(eyeX-.2,Math.sin(a)*.35,Math.cos(a)*.35),new T.Vector3(eyeX+.2,Math.sin(a)*.35,Math.cos(a)*.35),.011,silver);}const wheel=cylinder(.23,.15,back,gold);wheel.rotation.set(Math.PI/2,0,0);wheel.position.set(back,-.43,.4);
 if(s.cutaway){const m=new T.MeshBasicMaterial({color:0xefc782,transparent:true,opacity:.09,side:T.DoubleSide,depthWrite:false});owned.push(m);const plane=new T.Mesh(new T.PlaneGeometry(r*1.5,r*1.5),m);plane.rotation.y=Math.PI/2;plane.position.x=F;model.add(plane);ring(F,.13,.009,light);}
 if(s.rays)for(let i=0;i<10;i++){const a=i/10*Math.PI*2,y=Math.sin(a)*r*.81,z=Math.cos(a)*r*.81,ey=-y*(fe+shift)/f,ez=-z*(fe+shift)/f,uy=-y/f-ey/fe,uz=-z/f-ez/fe;path([new T.Vector3(-5.7,y,z),new T.Vector3(front,y,z),new T.Vector3(F,0,0),new T.Vector3(eyeX,ey,ez),new T.Vector3(eyeX+1.3,ey+uy*1.3,ez+uz*1.3)],0xe8bf7b,i);}
 label('01  OBJECTIVE',new T.Vector3(front,r+.6,0));label('02  FOCAL PLANE',new T.Vector3(F,-r-.22,.5),'#e8bf7b');label('03  EYEPIECE',new T.Vector3(eyeX,.9,0));
 }else{const primary=back-.16,virtualF=primary-f,sx=-1.75,fy=sx-virtualF;
 const profile:T.Vector2[]=[];for(let j=0;j<=32;j++){const h=(r-.04)*j/32,sag=s.mirror==='spherical'?2*f-Math.sqrt(4*f*f-h*h):h*h/(4*f);profile.push(new T.Vector2(h,sag));}
 const mirror=new T.Mesh(new T.LatheGeometry(profile,64),silver);mirror.rotation.z=Math.PI/2;mirror.position.x=primary;mirror.material.side=T.DoubleSide;model.add(mirror);ring(primary,r-.04,.055,gold);const sec=new T.Mesh(new T.CylinderGeometry(r*.31,r*.31,.045,48),silver);sec.rotation.z=Math.PI/4;sec.position.set(sx,0,0);model.add(sec);for(let i=0;i<4;i++){const a=i/4*Math.PI*2;rod(new T.Vector3(sx,0,0),new T.Vector3(sx,Math.sin(a)*r,Math.cos(a)*r),.013,dark);}const ey=fy+fe+shift,holder=cylinder(.28,.4,sx,dark,true);holder.rotation.z=0;holder.position.set(sx,ey,0);const el=lens(sx,.21);el.rotation.z=Math.PI/2;el.position.set(sx,ey,0);
 if(s.rays)for(let i=0;i<12;i++){const a=(i+.5)/4*Math.PI*2,zone=[.42,.67,.9][Math.floor(i/4)],y=Math.sin(a)*r*zone,z=Math.cos(a)*r*zone,rayF=s.mirror==='spherical'?sphericalRayFocus(s.focal,s.aperture*.5*zone)/s.focal*f:f,P=new T.Vector3(primary,y,z),V=new T.Vector3(primary-rayF,0,0),d=V.clone().sub(P),t=(sx-P.x-P.y)/(d.x+d.y),hit=P.clone().addScaledVector(d,t),focus=new T.Vector3(sx,sx-(primary-rayF),0),out=focus.clone().sub(hit),q=(ey-hit.y)/out.y,e=hit.clone().addScaledVector(out,q),ux=out.x/out.y-(e.x-sx)/fe,uz=out.z/out.y-e.z/fe;path([new T.Vector3(-5.7,y,z),P,hit,focus,e,new T.Vector3(e.x+ux,ey+1,e.z+uz)],i%2?0x85ccd3:0xe8bf7b,i);}
 label(s.mirror==='spherical'?'01  SPHERICAL MIRROR':'01  PARABOLIC MIRROR',new T.Vector3(primary,r+.55,0));label('02  SECONDARY',new T.Vector3(sx,-r-.25,.5));label('03  EYEPIECE',new T.Vector3(sx,ey+.5,0),'#e8bf7b');}
 // Machined dovetail scale, focus travel rack and an aligned finder scope.
 for(let j=0;j<29;j++){const tick=new T.Mesh(new T.BoxGeometry(.012,j%5===0?.085:.04,.015),gold);tick.position.set(-1.4+j*.1,-r-.54,.218);model.add(tick);}
 const finder=cylinder(.105,.9,-1.7,dark,true);finder.position.set(-1.7,r+.24,-.23);for(const x of[-2.16,-1.26]){const rim=ring(x,.106,.02,gold);rim.position.y=r+.24;rim.position.z=-.23;}rod(new T.Vector3(-1.7,r-.05,-.23),new T.Vector3(-1.7,r+.18,-.23),.04,silver);
 label('OPEN SKY  →',new T.Vector3(-4.8,-.05,0),'#e8bf7b');
 if(s.coating!=='ideal')label(coat.name.toUpperCase(),new T.Vector3(.1,r+.58,0),'#b1c6ed');} 
 engine.current={update,reset};update(latest.current);const resize=()=>{renderer.setSize(mount.clientWidth,mount.clientHeight);camera.aspect=mount.clientWidth/mount.clientHeight;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(mount);resize();let frame=0,last=0,visible=true;const io=new IntersectionObserver(e=>{visible=e[0].isIntersecting;});io.observe(mount);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 function animate(t:number){frame=requestAnimationFrame(animate);if(!visible||document.hidden||t-last<30)return;last=t;controls.update();for(const p of photons){const u=(!reduced&&latest.current.motion?(t*.00010+p.offset)%1:p.offset%1),lengths=p.path.slice(1).map((v,i)=>v.distanceTo(p.path[i]));let dist=u*lengths.reduce((a,b)=>a+b,0);for(let i=0;i<lengths.length;i++){if(dist<=lengths[i]){p.mesh.position.copy(p.path[i]).lerp(p.path[i+1],dist/lengths[i]);break;}dist-=lengths[i];}}renderer.render(scene,camera);}frame=requestAnimationFrame(animate);
 return()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();controls.dispose();clear();scene.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Points||o instanceof T.Line){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());}});[body,silver,dark,gold,glass,light].forEach(m=>m.dispose());renderer.dispose();renderer.domElement.remove();engine.current=null;};
 },[]);
 useEffect(()=>{engine.current?.update(state);},[state.scope,state.aperture,state.focal,state.eyepiece,state.focus,state.cutaway,state.rays,state.coating,state.mirror]);useEffect(()=>{engine.current?.reset(view);},[resetKey,view]);
 return <div className="scene" ref={host}>{failed&&<div className="scene-fallback"><h3>Your browser could not draw the telescope.</h3><p>The controls and field guide still work. Try another browser with WebGL enabled.</p></div>}</div>;
}
