/** Reproducible teaching experiment. This policy never commands the terminal fleet. */
export const learningActions=['Coast','UWB ping','UWB + vision'] as const;
export type LearningState={age:number;busy:boolean;fault:boolean};
export type LearningScore={name:string;reward:number;energy:number;progress:number;holds:number;reads:number;lost:number;steps:number};
export type LearningResult={seed:number;episodes:number;q:number[][];curve:{episode:number;reward:number}[];scores:LearningScore[]};
const random=(seed:number)=>()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
export function learningStateIndex(s:LearningState){return Math.min(6,Math.max(0,Math.floor(s.age)))+(s.busy?7:0)+(s.fault?14:0);}
const best=(q:number[])=>q.reduce((a,v,i)=>v>q[a]?i:a,0);
/** Every decision is one simulated second, with an independent stale-data guardian. */
export function learningTransition(s:LearningState,action:number,draws:{read:number;fault:number;busy:number}){action=Math.max(0,Math.min(2,Math.floor(action)));const successChance=action===1?(s.fault?.12:s.busy?.72:.94):action===2?(s.fault?.8:s.busy?.9:.98):0;const success=action>0&&draws.read<successChance;const age=success?0:Math.min(6,s.age+1),held=age>3,energy=action===0?0:action===1?.12:1.02,progress=held?0:1;const reward=progress-.7*energy-.065*age*age-(held?1.25:0);const next={age,busy:draws.busy<(s.busy?.86:.11),fault:draws.fault<(s.fault?.83:.055)};return{next,reward,energy,progress,held,success,attempted:action>0};}
export function evaluateLearning(q:number[][],policy:'learned'|'fixed'|'rules',seed=99017,steps=2400):LearningScore{const rng=random(seed);let state:LearningState={age:0,busy:false,fault:false};const total:LearningScore={name:policy==='learned'?'Learned table':policy==='fixed'?'Always fuse':'Simple age rule',reward:0,energy:0,progress:0,holds:0,reads:0,lost:0,steps};for(let i=0;i<steps;i++){const action=policy==='learned'?best(q[learningStateIndex(state)]):policy==='fixed'?2:state.age<1?0:state.fault?2:1;const result=learningTransition(state,action,{read:rng(),fault:rng(),busy:rng()});state=result.next;total.reward+=result.reward;total.energy+=result.energy;total.progress+=result.progress;total.holds+=result.held?1:0;total.reads+=result.success?1:0;total.lost+=result.attempted&&!result.success?1:0;}return total;}
export function trainLearning(seed=42,episodes=360):LearningResult{episodes=Math.max(1,Math.min(1000,Math.floor(episodes)));const rng=random(seed),q=Array.from({length:28},()=>[0,0,0]),curve:LearningResult['curve']=[];for(let e=0;e<episodes;e++){let state:LearningState={age:0,busy:rng()<.3,fault:false},reward=0;const epsilon=.45*(1-e/episodes)+.035;for(let k=0;k<100;k++){const index=learningStateIndex(state),action=rng()<epsilon?Math.floor(rng()*3):best(q[index]);const r=learningTransition(state,action,{read:rng(),fault:rng(),busy:rng()});const target=r.reward+.92*Math.max(...q[learningStateIndex(r.next)]);q[index][action]+=.13*(target-q[index][action]);reward+=r.reward;state=r.next;}if(e%10===0||e===episodes-1)curve.push({episode:e+1,reward:reward/100});}return{seed,episodes,q,curve,scores:([ 'learned','rules','fixed'] as const).map(p=>evaluateLearning(q,p))};}
export function learnedAction(q:number[][],age:number,busy:boolean,fault:boolean){return learningActions[best(q[learningStateIndex({age,busy,fault})])];}
