'use client';
import{useEffect,useRef,useState}from'react';import*as T from'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';import{kit,material,textSprite,disposeScene}from'../three-kit';import{terminalDetail}from'./terminal-detail';import{zones,type Sim,type Config,type Asset}from'./simulation';
export default function AirportScene({sim,config,view,layer,editing,onSelect,onMove}:{sim:Sim;config:Config;view:string;layer:string;editing:boolean;onSelect:(id:string)=>void;onMove:(x:number,z:number)=>void}){
 const host=useRef<HTMLDivElement>(null),latest=useRef({sim,config,view,layer,editing,onSelect,onMove});latest.current={sim,config,view,layer,editing,onSelect,onMove};const[failed,setFailed]=useState(false);
 useEffect(()=>{if(!host.current)return;const mount=host.current;let r:T.WebGLRenderer;try{r=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});}catch{setFailed(true);return;}r.setPixelRatio(Math.min(devicePixelRatio,1.6));r.setClearColor(0x070e1b);r.toneMapping=T.ACESFilmicToneMapping;r.toneMappingExposure=1.08;r.shadowMap.enabled=true;r.shadowMap.type=T.PCFShadowMap;mount.appendChild(r.domElement);r.domElement.setAttribute('aria-label','3D airport terminal with moving simulated assets. Select an asset in the fleet list to inspect it.');
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(37,1,.1,200),controls=new OrbitControls(camera,r.domElement);camera.position.set(34,28,34);controls.target.set(0,0,-1);controls.minDistance=12;controls.maxDistance=85;controls.maxPolarAngle=1.5;controls.enableDamping=true;
 scene.add(new T.HemisphereLight(0x8eaed3,0x101c2a,2));const sun=new T.DirectionalLight(0xc4d4ff,2.6);sun.position.set(-17,30,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-30,right:30,top:25,bottom:-25,near:1,far:90});sun.shadow.bias=-.0003;sun.shadow.normalBias=.03;scene.add(sun);
 const env=new T.Group();scene.add(env);const{box,cyl,ball,rod}=kit(env),floor=material(0x233644,.38,.3),pearl=material(0x657582,.38,.2),dark=material(0x122535),steel=material(0x4f6b81,.25,.6),mint=material(0x426b70),gold=material(0xbb995e),leaf=material(0x608561),glass=new T.MeshPhysicalMaterial({color:0x8ac2c5,transparent:true,opacity:.22,metalness:.1,roughness:.08,depthWrite:false}),asphalt=material(0x172531);
 box(0,-.5,0,38,.8,21,pearl);box(0,-.065,0,37,.05,19,floor);box(0,-.45,-17,42,.12,12,asphalt);
 for(let x=-18;x<=18;x+=1.5)box(x,-.02,0,.012,.015,19,steel);for(let z=-9;z<=9;z+=1.5)box(0,-.018,z,37,.015,.012,steel);
 // Main circulation spine and route markings.
 box(0,0,0,35,.016,2.1,pearl);for(let x=-16;x<=16;x+=2)box(x,.016,0,.8,.02,.035,mint);
 for(const zone of zones){const label=textSprite(zone.name.toUpperCase(),'#c6dbe8',3.5);label.position.set(zone.x,.12,zone.z+1.7);env.add(label);}
 // Glass terminal facade, structural columns, winged roof ribs, accessible boarding piers.
 box(0,1.6,-9.4,37,3.2,.08,glass);for(let x=-18;x<=18;x+=3){box(x,1.9,-9.3,.1,3.8,.14,steel);box(x,2.2,8.5,.18,4.4,.18,pearl);rod(new T.Vector3(x,4.4,8.5),new T.Vector3(x,5.3,0),.065,steel);rod(new T.Vector3(x,5.3,0),new T.Vector3(x,4,-9.3),.065,steel);}
 for(const x of[-13,0,13]){box(x,.6,-10.6,2.2,1.2,2.4,pearl);box(x,1.2,-10.6,2.25,.08,2.4,steel);box(x,.8,-10.6,2.22,.4,2.2,glass);}
 // Check-in islands with monitors, scales, luggage and queue stanchions.
 for(let row=0;row<2;row++)for(let col=0;col<7;col++){const x=-15+col*1.1,z=-6.7+row*2.2;box(x,.55,z,.95,1.1,.8,pearl);box(x,1.15,z,1.05,.1,.95,mint);box(x,1.45,z-.1,.5,.35,.08,dark);box(x,1.45,z-.047,.4,.25,.008,material(0x5cafa5,.2));box(x,.2,z+.62,.5,.3,.6,steel);if(col%2===0){box(x+.14,.53,z+.62,.26,.38,.32,gold);cyl(x,.01,z+1.1,.065,.8,steel);}}
 // Security screening lanes: belt, scanner, arch and transparent dividers.
 for(let i=0;i<4;i++){const x=-2.3+i*1.4;box(x,.6,-5,.66,.16,4,dark);box(x,1.1,-5.7,1.05,1.3,1.3,steel);box(x,.9,-4.95,.7,.5,.03,dark);for(const dx of[-.6,.6])box(x+dx,1,-3,.08,2,.1,mint);box(x,2,-3,1.25,.1,.1,mint);box(x+.65,.8,-5,.04,1.6,3.5,glass);}
 // Gate lounges and planters.
 for(let g=0;g<3;g++)for(let row=0;row<3;row++)for(let j=0;j<5;j++){const x=7+g*3.2+j*.5,z=-7+row*1.2;box(x,.5,z,.43,.12,.45,mint);box(x,.85,z-.2,.43,.6,.09,mint);box(x,.25,z,.07,.5,.07,steel);}
 // Baggage loops and moving individual suitcases.
 for(const x of[6.7,13.5]){const belt=new T.Mesh(new T.TorusGeometry(1.55,.36,4,60),dark);belt.rotation.x=Math.PI/2;belt.scale.x=1.5;belt.position.set(x,.35,5.5);env.add(belt);cyl(x,.1,5.5,1.25,.2,pearl);}
 // Service dock charging bays, return carts, solar roof panels behind the building.
 for(let i=0;i<8;i++){const x=-13.5+i*.7;box(x,.02,5.3,.55,.03,1.5,mint);box(x,.35,6,.5,.7,.18,dark);box(x,.7,5.88,.23,.09,.04,new T.MeshBasicMaterial({color:0x8cd5af}));}
 for(let i=0;i<4;i++){box(-16,.6,2.5+i*.7,1.5,1.2,.5,pearl);box(-16,1.3,2.5+i*.7,1.6,.1,.6,gold);}
 for(const[x,z]of[[-17,-2],[4,-7],[4,3],[-4,5],[17,1]]){cyl(x,.35,z,.6,.7,pearl);cyl(x,1.4,z,.1,2,steel);for(let i=0;i<5;i++){const a=i*2.4,b=ball(x+Math.sin(a)*.5,2+Math.cos(a)*.2,z+Math.cos(a)*.5,.55,leaf);b.scale.y=.5;}}
 // Three original simplified aircraft parked beyond the windows.
 for(const x of[-13,0,13]){const plane=new T.Group();env.add(plane);plane.position.set(x,.7,-16);const p=kit(plane);const fus=p.ball(0,.3,0,.6,pearl);fus.scale.set(1,1,6);p.box(0,.4,.3,7,.08,1.7,pearl);p.box(0,.45,-2.5,3,.07,.7,pearl);p.box(0,1.05,-2.4,.08,1.4,.95,mint);for(const sx of[-1.5,1.5]){const e=p.cyl(sx,.15,.6,.25,1,dark);e.rotation.x=Math.PI/2;}for(let j=0;j<9;j++)for(const sx of[-.58,.58])p.box(sx,.57,-1.8+j*.43,.02,.12,.16,dark);}
 const sensors=new T.Group();env.add(sensors);const sKit=kit(sensors);for(const[x,z]of[[-16,-8],[-5,-8],[5,-8],[16,-8],[-16,8],[-5,8],[5,8],[16,8]]){sKit.cyl(x,2,z,.04,4,steel);sKit.box(x,4,z,.28,.3,.25,mint);const ring=new T.Mesh(new T.RingGeometry(3.5,3.55,64),new T.MeshBasicMaterial({color:0x23887f,side:T.DoubleSide,transparent:true,opacity:.3}));ring.rotation.x=-Math.PI/2;ring.position.set(x,.04,z);sensors.add(ring);}
 const animateDetail=terminalDetail(scene);
 const peopleGeometry=new T.CapsuleGeometry(.09,.3,3,6),peopleMat=material(0xa6a994),people=new T.InstancedMesh(peopleGeometry,peopleMat,140);people.castShadow=true;env.add(people);const dummy=new T.Object3D();
 const fleet=new T.Group();scene.add(fleet);const meshes=new Map<string,T.Group>();const colors={moving:0x237b75,held:0xd78942,charging:0x5378a8,idle:0x81877d};
 function assetMesh(a:Asset){const g=new T.Group(),k=kit(g),paint=material(colors[a.mode],.4,.4);if(a.type==='robot'){k.cyl(0,.38,0,.29,.55,paint,.25);k.ball(0,.76,0,.22,pearl);k.box(0,.75,.19,.29,.15,.06,dark);for(const dx of[-.09,.09])k.ball(dx,.76,.225,.022,new T.MeshBasicMaterial({color:0xa5e9d6}));}else if(a.type==='wheelchair'){k.box(0,.45,0,.48,.09,.48,paint);k.box(0,.68,-.2,.48,.5,.07,paint);for(const sx of[-.28,.28]){const w=new T.Mesh(new T.TorusGeometry(.26,.035,8,22),dark);w.rotation.y=Math.PI/2;w.position.set(sx,.28,0);g.add(w);}if(a.occupied){k.ball(0,.9,0,.12,pearl);k.box(0,.68,0,.19,.22,.17,steel);}}else{for(const dx of[-.23,.23])for(const dz of[-.35,.35])k.ball(dx,.12,dz,.065,dark);k.box(0,.3,0,.55,.16,.85,paint);for(const dx of[-.23,.23])k.box(dx,.55,-.36,.03,.65,.03,steel);k.box(0,.88,-.36,.5,.04,.04,steel);if(a.type==='cleaner'){k.cyl(0,.57,0,.2,.4,gold);k.box(0,.52,.25,.4,.32,.3,mint);}else{for(const dz of[-.3,.3])k.box(0,.53,dz,.55,.28,.03,steel);}}g.userData.asset=a.id;g.userData.mode=a.mode;g.userData.paint=paint;g.traverse(o=>o.userData.asset=a.id);return g;}
 for(const a of latest.current.sim.assets){const g=assetMesh(a);fleet.add(g);meshes.set(a.id,g);}
 const halo=new T.Mesh(new T.RingGeometry(.59,.65,48),new T.MeshBasicMaterial({color:0xe6af49,side:T.DoubleSide}));halo.rotation.x=-Math.PI/2;halo.position.y=.06;scene.add(halo);let path:T.Line|null=null,links:T.LineSegments|null=null,lastSignature='',lastView='',lastLayer='';
 const ray=new T.Raycaster(),mouse=new T.Vector2();let down=[0,0];const pointerDown=(e:PointerEvent)=>down=[e.clientX,e.clientY];const pointerUp=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const b=r.domElement.getBoundingClientRect();mouse.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(Array.from(meshes.values()),true)[0];if(hit){latest.current.onSelect(hit.object.userData.asset);return;}if(latest.current.editing){const p=new T.Vector3();if(ray.ray.intersectPlane(new T.Plane(new T.Vector3(0,1,0),0),p))latest.current.onMove(p.x,p.z);}};r.domElement.addEventListener('pointerdown',pointerDown);r.domElement.addEventListener('pointerup',pointerUp);
 const resize=()=>{r.setSize(mount.clientWidth,mount.clientHeight);camera.aspect=mount.clientWidth/mount.clientHeight;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(mount);resize();let frame=0,last=0,visible=true;const io=new IntersectionObserver(e=>visible=e[0].isIntersecting);io.observe(mount);
 function animate(t:number){frame=requestAnimationFrame(animate);if(document.hidden||!visible||t-last<32)return;last=t;const{sim,config,view,layer}=latest.current;const selected=sim.assets.find(a=>a.id===config.selected)!;if(lastView!==view){lastView=view;if(view==='overhead'){camera.position.set(0,52,1);controls.target.set(0,0,0);}else if(view==='floor'){camera.position.set(23,7,17);controls.target.set(0,0,0);}else{camera.position.set(34,28,34);controls.target.set(0,0,-1);}}if(view==='follow'){camera.position.lerp(new T.Vector3(selected.x+6,6,selected.z+9),.05);controls.target.lerp(new T.Vector3(selected.x,.7,selected.z),.06);}
  for(const a of sim.assets){const g=meshes.get(a.id)!;g.position.set(a.x,0,a.z);g.rotation.y=a.heading;if(g.userData.mode!==a.mode){g.userData.mode=a.mode;(g.userData.paint as T.MeshStandardMaterial).color.setHex(colors[a.mode]);}}
  halo.position.set(selected.x,.06,selected.z);sensors.visible=layer==='coverage';
  const signature=JSON.stringify([config.selected,selected.route,Math.round(selected.x*3),Math.round(selected.z*3),layer]);if(signature!==lastSignature){lastSignature=signature;if(path){scene.remove(path);path.geometry.dispose();(path.material as T.Material).dispose();}path=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(selected.x,.12,selected.z),...selected.route.map(p=>new T.Vector3(p.x,.12,p.z))]),new T.LineBasicMaterial({color:0x008a96}));path.visible=layer==='routes'||layer==='coverage';scene.add(path);if(links){scene.remove(links);links.geometry.dispose();(links.material as T.Material).dispose();}const pts:T.Vector3[]=[];if(layer==='coverage')for(const[x,z]of[[-16,-8],[-5,-8],[5,-8],[16,-8],[-5,8],[5,8]]){pts.push(new T.Vector3(x,4,z),new T.Vector3(selected.x,.8,selected.z));}links=new T.LineSegments(new T.BufferGeometry().setFromPoints(pts),new T.LineBasicMaterial({color:0x43a98e,transparent:true,opacity:.3}));scene.add(links);}
  if(lastLayer!==layer){lastLayer=layer;}for(let i=0;i<140;i++){const n=config.scenario==='surge'?140:75;const x=((i*1.67+sim.time*(i%2?.13:-.12)+50)%35)-17.5,z=Math.sin(i*8.2)*1.15+(i%3===0?-3.2:i%3===1?3.2:0);dummy.position.set(x,i<n?.35:-20,z);dummy.rotation.y=i%2?Math.PI/2:-Math.PI/2;dummy.updateMatrix();people.setMatrixAt(i,dummy.matrix);}people.instanceMatrix.needsUpdate=true;animateDetail(sim,config,layer);controls.update();r.render(scene,camera);
 }frame=requestAnimationFrame(animate);return()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();controls.dispose();r.domElement.removeEventListener('pointerdown',pointerDown);r.domElement.removeEventListener('pointerup',pointerUp);disposeScene(scene);r.dispose();r.domElement.remove();};
 },[]);
 return <div className="airport-canvas" ref={host}>{failed&&<div className="scene-fallback">The 3D view needs WebGL. The simulation controls and fleet data still work.</div>}</div>;
}
