export type Sensor='rfid'|'uwb'|'vision'|'imu'|'textile';
export type AssetType='robot'|'wheelchair'|'trolley'|'cleaner';
export const zones=[{id:'arrivals',name:'Arrivals',x:-15,z:5},{id:'checkin',name:'Check-in',x:-8,z:-5},{id:'security',name:'Security',x:0,z:-5},{id:'gates',name:'Gate lounges',x:13,z:-5},{id:'baggage',name:'Baggage hall',x:9,z:5},{id:'charge',name:'Service & charging',x:-9,z:5}];
export type Asset={id:string;type:AssetType;x:number;z:number;target:number;route:{x:number;z:number}[];battery:number;uncertainty:number;age:number;mode:'moving'|'charging'|'held'|'idle';last:Record<Sensor,number>;health:Record<Sensor,boolean>;tasks:number;heading:number;packets:number;occupied:boolean};
export type Sim={time:number;assets:Asset[];energy:number;packets:number;bytes:number;tasks:number;log:{time:number;text:string}[];seed:number;requests:number;prevented:number};
export type Config={policy:'adaptive'|'fixed';scenario:'baseline'|'surge'|'dropout'|'occlusion'|'drift'|'stale';sensors:Record<Sensor,boolean>;selected:string};
export const defaults:Config={policy:'adaptive',scenario:'baseline',sensors:{rfid:true,uwb:true,vision:true,imu:true,textile:true},selected:'R-01'};
export const sensorInfo:Record<Sensor,{name:string;role:string;hz:number;joules:number;bytes:number}>={rfid:{name:'RFID / NFC',role:'Identity at reader checkpoints',hz:.5,joules:.015,bytes:48},uwb:{name:'UWB anchors',role:'Relative position',hz:2,joules:.12,bytes:96},vision:{name:'Vision',role:'Zone occupancy and motion',hz:1,joules:.9,bytes:2048},imu:{name:'IMU',role:'Motion and tilt on the edge',hz:5,joules:.006,bytes:32},textile:{name:'E-textile patch',role:'Seat load and handle contact',hz:1,joules:.008,bytes:24}};
const sensors=Object.keys(sensorInfo) as Sensor[];
const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,v));
export function routeTo(x:number,z:number,tx:number,tz:number){return[{x,z:0},{x:tx,z:0},{x:tx,z:tz}].filter((p,i,a)=>i===0||Math.abs(p.x-a[i-1].x)+Math.abs(p.z-a[i-1].z)>.01);}
export function makeSim(seed=42):Sim {let r=seed;const random=()=>{r=(r*1664525+1013904223)>>>0;return r/4294967296;};const assets:Asset[]=[];for(let i=0;i<28;i++){const type:AssetType=i<8?'robot':i<14?'wheelchair':i<24?'trolley':'cleaner',prefix={robot:'R',wheelchair:'W',trolley:'T',cleaner:'C'}[type],n=i<8?i+1:i<14?i-7:i<24?i-13:i-23,x=-16+random()*32,z=(i%2?1:-1)*(2.4+random()*3.5),target=i%5;assets.push({id:`${prefix}-${String(n).padStart(2,'0')}`,type,x,z,target,route:routeTo(x,z,zones[target].x,zones[target].z),battery:48+random()*48,uncertainty:.08,age:0,mode:'moving',last:{rfid:-10,uwb:-10,vision:-10,imu:-10,textile:-10},health:{rfid:true,uwb:true,vision:true,imu:true,textile:true},tasks:0,heading:0,packets:0,occupied:type==='wheelchair'&&i%2===0});}return{time:0,assets,energy:0,packets:0,bytes:0,tasks:0,log:[{time:0,text:'Terminal 01 ready · 28 assets · seed '+seed}],seed,requests:0,prevented:0};}
export function log(sim:Sim,text:string):Sim {return{...sim,log:[{time:sim.time,text},...sim.log].slice(0,10)};}
export function dispatch(sim:Sim,id:string,zone:number):Sim {const a=sim.assets.find(a=>a.id===id);if(!a||!zones[zone])return sim;if(a.age>5||a.battery<12||a.occupied){return log({...sim,prevented:sim.prevented+1},`${id}: dispatch refused · ${a.occupied?'seat occupied':a.age>5?'stale telemetry':'low battery'}`);}const t=zones[zone];return log({...sim,requests:sim.requests+1,assets:sim.assets.map(v=>v.id===id?{...v,target:zone,mode:'moving',route:routeTo(v.x,v.z,t.x,t.z)}:v)},`${id}: dispatch → ${t.name}`);}
export function reposition(sim:Sim,id:string,x:number,z:number):Sim{if(!Number.isFinite(x)||!Number.isFinite(z))return sim;x=clamp(x,-17,17);z=clamp(z,-6.5,6.5);return log({...sim,assets:sim.assets.map(a=>a.id===id?{...a,x,z,mode:'idle',route:[],age:0}:a)},`${id}: moved in layout editor`);}
export function step(prev:Sim,config:Config,dt:number):Sim{
 dt=clamp(dt,0,1);const time=prev.time+dt;let energy=prev.energy,packets=prev.packets,bytes=prev.bytes,tasks=prev.tasks,prevented=prev.prevented;const logs=[...prev.log];
 const assets=prev.assets.map(original=>{const a:Asset={...original,route:original.route.map(p=>({...p})),last:{...original.last},health:{...original.health}};const affected=a.id===config.selected;
  const stale=config.scenario==='stale'&&affected;
  const available:Record<Sensor,boolean>={rfid:config.sensors.rfid&&a.health.rfid&&!(config.scenario==='dropout'),uwb:config.sensors.uwb&&a.health.uwb&&!(config.scenario==='drift'&&affected),vision:config.sensors.vision&&a.health.vision&&!(config.scenario==='occlusion'&&a.x>0),imu:config.sensors.imu&&a.health.imu,textile:config.sensors.textile&&a.health.textile};
  let locationFresh=false;
  for(const s of sensors){if(!available[s]||stale)continue;const info=sensorInfo[s];let hz=info.hz;if(config.policy==='adaptive'){hz*=s==='vision'?(a.uncertainty>.3?.8:.12):s==='uwb'?(a.uncertainty>.25?1:.22):a.mode==='charging'?.15:.5;}if(time-a.last[s]>=1/hz){a.last[s]=time;packets++;a.packets++;energy+=info.joules;bytes+=info.bytes;if(s==='uwb'||s==='vision'||s==='rfid'&&Math.abs(a.z)>3.5)locationFresh=true;}}
  if(locationFresh)a.age=0;else a.age+=dt;
  const count=[available.uwb,available.vision,available.rfid].filter(Boolean).length;
  const target=clamp(.055+(3-count)*.17+a.age*.055+(config.scenario==='surge'?.07:0),.03,.98);a.uncertainty+=clamp(dt*2,0,1)*(target-a.uncertainty);
  const held=a.age>5||a.uncertainty>.72||a.occupied;
  if(held&&a.mode!=='held'){if(a.age>5){prevented++;logs.unshift({time,text:`${a.id}: edge guardian held motion · telemetry >5s old`});}a.mode='held';}
  if(!held&&a.mode==='held')a.mode='moving';
  if(a.battery<12&&a.target!==5&&!held){a.target=5;a.route=routeTo(a.x,a.z,zones[5].x,zones[5].z);}
  if(a.mode==='charging'){a.battery=Math.min(100,a.battery+dt*.45);if(a.battery>92){a.target=(parseInt(a.id.slice(2))+a.tasks)%5;a.route=routeTo(a.x,a.z,zones[a.target].x,zones[a.target].z);a.mode='moving';}}
  if(a.mode==='moving'&&!held){const next=a.route[0];if(next){const dx=next.x-a.x,dz=next.z-a.z,dist=Math.hypot(dx,dz);const spacing=prev.assets.some(o=>o.id!==a.id&&Math.hypot(o.x-a.x,o.z-a.z)<.55&&o.id<a.id);const speed=(a.type==='robot'?.7:.45)*(config.scenario==='surge'?.65:1)*(spacing?.08:1),travel=Math.min(dist,speed*dt);if(dist>.01){a.x+=dx/dist*travel;a.z+=dz/dist*travel;a.heading=Math.atan2(dx,dz);}a.battery=Math.max(0,a.battery-dt*(a.type==='robot'?.018:.009));if(dist<.09)a.route.shift();}else if(a.target===5){a.mode='charging';}else{tasks++;a.tasks++;a.target=(a.target+1+(parseInt(a.id.slice(2))%3))%5;const t=zones[a.target];a.route=routeTo(a.x,a.z,t.x,t.z);}}
  a.battery=clamp(a.battery,0,100);return a;
 });return{...prev,time,assets,energy,packets,bytes,tasks,prevented,log:logs.slice(0,10)};
}
export function metrics(sim:Sim){return{moving:sim.assets.filter(a=>a.mode==='moving').length,held:sim.assets.filter(a=>a.mode==='held').length,charging:sim.assets.filter(a=>a.mode==='charging').length,uncertain:sim.assets.filter(a=>a.uncertainty>.3).length,meanBattery:sim.assets.reduce((s,a)=>s+a.battery,0)/sim.assets.length,power:sim.time?sim.energy/sim.time:0};}
