export type Sensor='rfid'|'uwb'|'vision'|'imu'|'textile';
export type AssetType='robot'|'wheelchair'|'trolley'|'cleaner';
export type Point={x:number;z:number};
export const zones=[{id:'arrivals',name:'Arrivals',x:-15,z:5},{id:'checkin',name:'Check-in',x:-8,z:-5},{id:'security',name:'Security',x:0,z:-5},{id:'gates',name:'Gate lounges',x:13,z:-5},{id:'baggage',name:'Baggage hall',x:9,z:5},{id:'charge',name:'Service & charging',x:-9,z:5}];
export type SensorTelemetry={attempts:number;successes:number;failures:number;energy:number;lastAttempt:number;result:'waiting'|'received'|'lost'|'off';hz:number;reason:string};
export type Sample={time:number;age:number;uncertainty:number;battery:number;energy:number;received:number;lost:number;x:number;z:number;sensors:Record<Sensor,'received'|'lost'|'quiet'|'off'>};
export type Asset={id:string;type:AssetType;x:number;z:number;target:number;route:Point[];routeKind:'auto'|'manual';battery:number;uncertainty:number;age:number;mode:'moving'|'charging'|'held'|'idle';last:Record<Sensor,number>;health:Record<Sensor,boolean>;telemetry:Record<Sensor,SensorTelemetry>;history:Sample[];trace:Point[];tasks:number;heading:number;packets:number;occupied:boolean};
export type Sim={time:number;assets:Asset[];energy:number;packets:number;bytes:number;tasks:number;log:{time:number;text:string}[];seed:number;requests:number;prevented:number};
export type Config={policy:'adaptive'|'fixed';scenario:'baseline'|'surge'|'dropout'|'occlusion'|'drift'|'stale';sensors:Record<Sensor,boolean>;selected:string};
export const defaults:Config={policy:'adaptive',scenario:'baseline',sensors:{rfid:true,uwb:true,vision:true,imu:true,textile:true},selected:'R-01'};
export const sensorInfo:Record<Sensor,{name:string;role:string;hz:number;joules:number;bytes:number}>={rfid:{name:'RFID / NFC',role:'Identity at reader checkpoints',hz:.5,joules:.015,bytes:48},uwb:{name:'UWB anchors',role:'Relative position',hz:2,joules:.12,bytes:96},vision:{name:'Vision',role:'Zone occupancy and motion',hz:1,joules:.9,bytes:2048},imu:{name:'IMU',role:'Motion and tilt on the edge',hz:5,joules:.006,bytes:32},textile:{name:'E-textile patch',role:'Seat load and handle contact',hz:1,joules:.008,bytes:24}};
export const sensorKeys=Object.keys(sensorInfo) as Sensor[];
const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,v));
export function routeTo(x:number,z:number,tx:number,tz:number){return[{x,z:0},{x:tx,z:0},{x:tx,z:tz}].filter((p,i,a)=>i===0||Math.abs(p.x-a[i-1].x)+Math.abs(p.z-a[i-1].z)>.01);}
export function makeSim(seed=42,count=28):Sim {let r=seed;const random=()=>{r=(r*1664525+1013904223)>>>0;return r/4294967296;};const assets:Asset[]=[],counts:Record<AssetType,number>={robot:0,wheelchair:0,trolley:0,cleaner:0};count=clamp(Math.floor(Number.isFinite(count)?count:28),1,112);for(let i=0;i<count;i++){const slot=i%28,type:AssetType=slot<8?'robot':slot<14?'wheelchair':slot<24?'trolley':'cleaner',prefix={robot:'R',wheelchair:'W',trolley:'T',cleaner:'C'}[type],n=++counts[type],x=-16+random()*32,z=(i%2?1:-1)*(2.4+random()*3.5),target=i%5;const telemetry=Object.fromEntries(sensorKeys.map(s=>[s,{attempts:0,successes:0,failures:0,energy:0,lastAttempt:-10,result:'waiting',hz:0,reason:'Waiting for first poll'}])) as Record<Sensor,SensorTelemetry>;assets.push({id:`${prefix}-${String(n).padStart(2,'0')}`,type,x,z,target,route:routeTo(x,z,zones[target].x,zones[target].z),routeKind:'auto',battery:48+random()*48,uncertainty:.08,age:0,mode:'moving',last:{rfid:-10,uwb:-10,vision:-10,imu:-10,textile:-10},health:{rfid:true,uwb:true,vision:true,imu:true,textile:true},telemetry,history:[],trace:[{x,z}],tasks:0,heading:0,packets:0,occupied:type==='wheelchair'&&i%2===0});}return{time:0,assets,energy:0,packets:0,bytes:0,tasks:0,log:[{time:0,text:`Terminal 01 ready · ${count} assets · seed ${seed}`}],seed,requests:0,prevented:0};}
export function log(sim:Sim,text:string):Sim{return{...sim,log:[{time:sim.time,text},...sim.log].slice(0,16)};}
export function guardReason(a:Asset){return a.occupied?'Seat occupied: human assistance required':a.age>5?'Position older than 5 seconds':a.uncertainty>.72?'Uncertainty above the motion limit':a.battery<12?'Low battery: service route only':null;}
export function dispatch(sim:Sim,id:string,zone:number):Sim {const a=sim.assets.find(a=>a.id===id);if(!a||!zones[zone])return sim;const reason=guardReason(a);if(reason)return log({...sim,prevented:sim.prevented+1},`${id}: dispatch refused · ${reason.toLowerCase()}`);const t=zones[zone];return log({...sim,requests:sim.requests+1,assets:sim.assets.map(v=>v.id===id?{...v,target:zone,mode:'moving',routeKind:'auto',route:routeTo(v.x,v.z,t.x,t.z)}:v)},`${id}: dispatch → ${t.name}`);}
/** Custom instructions remain constrained to the illustrative central corridor. */
export function planRoute(sim:Sim,id:string,waypoints:Point[]):Sim{const a=sim.assets.find(a=>a.id===id);if(!a)return sim;if(!waypoints.length||waypoints.length>12||waypoints.some(p=>!Number.isFinite(p.x)||!Number.isFinite(p.z)||Math.abs(p.x)>17||Math.abs(p.z)>6.5))return log(sim,`${id}: route needs 1–12 points inside the terminal`);const reason=guardReason(a);if(reason)return log({...sim,prevented:sim.prevented+1},`${id}: custom route refused · ${reason.toLowerCase()}`);let last:Point=a;const route:Point[]=[];for(const p of waypoints){for(const q of routeTo(last.x,last.z,p.x,p.z)){const prev=route.at(-1)||a;if(Math.hypot(q.x-prev.x,q.z-prev.z)>.05)route.push(q);}last=p;}const nearest=zones.reduce((best,z,i)=>Math.hypot(z.x-last.x,z.z-last.z)<Math.hypot(zones[best].x-last.x,zones[best].z-last.z)?i:best,0);return log({...sim,requests:sim.requests+1,assets:sim.assets.map(v=>v.id===id?{...v,route,routeKind:'manual',target:nearest,mode:'moving'}:v)},`${id}: custom route armed · ${waypoints.length} stops · corridor constrained`);}
export function cancelRoute(sim:Sim,id:string){return log({...sim,assets:sim.assets.map(a=>a.id===id?{...a,route:[],routeKind:'manual' as const,mode:'idle' as const}:a)},`${id}: route cancelled · holding position`);}
export function reposition(sim:Sim,id:string,x:number,z:number):Sim{if(!Number.isFinite(x)||!Number.isFinite(z))return sim;x=clamp(x,-17,17);z=clamp(z,-6.5,6.5);return log({...sim,assets:sim.assets.map(a=>a.id===id?{...a,x,z,mode:'idle',route:[],routeKind:'manual',trace:[{x,z}],age:0}:a)},`${id}: moved in layout editor`);}
export function sensingDecision(a:Asset,config:Config,s:Sensor){const info=sensorInfo[s],affected=a.id===config.selected,enabled=config.sensors[s]&&a.health[s];let hz=info.hz,reason='Fixed polling: same rate regardless of evidence';if(config.policy==='adaptive'){const uncertain=s==='vision'?a.uncertainty>.3:a.uncertainty>.25;hz*=s==='vision'?(uncertain?.8:.12):s==='uwb'?(uncertain?1:.22):a.mode==='charging'?.15:.5;reason=s==='vision'||s==='uwb'?(uncertain?'Uncertainty rising: ask for more location evidence':'State clear: reduce expensive location polls'):a.mode==='charging'?'Charging: reduce background sensing':'Normal edge sampling';}if(!enabled)return{hz:0,enabled:false,success:false,reason:!config.sensors[s]?'Network switched off':'Device switched off'};const blocked=config.scenario==='stale'&&affected||s==='rfid'&&config.scenario==='dropout'||s==='uwb'&&config.scenario==='drift'&&affected||s==='vision'&&config.scenario==='occlusion'&&a.x>0;return{hz,enabled:true,success:!blocked,reason:blocked?config.scenario==='stale'?'Telemetry link unavailable':s==='rfid'?'RFID reader blackout':s==='uwb'?'Drift: position rejected':'Camera occluded':reason};}
export function step(prev:Sim,config:Config,dt:number):Sim{
 if(!Number.isFinite(dt))return prev;dt=clamp(dt,0,1);const time=prev.time+dt;let energy=prev.energy,packets=prev.packets,bytes=prev.bytes,tasks=prev.tasks,prevented=prev.prevented;const logs=[...prev.log];
 const assets=prev.assets.map(original=>{const a:Asset={...original,route:original.route.map(p=>({...p})),last:{...original.last},health:{...original.health},telemetry:Object.fromEntries(sensorKeys.map(s=>[s,{...original.telemetry[s]}])) as Record<Sensor,SensorTelemetry>,history:[...original.history],trace:[...original.trace]};let locationFresh=false;
  for(const s of sensorKeys){const decision=sensingDecision(a,config,s),info=sensorInfo[s],telemetry=a.telemetry[s];telemetry.hz=decision.hz;telemetry.reason=decision.reason;if(!decision.enabled){telemetry.result='off';continue;}if(time-telemetry.lastAttempt>=1/decision.hz){telemetry.lastAttempt=time;telemetry.attempts++;telemetry.energy+=info.joules;energy+=info.joules;if(decision.success){telemetry.result='received';telemetry.successes++;a.last[s]=time;packets++;a.packets++;bytes+=info.bytes;if(s==='uwb'||s==='vision'||s==='rfid'&&Math.abs(a.z)>3.5)locationFresh=true;}else{telemetry.result='lost';telemetry.failures++;}}}
  if(locationFresh)a.age=0;else a.age+=dt;
  const count=(['uwb','vision','rfid'] as Sensor[]).filter(s=>{const d=sensingDecision(a,config,s);return d.enabled&&d.success;}).length;
  const target=clamp(.055+(3-count)*.17+a.age*.055+(config.scenario==='surge'?.07:0),.03,.98);a.uncertainty+=clamp(dt*2,0,1)*(target-a.uncertainty);
  const held=a.age>5||a.uncertainty>.72||a.occupied;
  if(held&&a.mode!=='held'){if(a.age>5){prevented++;logs.unshift({time,text:`${a.id}: edge guardian held motion · telemetry >5s old`});}a.mode='held';}
  if(!held&&a.mode==='held')a.mode=a.route.length?'moving':'idle';
  if(a.battery<12&&(a.target!==5||a.routeKind==='manual')&&!held){a.target=5;a.routeKind='auto';a.route=routeTo(a.x,a.z,zones[5].x,zones[5].z);a.mode='moving';logs.unshift({time,text:`${a.id}: low battery · replaced route with charging return`});}
  if(a.mode==='charging'){a.battery=Math.min(100,a.battery+dt*.45);if(a.battery>92){a.target=(parseInt(a.id.slice(2))+a.tasks)%5;a.routeKind='auto';a.route=routeTo(a.x,a.z,zones[a.target].x,zones[a.target].z);a.mode='moving';}}
  if(a.mode==='moving'&&!held){const next=a.route[0];if(next){const dx=next.x-a.x,dz=next.z-a.z,dist=Math.hypot(dx,dz);const spacing=prev.assets.some(o=>o.id!==a.id&&Math.hypot(o.x-a.x,o.z-a.z)<.55&&o.id<a.id);const speed=(a.type==='robot'?.7:.45)*(config.scenario==='surge'?.65:1)*(spacing?.08:1),travel=Math.min(dist,speed*dt);if(dist>.01){a.x+=dx/dist*travel;a.z+=dz/dist*travel;a.heading=Math.atan2(dx,dz);}a.battery=Math.max(0,a.battery-dt*(a.type==='robot'?.018:.009));if(dist<.09)a.route.shift();}else if(a.routeKind==='manual'){tasks++;a.tasks++;a.mode='idle';}else if(a.target===5){a.mode='charging';}else{tasks++;a.tasks++;a.target=(a.target+1+(parseInt(a.id.slice(2))%3))%5;const t=zones[a.target];a.route=routeTo(a.x,a.z,t.x,t.z);}}
  a.battery=clamp(a.battery,0,100);
  if(!a.history.length||time-a.history[a.history.length-1].time>=1-1e-8){const before=a.history.at(-1),totals=sensorKeys.reduce((v,s)=>({energy:v.energy+a.telemetry[s].energy,received:v.received+a.telemetry[s].successes,lost:v.lost+a.telemetry[s].failures}),{energy:0,received:0,lost:0});const status=Object.fromEntries(sensorKeys.map(s=>[s,a.telemetry[s].result==='off'?'off':a.telemetry[s].lastAttempt>(before?.time??-1)?a.telemetry[s].result==='lost'?'lost':'received':'quiet'])) as Sample['sensors'];a.history.push({time,age:a.age,uncertainty:a.uncertainty,battery:a.battery,...totals,x:a.x,z:a.z,sensors:status});a.history=a.history.slice(-90);if(!a.trace.length||Math.hypot(a.x-a.trace[a.trace.length-1].x,a.z-a.trace[a.trace.length-1].z)>.04)a.trace.push({x:a.x,z:a.z});a.trace=a.trace.slice(-180);}
  return a;
 });return{...prev,time,assets,energy,packets,bytes,tasks,prevented,log:logs.slice(0,16)};
}
export function metrics(sim:Sim){return{moving:sim.assets.filter(a=>a.mode==='moving').length,held:sim.assets.filter(a=>a.mode==='held').length,charging:sim.assets.filter(a=>a.mode==='charging').length,uncertain:sim.assets.filter(a=>a.uncertainty>.3).length,meanBattery:sim.assets.reduce((s,a)=>s+a.battery,0)/sim.assets.length,power:sim.time?sim.energy/sim.time:0};}
