'use client';
import {Compass,ArrowUpRight,Moon,Sun,Sparkles,Eye} from 'lucide-react';
import {angularSeparation,bearingName,nearestPattern,skyPatterns,type Aim,type RoomMood} from './sky';
export function AimPanel({aim,onAim,mood,onMood,view,onView,guides,onGuides}:{aim:Aim;onAim:(a:Aim)=>void;mood:RoomMood;onMood:(m:RoomMood)=>void;view:string;onView:(v:string)=>void;guides:boolean;onGuides:(v:boolean)=>void}){
 const near=nearestPattern(aim),distance=angularSeparation(aim,near);
 return <aside className="aim-panel" aria-label="Telescope pointing and room lighting">
 <header><Compass size={15}/><span>YOUR WINDOW INTO THE NIGHT</span></header><h2>Choose a direction.</h2>
 <div className="pointing-dial"><svg viewBox="0 0 140 140" role="img" aria-label={`Telescope points ${Math.round(aim.azimuth)} degrees ${bearingName(aim.azimuth)}, ${Math.round(aim.altitude)} degrees above the horizon`}><circle cx="70" cy="70" r="47"/><circle cx="70" cy="70" r="33" className="dial-inner"/>{[0,90,180,270].map((a,i)=><text key={a} x={70+Math.sin(a*Math.PI/180)*61} y={74-Math.cos(a*Math.PI/180)*61}>{['N','E','S','W'][i]}</text>)}<g transform={`rotate(${aim.azimuth} 70 70)`}><path d="M70 25 L76 49 L70 44 L64 49 Z"/><line x1="70" y1="43" x2="70" y2="80"/></g><circle cx="70" cy="70" r="3" className="dial-centre"/></svg><div><strong>{aim.azimuth.toFixed(0)}<small>° {bearingName(aim.azimuth)}</small></strong><span>FULL 360° AZIMUTH</span><strong>{aim.altitude.toFixed(0)}<small>° altitude</small></strong><span>UP FROM THE HORIZON</span></div></div>
 <label className="range-label" htmlFor="scope-azimuth">Turn around the horizon<output>{aim.azimuth.toFixed(0)}°</output><input id="scope-azimuth" type="range" min="0" max="360" step="1" value={aim.azimuth} onChange={e=>onAim({...aim,azimuth:+e.target.value})}/></label>
 <label className="range-label" htmlFor="scope-altitude">Raise or lower the tube<output>{aim.altitude.toFixed(0)}°</output><input id="scope-altitude" type="range" min="-5" max="85" step="1" value={aim.altitude} onChange={e=>onAim({...aim,altitude:+e.target.value})}/></label>
 <div className="aim-view-toggle"><button aria-pressed={view==='sky'} onClick={()=>onView(view==='sky'?'room':'sky')}><Eye size={14}/>{view==='sky'?'Return to the room':'Look at the sky'}<ArrowUpRight size={13}/></button><button aria-pressed={guides} onClick={()=>onGuides(!guides)}>Star guides {guides?'on':'off'}</button></div>
 <p className="aim-hint">{view==='sky'?'Drag the sky to aim. This wide finder shows patterns; use the optical bench for magnified planet studies.':'Drag around the telescope to inspect its mount. Arrow keys aim; the room stays still while the tube turns.'}</p>
 <div className="aim-section-title">FIND A FAMILIAR PATTERN</div><div className="constellation-targets">{skyPatterns.map(p=><button key={p.id} aria-pressed={distance<3&&near.id===p.id} onClick={()=>{onAim({azimuth:p.azimuth,altitude:p.altitude});onView('sky');}}>{p.name}<ArrowUpRight size={11}/></button>)}</div>
 <p className="pattern-story"><strong>{distance<18?`Near ${near.name}`:'Between the patterns'}</strong>{distance<18?near.story:'Sweep the horizon or choose a star pattern. Your bearing and elevation move the telescope and its sky view together.'}</p>
 <div className="aim-section-title">THE ROOM, AFTER DARK</div><div className="room-moods">{([['moonlit','Moonlit',Moon],['lamplight','Lamplight',Sun],['aurora','Blue hour',Sparkles]]as const).map(([id,label,Icon])=><button key={id} aria-pressed={mood===id} onClick={()=>onMood(id)}><Icon size={13}/>{label}</button>)}</div>
 <p className="sky-model-note">A composed teaching sky. Pattern shapes and bearings are illustrative, not tonight’s sky at your location. The wide sky view removes the room so walls do not hide the lesson. <a href="https://spaceplace.nasa.gov/constellations/en/" target="_blank" rel="noreferrer">About constellations ↗</a></p>
 </aside>;
}
