'use client';
import {useEffect,useMemo,useRef} from 'react';
import {Pause,Play,X,RotateCcw} from 'lucide-react';
import type {LabState} from '../optics';
import {advanceRayTime,initialRays,rayColors,rayExperiment,type RaySettings} from './ray-optics';

type Props={state:LabState;settings:RaySettings;onState:(s:Partial<LabState>)=>void;onSettings:(s:RaySettings)=>void;onClose:()=>void};
function Range({label,value,min,max,step=1,unit,onChange}:{label:string;value:number;min:number;max:number;step?:number;unit:string;onChange:(v:number)=>void}){return <label className="ray-range"><span>{label}<output>{Number.isInteger(value)?value:value.toFixed(1)} {unit}</output></span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/></label>;}
function RayCanvas({state,settings}:{state:LabState;settings:RaySettings}){
 const canvas=useRef<HTMLCanvasElement>(null),model=useMemo(()=>rayExperiment(state,settings),[state.scope,state.focal,state.aperture,state.mirror,settings]),current=useRef({state,settings,model});current.current={state,settings,model};
 useEffect(()=>{
  const c=canvas.current!,ctx=c.getContext('2d')!;let raf=0,last=0,time=0,w=800,h=340,dirty=true;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const resize=()=>{const rect=c.getBoundingClientRect();w=rect.width;h=rect.height;const dpr=Math.min(devicePixelRatio,2);c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);dirty=true;};const ro=new ResizeObserver(resize);ro.observe(c);resize();
  let drawn:typeof current.current|null=null;
  function draw(t:number){raf=requestAnimationFrame(draw);if(t-last<30)return;const dt=(t-last)/1000;last=t;const {state:s,settings:r,model:m}=current.current;time=advanceRayTime(time,dt,s.motion,reduced);if(document.hidden)return;if(!dirty&&drawn===current.current&&(!s.motion||reduced))return;dirty=false;drawn=current.current;
   ctx.clearRect(0,0,w,h);const bg=ctx.createLinearGradient(0,0,w,h);bg.addColorStop(0,'#071520');bg.addColorStop(1,'#0a1d27');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);
   const compact=w<610,rayW=compact?w:w*.72,rayH=compact?h*.6:h,spotX=compact?w*.5:rayW+(w-rayW)/2,spotY=compact?rayH+(h-rayH)*.47:h*.5,spotR=compact?Math.min(62,(h-rayH)*.32):Math.min(86,(w-rayW)*.37),left=24,right=rayW-22,top=57,bottom=rayH-45,center=(top+bottom)/2;
   const extent=Math.max(m.plane,m.image)*1.22, x=(q:number)=>left+(q+s.focal*.4)/(extent+s.focal*.4)*(right-left), ys=(bottom-top)/Math.max(s.aperture*1.45,200),y=(q:number)=>center-q*ys;
   function line(points:number[][],color:string,width=1){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
   function text(str:string,px:number,py:number,color='#a6bec9',align:CanvasTextAlign='left',size=10){ctx.font=`${size}px ui-monospace,monospace`;ctx.fillStyle=color;ctx.textAlign=align;ctx.fillText(str,px,py);}
   text(s.scope==='reflector'?'PRIMARY MIRROR · RETURN PATH UNFOLDED':'OBJECTIVE LENS · LIGHT TRAVELS →',left,24,'#cfddda', 'left',w<460?8:10);
   text(r.source==='near'?`LAMP AT ${m.objectDistance.toFixed(0)} mm`:r.source==='offaxis'?`STAR ${r.angle.toFixed(1)}° OFF AXIS`:'DISTANT STAR · PARALLEL LIGHT',left,41,'#779cae','left',8);
   ctx.save();ctx.beginPath();ctx.rect(left,top-12,right-left,bottom-top+24);ctx.clip();
   ctx.setLineDash([3,7]);line([[left,center],[right,center]],'#7998a343');ctx.setLineDash([]);
   const pupil=s.aperture*.5;
   ctx.fillStyle='#8acee716';ctx.strokeStyle='#aed8e2a8';ctx.lineWidth=2;ctx.beginPath();
   if(s.scope==='refractor'){ctx.moveTo(x(0),y(pupil));ctx.bezierCurveTo(x(0)-17,y(pupil*.45),x(0)-17,y(-pupil*.45),x(0),y(-pupil));ctx.bezierCurveTo(x(0)+17,y(-pupil*.45),x(0)+17,y(pupil*.45),x(0),y(pupil));ctx.fill();ctx.stroke();if(r.lens==='achromat'){line([[x(0),y(pupil)],[x(0),y(-pupil)]],'#e4c394aa');}}
   else{ctx.moveTo(x(0)+8,y(pupil));ctx.quadraticCurveTo(x(0)-9,center,x(0)+8,y(-pupil));ctx.stroke();}
   const end=extent,paths=m.rays.filter(ray=>ray.meridional);
   for(const [index,ray] of paths.entries()){
    const physicalStart=-s.focal*.4,startY=ray.hit[1]+(physicalStart-ray.hit[0])*ray.incoming[1]/ray.incoming[0],physicalEnd=s.scope==='reflector'?-end:end,endY=ray.hit[1]+(physicalEnd-ray.hit[0])*ray.outgoing[1]/ray.outgoing[0],hitX=s.scope==='reflector'?-ray.hit[0]:ray.hit[0],points=[[x(physicalStart),y(startY)],[x(hitX),y(ray.hit[1])],[x(end),y(endY)]],color=rayColors[ray.nm];
    line(points,color+'68',1);const lengths=[Math.hypot(points[1][0]-points[0][0],points[1][1]-points[0][1]),Math.hypot(points[2][0]-points[1][0],points[2][1]-points[1][1])];
    for(let k=0;k<2;k++){let d=((time*.18+index*.047+k*.5)%1)*(lengths[0]+lengths[1]);const segment=d>lengths[0]?1:0;if(segment)d-=lengths[0];const f=d/lengths[segment],px=points[segment][0]+(points[segment+1][0]-points[segment][0])*f,py=points[segment][1]+(points[segment+1][1]-points[segment][1])*f;ctx.shadowBlur=8;ctx.shadowColor=color;ctx.fillStyle=color;ctx.beginPath();ctx.arc(px,py,1.65,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}
   }
   ctx.setLineDash([3,4]);line([[x(m.image),top],[x(m.image),bottom]],'#a4bcc44a');ctx.setLineDash([]);line([[x(m.plane),top-6],[x(m.plane),bottom+6]],'#f6d493',1.5);
   ctx.restore();text('PRIMARY',x(0),bottom+22,'#c2d8d9','center',8);text(`${m.plane.toFixed(0)} mm`,x(m.plane),bottom+22,'#f2d396','center',9);text('DETECTOR',x(m.plane),bottom+35,'#b29f80','center',7);
   if(!compact)line([[rayW,53],[rayW,h-34]],'#b6d2d321');
   text('WHAT REACHES THE DETECTOR',spotX,compact?rayH+12:24,'#cfddda','center',compact?8:9);
   const scale=Math.max(m.radius*1.2,m.airy*2,.03),spotScale=spotR/scale;
   for(const frac of[.5,1]){ctx.beginPath();ctx.arc(spotX,spotY,spotR*frac,0,Math.PI*2);ctx.strokeStyle='#91b8c329';ctx.lineWidth=1;ctx.stroke();}
   line([[spotX-spotR,spotY],[spotX+spotR,spotY]],'#86a9b525');line([[spotX,spotY-spotR],[spotX,spotY+spotR]],'#86a9b525');
   ctx.setLineDash([2,3]);ctx.beginPath();ctx.arc(spotX,spotY,Math.max(1,m.airy*spotScale),0,Math.PI*2);ctx.strokeStyle='#edd59a9a';ctx.stroke();ctx.setLineDash([]);
   for(const ray of m.rays){ctx.fillStyle=rayColors[ray.nm]+'b8';ctx.beginPath();ctx.arc(spotX+(ray.spot[0]-m.centroid[0])*spotScale,spotY+(ray.spot[1]-m.centroid[1])*spotScale,1.65,0,Math.PI*2);ctx.fill();}
   text(`RADIUS ${scale<.1?(scale*1000).toFixed(0)+' µm':scale.toFixed(2)+' mm'}`,spotX,spotY+spotR+16,'#b9c7c7','center',8);text('AUTO-ZOOM · CENTERED ON RAY CENTROID',spotX,spotY+spotR+30,'#7c9fac','center',compact?7:6.5);
   text('Rays are sampled paths. Vertical ray scale is expanded.',left,h-10,'#7997a6','left',w<460?7:8);
  }raf=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(raf);ro.disconnect();};
 },[]);
 return <canvas ref={canvas} className="ray-bench-canvas" role="img" aria-label="Optical ray diagram and geometric detector spot. Blue, green and red paths show where each wavelength comes to focus."/>;
}
export function RayBench({state,settings,onState,onSettings,onClose}:Props){
 const m=useMemo(()=>rayExperiment(state,settings),[state.scope,state.focal,state.aperture,state.mirror,settings]);const set=(p:Partial<RaySettings>)=>onSettings({...settings,...p});
 function preset(which:string){onState({focus:0,rays:true,scope:which==='color'||which==='correct'?'refractor':'reflector',focal:which==='color'||which==='correct'?600:400,aperture:which==='color'||which==='correct'?150:250,mirror:which==='sphere'?'spherical':'parabolic'});onSettings({...initialRays,lens:which==='correct'?'achromat':'singlet',dispersion:2.5,source:which==='coma'?'offaxis':'star',angle:3});}
 const insight=state.scope==='reflector'?(settings.source==='offaxis'?'An off-axis bundle forms a comet-shaped spot. A paraboloid fixes on-axis spherical aberration; it does not remove off-axis coma.':state.mirror==='spherical'?'Edge rays return to a different focus than central rays. Open the aperture to see spherical aberration grow.':settings.source==='near'?'A paraboloid has a shared focus for parallel light. A nearby lamp sends a divergent bundle, so that perfect on-axis condition no longer applies.':'Parallel light returns to one geometric focus. Reflection has no glass dispersion, so the three colors follow the same paths.'):settings.lens==='achromat'?'Two opposite-power glasses bring blue and red to the same focus. Green retains a small residual: an achromat does not make every color identical.':settings.lens==='ideal'?'This ideal thin lens brings one on-axis bundle to a shared point. Move the detector away and that point spreads into a circle.':'Glass bends different wavelengths by different amounts. Blue has a shorter focal length here; the detector cannot focus all three colors at once.';
 return <aside className="ray-bench" aria-label="Ray experiments"><header><div><span className="eyebrow">THE LIGHT BENCH</span><h2>Follow a ray. <em>Find the difference.</em></h2></div><button className="ray-close" onClick={onClose} aria-label="Close ray experiments"><X size={18}/></button></header>
 <div className="ray-presets" aria-label="Optical experiments"><button onClick={()=>preset('color')}>Split white light</button><button onClick={()=>preset('correct')}>Correct the color</button><button onClick={()=>preset('sphere')}>Spherical edge rays</button><button onClick={()=>preset('coma')}>Find off-axis coma</button></div>
 <RayCanvas state={state} settings={settings}/><div className="ray-transport"><span>{state.motion?'Following the light':'Rays frozen in place'}</span><button aria-pressed={!state.motion} onClick={()=>onState({motion:!state.motion})}>{state.motion?<Pause size={13}/>:<Play size={13}/>} {state.motion?'Pause rays':'Resume rays'}</button><button onClick={()=>set({detector:0})}><RotateCcw size={12}/> Paraxial focus</button></div>
 <div className="ray-metrics" aria-live="polite"><div><span>Geometric RMS spot</span><strong>{m.rms<.01?(m.rms*1000).toFixed(1)+' µm':m.rms.toFixed(3)+' mm'}</strong></div><div><span>Spectral focal spread</span><strong>{m.colorSpread.toFixed(3)} mm</strong></div><div><span>Nominal image distance</span><strong>{m.image.toFixed(1)} mm</strong></div></div>
 <p className="ray-discovery">{insight}</p>
 <div className="ray-controls"><div><label>Primary optic<select aria-label="Ray bench primary optic" value={state.scope} onChange={e=>onState({scope:e.target.value as LabState['scope']})}><option value="refractor">Lens · refracts light</option><option value="reflector">Mirror · reflects light</option></select></label>{state.scope==='refractor'?<label>Lens design<select aria-label="Lens design" value={settings.lens} onChange={e=>set({lens:e.target.value as RaySettings['lens']})}><option value="ideal">Ideal thin lens</option><option value="singlet">Singlet · one glass</option><option value="achromat">Achromat · two glasses</option></select></label>:<label>Mirror figure<select aria-label="Ray bench mirror figure" value={state.mirror} onChange={e=>onState({mirror:e.target.value as LabState['mirror']})}><option value="parabolic">Parabolic</option><option value="spherical">Spherical</option></select></label>}<Range label="Objective focal length" value={state.focal} min={400} max={1600} step={50} unit="mm" onChange={focal=>onState({focal})}/><Range label="Objective aperture" value={state.aperture} min={60} max={250} step={10} unit="mm" onChange={aperture=>onState({aperture})}/></div>
 <div><label>Light source<select aria-label="Light source" value={settings.source} onChange={e=>set({source:e.target.value as RaySettings['source'],detector:0})}><option value="star">Distant star · parallel rays</option><option value="near">Nearby lamp · divergent rays</option><option value="offaxis">Off-axis star · tilted bundle</option></select></label><label>Light color<select aria-label="Light color" value={settings.spectrum} onChange={e=>set({spectrum:e.target.value as RaySettings['spectrum']})}><option value="white">White light · 3 sample wavelengths</option><option value="blue">Blue · 486.1 nm</option><option value="green">Green · 550 nm</option><option value="red">Red · 656.3 nm</option></select></label>{settings.source==='near'&&<Range label="Lamp distance" value={settings.distance} min={2} max={10} step={.5} unit="× focal length" onChange={distance=>set({distance})}/>} {settings.source==='offaxis'&&<Range label="Angle from axis" value={settings.angle} min={0} max={4} step={.1} unit="°" onChange={angle=>set({angle})}/>} {state.scope==='refractor'&&settings.lens!=='ideal'&&<Range label="Glass dispersion" value={settings.dispersion} min={0} max={3} step={.1} unit="× reference" onChange={dispersion=>set({dispersion})}/>}<Range label="Detector offset" value={settings.detector} min={-60} max={60} step={.5} unit="mm" onChange={detector=>set({detector})}/></div></div>
 <details className="ray-model"><summary>What the experiment calculates</summary><p>Lenses use paraxial thin-lens power with illustrative wavelength-dependent glass indices. The achromat combines two glass powers to align 486.1 and 656.3 nm; it retains a secondary color error. Lens shape aberrations are omitted. The spectral focal spread is the range of focal lengths across the three sampled wavelengths, even with a single color selected.</p><p>Mirror rays use the law of reflection on a sphere (radius 2F) or a paraboloid. The return beam is unfolded to the right for comparison; the telescope’s secondary and eyepiece are omitted here. Off-axis mirror spots include the aberrations of that surface, predominantly coma at these small angles. The nearby-lamp focus uses 1/F = 1/object + 1/image as its reference.</p><p>The detector shows sampled geometric intersections, with automatic scale and centroid centering. Its dashed gold circle is a 550 nm diffraction-size reference at the nominal focal ratio, not a finite-distance prediction. This is not a wave-optics image; diffraction, seeing and coating losses are absent from this bench. The planet preview uses its separate, qualitative telescope model. Photon speed is illustrative.</p><p><a href="https://openstax.org/books/university-physics-volume-3/pages/2-4-thin-lenses" target="_blank" rel="noreferrer">Thin-lens equation ↗</a><a href="https://www.edmundoptics.com/knowledge-center/application-notes/optics/chromatic-and-monochromatic-optical-aberrations/" target="_blank" rel="noreferrer">Color and shape aberrations ↗</a></p></details>
 </aside>;
}
