import * as T from 'three';
import {skyDirection,skyPatterns,type RoomMood} from './sky';
/** A composed, non-ephemeris sky for learning mount coordinates and recognition. */
export function teachingSky(scene:T.Scene){
 const root=new T.Group(),guides=new T.Group();scene.add(root);root.add(guides);
 const skyMaterial=new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{glow:{value:new T.Color(0x12283d)}},vertexShader:'varying vec3 p;void main(){p=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 p;uniform vec3 glow;void main(){float h=normalize(p).y;vec3 c=mix(glow,vec3(.003,.008,.022),smoothstep(-.08,.7,h));gl_FragColor=vec4(c,1.);}'});
 root.add(new T.Mesh(new T.SphereGeometry(68,48,32),skyMaterial));
 let seed=814;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
 const dots:number[]=[],colors:number[]=[];
 // Sample sine-altitude within its physical domain, from just below the horizon to zenith.
 for(let i=0;i<2400;i++){const az=random()*360,alt=Math.asin(random()*1.22-.22)*180/Math.PI,p=skyDirection(az,alt);dots.push(...p.map(v=>v*64));const bright=.4+random()*.6;colors.push(bright*.8,bright*.9,bright);}
 const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(dots,3));geo.setAttribute('color',new T.Float32BufferAttribute(colors,3));root.add(new T.Points(geo,new T.PointsMaterial({size:1.6,vertexColors:true,sizeAttenuation:false,transparent:true,opacity:.92,toneMapped:false})));
 const band:number[]=[];for(let i=0;i<1600;i++){const a=random()*Math.PI*2,b=(random()+random()+random()-1.5)*.11;const p=new T.Vector3(Math.cos(a),Math.sin(a)*.68+b,Math.sin(a)*.73).normalize().multiplyScalar(63);band.push(...p.toArray());}
 const bandGeo=new T.BufferGeometry();bandGeo.setAttribute('position',new T.Float32BufferAttribute(band,3));root.add(new T.Points(bandGeo,new T.PointsMaterial({color:0x9babdf,size:1.1,sizeAttenuation:false,transparent:true,opacity:.3,depthWrite:false,toneMapped:false})));
 const textures:T.Texture[]=[];const starCanvas=document.createElement('canvas');starCanvas.width=64;starCanvas.height=64;const starCtx=starCanvas.getContext('2d')!,starGradient=starCtx.createRadialGradient(32,32,0,32,32,31);starGradient.addColorStop(0,'#ffffff');starGradient.addColorStop(.16,'#fff6e9');starGradient.addColorStop(.35,'#b8d9ffb3');starGradient.addColorStop(.7,'#81b8fa35');starGradient.addColorStop(1,'#80b7ff00');starCtx.fillStyle=starGradient;starCtx.fillRect(0,0,64,64);const starTexture=new T.CanvasTexture(starCanvas);textures.push(starTexture);
 function text(label:string,position:T.Vector3,color='#b9d7e8',width=9){const c=document.createElement('canvas');c.width=512;c.height=80;const ctx=c.getContext('2d')!;ctx.font='400 28px monospace';ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(label,256,50);const texture=new T.CanvasTexture(c);textures.push(texture);const sprite=new T.Sprite(new T.SpriteMaterial({map:texture,transparent:true,depthWrite:false}));sprite.position.copy(position);sprite.scale.set(width,width*.156,1);guides.add(sprite);}
 for(const pattern of skyPatterns){const vertices=pattern.stars.map(([x,y])=>new T.Vector3(...skyDirection(pattern.azimuth+x/Math.cos(pattern.altitude*Math.PI/180),pattern.altitude+y)).multiplyScalar(62));const pointsGeo=new T.BufferGeometry().setFromPoints(vertices);root.add(new T.Points(pointsGeo,new T.PointsMaterial({color:0xfff3da,size:9,sizeAttenuation:false,map:starTexture,transparent:true,depthWrite:false,alphaTest:.006,toneMapped:false,blending:T.AdditiveBlending})));
 const links:T.Vector3[]=[];for(const[a,b]of pattern.links)links.push(vertices[a],vertices[b]);guides.add(new T.LineSegments(new T.BufferGeometry().setFromPoints(links),new T.LineBasicMaterial({color:0x90bddd,transparent:true,opacity:.55,toneMapped:false})));text(pattern.name.toUpperCase(),new T.Vector3(...skyDirection(pattern.azimuth,pattern.altitude-14)).multiplyScalar(61),'#c2d5e3',8);}
 for(const[az,label]of[[0,'NORTH · 0°'],[90,'EAST · 90°'],[180,'SOUTH · 180°'],[270,'WEST · 270°']]as const)text(label,new T.Vector3(...skyDirection(az,1)).multiplyScalar(60),'#e8c98d',10);
 const horizon=[];for(let i=0;i<=180;i++)horizon.push(new T.Vector3(...skyDirection(i*2,0)).multiplyScalar(60));guides.add(new T.Line(new T.BufferGeometry().setFromPoints(horizon),new T.LineBasicMaterial({color:0x78999f,transparent:true,opacity:.35})));
 return{root,guides,setMood(mood:RoomMood){skyMaterial.uniforms.glow.value.set(mood==='aurora'?0x164344:mood==='lamplight'?0x202438:0x12283d);},dispose(){textures.forEach(t=>t.dispose());guides.traverse(o=>{if(o instanceof T.Sprite)o.material.dispose();});}};
}
