'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,LoaderCircle,RotateCcw,Expand,ChevronUp,ChevronDown,Play} from 'lucide-react';
import {type Project} from '../projects';
import {usePulse,track} from '../activity';
import {CaptureControls} from '../components/capture';
import {WorldDock} from '../components/world-dock';
import './external-world.css';

export default function ExternalWorld({project}:{project:Project}){
 const {pulse,favorite}=usePulse(project.id),[attempt,setAttempt]=useState(0),[phase,setPhase]=useState<'loading'|'loaded'|'slow'>('loading'),[notice,setNotice]=useState(''),[help,setHelp]=useState(false),[preview,setPreview]=useState(false);
 const local=project.url?.startsWith('/games/');
 const frame=useRef<HTMLIFrameElement|null>(null);const embedded=project.embed==='frame';
 useEffect(()=>{if(!embedded)return;const poll=setInterval(()=>{try{const d=frame.current?.contentDocument;if(d&&d.URL!=='about:blank'&&d.readyState!=='loading'&&d.body?.childElementCount){setPhase('loaded');clearInterval(poll);}}catch{/* Cross-origin worlds use the frame load event. */}},300);const timer=setTimeout(()=>{clearInterval(poll);setPhase(p=>p==='loaded'?p:'slow');},18000);return()=>{clearTimeout(timer);clearInterval(poll);};},[attempt,embedded]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer);},[notice]);
 // Keep the pirate world's informational HUD quiet while retaining sailing controls.
 useEffect(()=>{
  if(project.id!=='tides'||phase!=='loaded')return;
  const doc=frame.current?.contentDocument;if(!doc)return;
  const style=doc.createElement('style');style.textContent=`#hud-layer .topbar,#heading-ribbon,#crew-chat{transition:opacity .6s}.pe-hub-rest #hud-layer .topbar:not(:hover):not(:focus-within),.pe-hub-rest #heading-ribbon:not(:hover),.pe-hub-rest #crew-chat:not(:hover):not(:focus-within){opacity:.2}@media(prefers-reduced-motion:reduce){#hud-layer .topbar,#heading-ribbon,#crew-chat{transition:none}}`;doc.head.appendChild(style);
  const sync=()=>doc.documentElement.classList.toggle('pe-hub-rest',document.body.classList.contains('hud-resting'));
  const wake=()=>window.dispatchEvent(new Event('pe-hud-wake'));
  const edge=(e:PointerEvent)=>{const h=doc.defaultView?.innerHeight||0;if(e.clientY<110||e.clientY>h-110)wake();};
  const key=(e:KeyboardEvent)=>{if(e.key==='Tab'||e.key==='Escape')wake();};
  const observer=new MutationObserver(sync);observer.observe(document.body,{attributes:true,attributeFilter:['class']});sync();doc.addEventListener('pointermove',edge,{passive:true});doc.addEventListener('keydown',key);
  return()=>{observer.disconnect();style.remove();doc.documentElement.classList.remove('pe-hub-rest');doc.removeEventListener('pointermove',edge);doc.removeEventListener('keydown',key);};
 },[project.id,phase,attempt]);
 const onFavorite=async(id:string)=>{try{const saved=await favorite(id);setNotice(saved?'A little wonder, saved.':'Removed from your favorites.');}catch(e){setNotice((e as Error).message);}};
 const guides:Record<string,{start:string;keys:string;goal:string}>={
 'plate-engine':{start:'Drag to orbit the Earth cutaway, then follow the eight stops from mantle currents to an island volcano.',keys:'Drag: orbit · Scroll or pinch: zoom · Arrow keys: orbit the focused scene · + / −: zoom · Use the stop buttons and pause control to explore',goal:'Try Break the megathrust to see a quake and tsunami. Change mantle heat, then visit the Arc to compare the volcano forecast. Distances and time are compressed for this illustrative model.'},
 'coral-memory':{start:'You enter straight into the reef. Drag to look around; click a coral to open its dossier.',keys:'Drag: orbit · Scroll or pinch: zoom · Space: timeline · T: tour · N: night dive · P: photo mode · C: save photo',goal:'Move the timeline back to 2020 and watch a simulated heatwave. Select a colony, compare its history, then pin a note. Your notes stay on this device.'},
 'edge-universe':{start:'Press Play to descend from the observable universe toward the smallest scales.',keys:'Space: play / pause · ← / →: previous / next layer · Drag the timeline or choose a named layer',goal:'Pause at any scale and compare its size. Speed controls let you take the journey at your own pace.'},
 glorp:{start:'Enter the arena and move your alien hero into position.',keys:'A / D or ← / →: move · Space: fire',goal:'Watch the boss, dodge its attacks, and find your opening. An original alien action game.'},
 skyline:{start:'Choose Skip story or follow the opening, then press Swing! to enter the city.',keys:'WASD / arrows: move · Space: jump · ↓: dive · Hold mouse or Shift: swing · E: shockwave · P: pause',goal:'Follow the city route, collect pickups, and take on missions. Hero Studio, checkpoints and the journal keep your local journey.'},
 'hollow-bloom':{start:'Click to begin. Search the pharmacy for medical supplies; keep quiet around infected enemies.',keys:'WASD: move · Shift: run · C: crouch · Hold Q: listen · E: interact · F: knife · H: heal · Tab: backpack and crafting',goal:'Find supplies and escape. Noise attracts infected enemies; ammunition is limited. Mouse: aim and attack.'},
 tides:{start:'Choose a callsign and ship, then choose Guided for your first voyage.',keys:'W / S: sail speed · A / D: steer · Q / R: broadsides · Space: bow cannon · H: all controls',goal:'Reach the first marked port. Use the sea chart to set a course; the arrow points toward your selected destination.'},
 'fable-flight':{start:'Choose Clear Circuit and press Begin Flight. Press E for departure checks, then hold W to add throttle.',keys:'W / S: throttle · ↓: nose up · ↑: nose down · ← / →: roll · A / D: rudder · Space: brake · E: checks',goal:'For the first takeoff, add full throttle and gently pull ↓ at 55 kt. Follow the training gates. This is a simulation, not flight instruction.'},
 galevein:{start:'Press Start, then Explore for free flight or Story to follow the beacon trail.',keys:'W / S: speed · ↑ / ↓: climb / dive · A / D: turn · Space: flap · V: camera · X: plasma',goal:'Gain height and follow the glowing beacons. Explore turns off the keeper hunt while you learn to fly.'},
 lightning:{start:'Press BEGIN to follow the 60-second journey, or open LIGHTNING LAB to experiment.',keys:'Pause and drag the timeline to inspect any instant. PHYSICS reveals the quantities behind the scene.',goal:'Watch charge separate, follow the stepped leader, then meet the upward streamer.'},
 'universe-clash':{start:'Pick a fighter, then choose Local Pit or a Duel against AI.',keys:'The game shows the active fighter’s controls when a match starts. Click inside the arena to focus it.',goal:'Training is the easiest first stop. Online human matchmaking is not connected in this edition.'},
 poe:{start:'Play the Masque, or choose Usher or The Raven. Chapter buttons move through the film.',keys:'Use the player to pause, scrub, and control sound.',goal:'A cinematic anthology from the original Poe project. This edition is a film journey.'},
 aeolith:{start:'Choose an AI match style and launch your ship.',keys:'Use the match’s controls panel. Click inside the arena to focus the game.',goal:'This is Meridian Clash AI practice; cloud progression and matchmaking are not connected.'}
 };const guide=guides[project.id];
 const openOriginal=()=>track('project_open',project.id);
 return <main className={`external-world ${embedded?'embedded-world':'showcase-world'}`}>
  {embedded?<div className="external-frame-wrap"><iframe key={attempt} ref={frame} className={`external-frame ${phase==='loading'?'is-loading':''}`} title={project.title} src={project.url} allow="autoplay; clipboard-write; gamepad" referrerPolicy="no-referrer" onLoad={()=>{setPhase('loaded');}} onError={()=>setPhase('slow')}/>
   {phase!=='loaded'&&<div className="world-arrival" aria-live="polite">{project.image&&<img className="arrival-image" src={project.image} alt=""/>}<div className="arrival-curtain"/><div className="arrival-orbit"/>{phase==='loading'&&<LoaderCircle className="arrival-spinner" size={24}/>}<span className="eyebrow">ENTERING YOUR NEXT WORLD</span><h1>{project.title}</h1><p>{phase==='loading'?'Opening the scene…':'This world is taking longer to answer.'}</p>{phase==='slow'&&<div className="arrival-actions"><button onClick={()=>(setPhase('loading'),setAttempt(v=>v+1))}><RotateCcw size={15}/>Try again</button><a href={project.url} target="_blank" rel="noreferrer" onClick={openOriginal}>Open original <ArrowUpRight size={15}/></a></div>}</div>}
  </div>:<div className={`external-showcase art-${project.art}`}><div className="showcase-orbits"><i/><i/><i/></div><div className="showcase-grain"/>{project.trailer?<video className="showcase-film" src={project.trailer} autoPlay={preview} muted loop playsInline controls={preview}/>:project.image?<img className="showcase-film" src={project.image} alt=""/>:null}<article className="showcase-story"><span className="eyebrow">{project.tag}</span><h1>{project.title}</h1><p>{project.subtitle}</p>{project.edition&&<p className="world-edition">{project.edition}</p>}<a className="showcase-enter" href={project.url} target="_blank" rel="noreferrer" onClick={openOriginal}>{project.kind==='showcase'?'Watch the original film':project.id==='tokenbar'?'Explore the source': 'Open this world'} <ArrowUpRight size={19}/></a><small>{project.kind==='showcase'?'The film opens on X. Your next door stays here.':'Opens in another tab. Come back here to continue your journey.'}</small>{project.trailer&&<button className="showcase-preview" onClick={()=>setPreview(v=>!v)}><Play size={15}/>{preview?'Pause trailer':'Play the trailer'}</button>}</article></div>}
  {embedded&&<aside className={`world-frame-tools ${help?'expanded':''}`}><button className="frame-name" aria-expanded={help} onClick={()=>setHelp(v=>!v)}><span>How to play <small>{project.title}</small></span>{help?<ChevronUp size={13}/>:<ChevronDown size={13}/>}</button>{help&&<div>{project.edition&&<p className="world-edition">{project.edition}</p>}<p className="world-start-guide">{guide?.start||project.subtitle}</p>{guide&&<><div className="world-key-chips" aria-label="Controls">{guide.keys.split(" · ").map(key=><span key={key}>{key}</span>)}</div><details className="world-guide-more"><summary>Your first discovery</summary><p>{guide.goal}</p></details></>}<a href={`/notes/${project.id}`}>Behind this world <ArrowUpRight size={14}/></a><button onClick={()=>{(setPhase('loading'),setAttempt(v=>v+1));setHelp(false);}}><RotateCcw size={14}/>Reload world</button><a href={project.url} target="_blank" rel="noreferrer" onClick={openOriginal}>Open original <ArrowUpRight size={14}/></a><button onClick={e=>e.currentTarget.closest('main')?.requestFullscreen?.().catch(()=>setNotice('Fullscreen is unavailable in this browser.'))}><Expand size={14}/>Fullscreen world</button></div>}</aside>}
  {embedded&&<CaptureControls project={project.id} title={project.title} sourceKind={local?'canvas':'tab'} selector={local?'iframe-world':undefined}/>}
  <WorldDock current={project.id} pulse={pulse} onFavorite={onFavorite}/>
  {notice&&<div className="toast" role="status">{notice}</div>}
 </main>;
}
